### ISSUE TITLE
Huawei K3770 Connection Parameters?

### ISSUE THREAD

**Issue by hbarnard** [gammu/gammu#100]
Hi, I noticed in another issue that this seems to 'work' for gammu-smsd. So I'm going to try it. However, I can't find connect parameter info in the gammu phone database? Grateful for a set of params therefore. Not really an issue, more of a documentation question. Best regards Hugh

**Comment by nijel** [comment]
I guess it will be same as K3765:

http://wammu.eu/phones/vodafone/6208/

**Comment by hbarnard** [comment]
Hi Michal, Thanks, I'll try! best regards Hugh

On 19 May 2015 at 10:29, Michal Čihař <notifications@github.com> wrote:

> I guess it will be same as K3765:
>
> http://wammu.eu/phones/vodafone/6208/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gammu/gammu/issues/100#issuecomment-103415259>.
>



-- 
http://www.hughbarnard.org
http://www.twitter.com/hughbarnard
http://www.big-wave-heuristics.com/
<http://www.hackney-environment-network.org.uk/>
