### ISSUE TITLE
wammu and gammu

### ISSUE THREAD

**Issue by pierreleonard** [gammu/gammu#103]
Hi all,

I run mageia 5 RC and had non fonctionnality with wammu.

When I launch wammu in a tty window with or without --debug parameters I have a  pop_up window for a bug :

bea265b2828e717887170a88e3978fef @gammu

24657 pts/3    Ss     0:00  \_ /bin/bash
24864 pts/3    Sl+    0:00      \_ /usr/bin/python /usr/bin/wammu

It seems not known.

Sincerely

Pierre Léonard

**Comment by nijel** [comment]
Can you please include the error message?

**Comment by pierreleonard** [comment]
Bonjour Michal Čihař ,
>
> Closed #103 <https://github.com/gammu/gammu/issues/103>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gammu/gammu/issues/103#event-308261607>.
>
sorry for that long time without asnwer.

The problem is that I have no error message with  :

  * wammu--debug  ,
  * gammu  --debug errors --info

but with : [pierre@alycanthe ~]$ gammu identify
Erreur lors de l'écriture sur le périphérique.

and the phone react with lighting up.


J'ai un Ultym5 vendu par bouygues with android 4.3

Many thanks for help

-- 
signature thunderbird

            La vie est belle          Pierre Léonard

http://www.leonard.nom.fr        Pierre@leonard.nom.fr
Tel : 01 39 02 71 67       --  Portable : 06 62 83 47 44


	Pierre
