### ISSUE TITLE
missing way to set SMSC manually

### ISSUE THREAD

**Issue by codemonkeyforever** [gammu/gammu#106]
I am using a old SAMSUNG QBOWL mobile phone with gammu-smsd 1.33 (debian testing), with the MYSQL backend. However, when I inject a new SMS, it cant be sent. According to the logs, gammu cant find out the SMSC of the mobile phone, so it sends some EMPTYSMC error code. 

Setting the SMSC for the mobile also does not work. Actually, sending SMS from the mobile phone works perfecly, but gammu does not find the SMSC out. Actually, I consider it not a modem specific problem, because there will always be some modems where this getsmsc command does not work. So there should be like in the other sms gateways some configuration option to the set the SMSC manually. Unfortunately, I didn~t find any way to set the SMSC manually. 

Or is there some hidden way to set it, or circumvent the problem?

**Comment by nijel** [comment]
Actually you can set SMSC for quite some time (since 6149d3aa), but it's not documented...

**Comment by codemonkeyforever** [comment]
Ahoj Michal,

I added the hidden "SMSC" option in the config file, and then it just worked perfectly! :-))
Thanks for your great work!

pa,
josef

**Comment by weblate** [comment]
Now it's also documented: http://wammu.eu/docs/manual/smsd/config.html#option-SMSC

**Comment by codemonkeyforever** [comment]
Thank you. Documentation sounds correct to me.
