### ISSUE TITLE
No DeliveryDateTime in DB while DeliveryReport present in log file.

### ISSUE THREAD

**Issue by whitehunter** [gammu/gammu#110]
Hi, I have trouble with delivery reports. Column DeliveryDateTime.sentitems in DB backend always is NULL while incoming SMS works fine and log file has "Delivery report: Delivered to... ".
I try to reinstall everything but still don't work. 
I expected that the problem with SMSC numbers. In DB i see different SMSC number for incoming and outputting SMS. I try to set one of this in gamma-smsdrc (with this option: SMSC = +7...) but no affecting.
 

sorry of my english

**Comment by nijel** [comment]
In this case you need to set option SkipSMSCNumber:  http://wammu.eu/docs/manual/smsd/config.html#option-SkipSMSCNumber

I've adjusted the code to give this hint in logs as well once this problem happens.
