### ISSUE TITLE
Multipart SMS via SQL

### ISSUE THREAD

**Issue by whitehunter** [gammu/gammu#112]
Shot SMS via SQL works fine: 
```
mysql> INSERT INTO outbox (
    ->     DestinationNumber,
    ->     TextDecoded,
    ->     CreatorID,
    ->     Coding
    -> ) VALUES (
    ->      '+7952722XXXX',
    ->     'Еденичнное сообщение',
    ->      'Program',
    ->      'Unicode_No_Compression'
    -> );
Query OK, 1 row affected (0,00 sec)
```

But when i try to send multipart message i got nothing:
```
INSERT INTO outbox (
    CreatorID,
    MultiPart,
    DestinationNumber,
    UDH,
    TextDecoded,
    Coding,
    Class
) VALUES (
    'Gammu 1.23.91',
    'true',
    '+7952722XXXX',
    '050003D30201',
    '11ывафывафывлапфыпфыафывафываыфвмчфмчмфывпфыафывапйцпцйпыпфыпимаим',
    'Unicode_No_Compression',
    0
);
INSERT INTO outbox_multipart (
    SequencePosition,
    UDH,
    TextDecoded,
    ID,
    Coding,
    Class
) VALUES (
    2,
    '050003D30202',
    '22выфафывпофдлыпвождфлыоаждлыфвоаждлфыовждалофыдлаофылаывлаenddddd',
    ID_FROM_OUTBOX_MSG,
    'Unicode_No_Compression',
    0 
);
```

What I'am doing wrong?

**Comment by nijel** [comment]
Do you see something in the log?

**Comment by whitehunter** [comment]
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: Using SQL service
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: Configuring Gammu SMSD...
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: SHM token: 0xffffffffce07fa56 (-838337962)
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: PIN code is "4976"
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: CommTimeout=10, SendTimeout=20, ReceiveFrequency=0, ResetFrequency=0, HardResetFrequency=0
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: checks: CheckSecurity=1, CheckBattery=1, CheckSignal=1
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: mode: Send=1, Receive=1
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: deliveryreport = sms
Wed 2015/07/08 15:45:48 gammu-smsd[1036]: phoneid = 1
Wed 2015/07/08 15:45:48 gammu-smsd[1037]: Connected to Database: gammu on localhost
Wed 2015/07/08 15:45:48 gammu-smsd[1037]: Database structures version: 14, SMSD current version: 14
Wed 2015/07/08 15:45:48 gammu-smsd[1037]: Connected to Database native_mysql: gammu on localhost
Wed 2015/07/08 15:45:48 gammu-smsd[1037]: Created POSIX RW shared memory at 0x10e04c000
Wed 2015/07/08 15:45:48 gammu-smsd[1037]: Starting phone communication...
Wed 2015/07/08 15:47:09 gammu-smsd[1037]: Inserting phone info
Wed 2015/07/08 15:47:10 gammu-smsd[1037]: Message: 11ывафывафывлапфыпфыафывафываыфвмчфмчмфывпфыафывапйцпцйпыпфыпимаим
Wed 2015/07/08 15:47:10 gammu-smsd[1037]: Message: 22выфафывпофдлыпвождфлыоаждлыфвоаждлфыовждалофыдлаофылаывлаenddddd
Wed 2015/07/08 15:47:10 gammu-smsd[1037]: New message to send: 13
Wed 2015/07/08 15:47:18 gammu-smsd[1037]: SMS sent on device: "/dev/tty.HUAWEIMobile-Modem" status=0, reference=97
Wed 2015/07/08 15:47:18 gammu-smsd[1037]: Transmitted 13 (part: 1) to +79527220901
Wed 2015/07/08 15:47:22 gammu-smsd[1037]: SMS sent on device: "/dev/tty.HUAWEIMobile-Modem" status=0, reference=98
Wed 2015/07/08 15:47:22 gammu-smsd[1037]: Transmitted 13 (total: 2) to +79527220901
Wed 2015/07/08 15:47:24 gammu-smsd[1037]: Received message from: +79527220901
Wed 2015/07/08 15:47:24 gammu-smsd[1037]: Read 1 messages
Wed 2015/07/08 15:47:24 gammu-smsd[1037]: Delivery report: Delivered to +79527220901
Wed 2015/07/08 15:47:24 gammu-smsd[1037]: Checking for delivery report, SMSC=+79505198000, state=SendingOK
Wed 2015/07/08 15:47:24 gammu-smsd[1048]: Starting run on receive: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 /Users/Andrey/my_django/production/phonebook/manage.py nosmsd_incoming
Wed 2015/07/08 15:47:24 gammu-smsd[1037]: Process failed with exit status 1
Wed 2015/07/08 15:47:32 gammu-smsd[1037]: Received message from: +79527220901
Wed 2015/07/08 15:47:32 gammu-smsd[1037]: Read 1 messages
Wed 2015/07/08 15:47:32 gammu-smsd[1037]: Delivery report: Delivered to +79527220901
Wed 2015/07/08 15:47:32 gammu-smsd[1037]: Checking for delivery report, SMSC=+79505198000, state=SendingOK
Wed 2015/07/08 15:47:32 gammu-smsd[1050]: Starting run on receive: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 /Users/Andrey/my_django/production/phonebook/manage.py nosmsd_incoming
Wed 2015/07/08 15:47:32 gammu-smsd[1037]: Process failed with exit status 1

Run on receive return error because I try to use django nosmsd. But when I try send sms via python, I got error, end now I try to did it via SQL.
