### ISSUE TITLE
"simple AT command to wake up" fails to parse "OK" response, if echo mode is still on

### ISSUE THREAD

**Issue by basinilya** [gammu/gammu#115]
My modem Huawei E3276.
Gammu enables echo mode at the beginning of communication.
This mode remains on, when gammu connects to it for the second time.

GDB shows that in GSM_DispatchMessage() the value of Reply[reply].requestID differs.
echo initially off: ID_Initialise
echo initially on: ID_IncomingFrame

Because the condition not met, gammu keeps waiting until timeout. However, if the modem periodically prints radio levels (which it does in 4g mode), timeout never occurs and gammu hangs forever.

Compare good and bad logs:
http://basinilya.googlecode.com/svn/wiki/gammu/echo/gammu.log-good
http://basinilya.googlecode.com/svn/wiki/gammu/echo/gammu.log-bad
http://basinilya.googlecode.com/svn/wiki/gammu/echo/gammu.log-bad-4g

response with echo: "\033\rAT\r\r\nOK\r\n"

Please answer: why is gammu trying to read the whole response into buffer instead of passing individual lines to GSM_DispatchMessage() ? Why is this StartStrings stuff needed?

**Comment by nijel** [comment]
This should be fixed in git (with fix for #136).
