### ISSUE TITLE
myPhone 6200 (MT6227) DUAL SIM not working with gammu and wammu. Please help.

### ISSUE THREAD

**Issue by kszere** [gammu/gammu#116]
### MODEL INFO ###
myPhone 6200 (MT6227) DUAL SIM
More info about this phone: http://www.myphone.pl/produkt/myphone-6200/

### DESCRIPTION PROBLEMS ###
Phone found in /dev/ttyACM0 or /dev/ttyUSB0
... but gammu and wammu cannot connect to this phone.

Also option connect by Bluetooth not working.

### GAMMU-DETECT OUTPUT ###
[gammu]
device = /dev/ttyUSB0
name = Port telefonu USB WALTON_Olvio_L14 WALTON_Olvio_L14
connection = at

### LSUSB OUTPUT ###
Bus 007 Device 006: ID 0e8d:0003 MediaTek Inc. MT6227 phone

### DMESG OUTPUT ###
[ 2116.240741] usb 7-1: new full-speed USB device number 2 using ohci-pci
[ 2116.421896] usb 7-1: New USB device found, idVendor=0e8d, idProduct=0003
[ 2116.421901] usb 7-1: New USB device strings: Mfr=3, Product=4, SerialNumber=0
[ 2116.421903] usb 7-1: Product: WALTON Olvio L14
[ 2116.421905] usb 7-1: Manufacturer: WALTON Olvio L14
[ 2116.569686] cdc_acm 7-1:1.1: ttyACM0: USB ACM device
[ 2116.572465] usbcore: registered new interface driver cdc_acm
[ 2116.572469] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[ 2116.622605] usbcore: registered new interface driver usbserial
[ 2116.623174] usbcore: registered new interface driver usbserial_generic
[ 2116.623708] usbserial: USB Serial support registered for generic
[ 2116.669538] usbcore: registered new interface driver option
[ 2116.669907] usbserial: USB Serial support registered for GSM modem (1-port)

**Comment by nijel** [comment]
Can you please provide debug log to see what went wrong with Gammu? See http://wammu.eu/support/bugs/

**Comment by KW4NP** [comment]
@nijel it looks like I have the same issue.  Different phone but same mt6227 chip.  Wammu can't connect although I can connect over AT.  Most AT commands return CME 100 for some reason.  Here is the debug log.
[wammu.log](https://github.com/gammu/gammu/files/3219254/wammu.log)

**Comment by jaboto** [comment]
Hey @KW4NP , did you solve the issue? I am facing the same problem with a TECNO phone

**Comment by KW4NP** [comment]
No, I wasn't able to solve the issue. Apparently this chip isn't supported
by gammu, so it won't work.  Sorry

**Comment by jaboto** [comment]
Oh, thanks anyway!
