### ISSUE TITLE
Errror-Report: An unhandled exception occurred condition

### ISSUE THREAD

**Issue by Ingolf2** [gammu/gammu#121]
Thanks for wammu.
I working fine with Motorola krzr k1 until the download calendar: An unhandled exception occurred condition.
Please write an eMail to me: IngolfPetersohn@i2pmail.org for the logfile.
I don`t know, how i can search for http://bugs.cihar.com/view_all_set.php?f=3&type=1&search=f5dcf26b92e570a43daaab11d9b7c425.
I give you the first 20 lines of the logfile:

--------------- System information ----------------
Platform     linux2
Python       2.7.6
wxPython     2.8.12.1
Wammu        0.36
python-gammu 1.33.0
Gammu        1.33.0
Bluetooth    None
locales      de_DE (UTF-8)
connection   at19200
device       /dev/ttyACM0
model        
Sat 2015/07/25 11:51:00: [Gammu            - 1.33.0 built 17:22:11 Jul 25 2013 using GCC 4.8]
Sat 2015/07/25 11:51:00: [Connection       - "at19200"]
Sat 2015/07/25 11:51:00: [Connection index - 0]
Sat 2015/07/25 11:51:00: [Model type       - ""]
Sat 2015/07/25 11:51:00: [Device           - "/dev/ttyACM0"]
Sat 2015/07/25 11:51:00: [Running on       - Linux, kernel 3.13.0-24-generic (#47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014)]
Sat 2015/07/25 11:51:00: Serial device: DTR is up, RTS is up, CAR is down, CTS is up

Best regards
Ingolf

**Comment by nijel** [comment]
Should be fixed in Wammu 0.40.
