### ISSUE TITLE
Wammu gives a Traceback with non-ascii home directory

### ISSUE THREAD

**Issue by goeranu** [gammu/gammu#122]
Whenever I start wammu, I only get a message window with a Python traceback.  It happens only to me on the system, not to other users.  It appears that the important difference is that my home directory contains non-ASCII letters.  If I create a fake pure ASCII home directory under /tmp and set the HOME environment variable to point to it, wammu starts.  But if that directory also contains any non-ASCII, wammu crashes again.

I couldn't easily copy and paste from the message window.  But I discovered that wammu-configure has a similar looking problem, with the same top of the Python stack.  So I attach that traceback instead.

This happens on Fedora with wammu-0.38-1.fc22.

To repeat:
1. mkdir /tmp/göran
2. HOME=/tmp/göran wammu

Traceback from wammu-configure:
> Traceback (most recent call last):
>   File "/usr/bin/wammu-configure", line 131, in <module>
>     do_wizard()
>   File "/usr/bin/wammu-configure", line 104, in do_wizard
>     wammu_cfg = Wammu.WammuSettings.WammuConfig()
>   File "/usr/lib/python2.7/site-packages/Wammu/WammuSettings.py", line 113, in __init__
>     self.InitGammu()
>   File "/usr/lib/python2.7/site-packages/Wammu/WammuSettings.py", line 122, in InitGammu
>     self.gammu = Wammu.GammuSettings.GammuSettings(self, path)
>   File "/usr/lib/python2.7/site-packages/Wammu/GammuSettings.py", line 41, in __init__
>     self.filename = self.wammu_cfg.Read('/Gammu/Gammurc')
>   File "/usr/lib/python2.7/site-packages/Wammu/WammuSettings.py", line 135, in Read
>     result = Wammu.OSUtils.ExpandPath(result)
>   File "/usr/lib/python2.7/site-packages/Wammu/OSUtils.py", line 61, in ExpandPath
>     return os.path.expanduser(orig)
>   File "/usr/lib64/python2.7/posixpath.py", line 280, in expanduser
>     return (userhome + path[i:]) or '/'
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)

**Comment by nijel** [comment]
This is really a bug in Wammu, can you please open the issue there: https://github.com/gammu/wammu/issues

I can open it there as well, but it's better to have correct reporter in case something needs to be clarified or tested.

**Comment by goeranu** [comment]
No problem, you find it here: https://github.com/gammu/wammu/issues/12

(Then, maybe I should make a report about the destination of the "Report bug" button too. :smile:)
