### ISSUE TITLE
own number

### ISSUE THREAD

**Issue by psy21d** [gammu/gammu#123]
Documentation troubles.
Need to get\set own number into sim (phone?).

There is instruction
http://www.8051projects.net/lofiversion/t51337/how-to-get-my-own-phone-number-using-at-commands.html

I was read libGammu documentation and cannot find it.
But I know, this function has in library!

Need some help to find, where it and how can to use. (C++)

**Comment by nijel** [comment]
You can use [GSM_SetMemory][1] with [GSM_MemoryEntry::MemoryType][2] = [MEM_ON][3] and [GSM_MemoryEntry::Location][4] = 1.

[1]:http://wammu.eu/docs/manual/c/memory.html#c.GSM_SetMemory
[2]:http://wammu.eu/docs/manual/c/memory.html#c.GSM_MemoryEntry::MemoryType
[3]:http://wammu.eu/docs/manual/c/memory.html#c.MEM_ON
[4]:http://wammu.eu/docs/manual/c/memory.html#c.GSM_MemoryEntry::Location

**Comment by psy21d** [comment]
OK it is really good, I will test it!
I can save number in this slot?

**Comment by nijel** [comment]
Yes, if phone supports that (some do and some do not).

**Comment by psy21d** [comment]
Yes, it works in console
AT+CPBW=1,"123456789"
this command store number into slot.

Then, I can AT+CNUM or
AT+CPBS="ON"
AT+CPBR=1
