### ISSUE TITLE
gammu-smsd - DeliveryReport not working due to timezone offset

### ISSUE THREAD

**Issue by rrudiger** [gammu/gammu#124]
Hello,

First, thanks for this great application.

Setup:
Debian wheezy with local time on Europe/Paris and system time to UTC.
Sqlite database
Gammu 1.36.4

Issue:
SendingDateTime is set by datetime('now') so UTC time.
When a Delivery report is received it compare the SendingDateTime to the SMS DateTime and find a gap of 2hours and some minutes.

Workaround:
I changed datetime(now) to datetime('now', 'localtime') for the query SQL_QUERY_ADD_SENT_INFO.

Am I missing a parameter somewhere to fix this without touching the code ?

Thanks, Romain.

```
select ID, UpdatedInDB, InsertIntoDB, SendingDateTime, DeliveryDateTime, TextDecoded, Status from sentitems;
Before the change:
6|2015-08-15 16:45:49|2015-08-15 16:41:13|2015-08-15 16:45:49||test Sat Aug 15 18:41:13 CEST 2015|SendingOK
After:
7|2015-08-15 17:12:51|2015-08-15 17:12:31|2015-08-15 19:12:47|2015-08-15 19:12:47|test Sat Aug 15 19:12:31 CEST 2015|DeliveryOK
```

**Comment by nijel** [comment]
Should be fixed in git, using localtime for SQLite indeed makes sense.
