### ISSUE TITLE
SMSD feature request: resend on SendingError [$50]

### ISSUE THREAD

**Issue by melones** [gammu/gammu#131]
I have a sporadical problem that once/twice a month my modem gets a timeout during sending a message. In such situation a message is not sent (it gets a "SendingError" Status in sentitems table in SMSD database). This causes that **the message is totally lost** (it is not being sent) and doesn't get to the user. 

My proposal is that SMSD service could have an ability to automatically resend such a message. But I imagine that in order to avoid looping, resending should be done only defined number of times. And a resent message should have a special flag that marks it as a resend (let's call it **RetryCount**) in outbox table. 

Some time ago there was a feature in SMSD service that allowed to resend a message if sending failed. This was described by a setting **MaxRetries** in SMSD configuration file. However right now, as far as I know, this feature is obsolete and doesn't work anymore. 

So I can imagine the following algorithm for this *resend feature* (a sketch):
1. A new flag **RetryCount** is added to outbox table of SMSD database. 
2. **MaxRetries** setting is used to control max number of retries. 
3. When SMSD gets "SendingError" during sending a message **RetryCount** is incremented for the message.  Then SMSD compares value of  **RetryCount** and **MaxRetries** setting. 
   * if  **RetryCount** <= **MaxRetries** then the message stays in outbox. SMSD will try to send it again.
   * if  **RetryCount** > **MaxRetries** then the message is moved to sentitems table with status "SendingError"

Would it be possible to implement in SMSD service?

**Comment by nijel** [comment]
The message is not totally lost, it's properly stored in SentItems with an error. You can use your application to enqueue it again. Adding some retrying to SMSD itself would be an option as well.

**Comment by melones** [comment]
nijel, you're perfectly right message is not lost. Would it be possible to add this retry feature to SMSD? I'll post a small bounty to appreciate the work of developer :)

**Comment by melones** [comment]
Hi nijel,
Is there any chance/timeframe for the implementation of this enhancement?

**Comment by nijel** [comment]
There is currently no timeframe for this. I should be able to get to this in December.

**Comment by nijel** [comment]
@melones, can you please try the smsd-retries branch? It should bring back previous MaxRetries logic. It's far from perfect (it relies on consistent sorting of messages from queue, what IMHO none of the backends guarantees by default), but should work quite good in cases when queue is not that full.

See https://github.com/gammu/gammu/tree/smsd-retries

**Comment by melones** [comment]
Thanks nijel. I'll test that in next days. Can you describe how it works in more algorithmic way? :)

**Comment by nijel** [comment]
The SMSD core always gets one message from the backend (eg. database or files). If it's ID (generated by backend) matches previous one, it considers it retry and checks MaxRetries. Otherwise it's considered as new message to send.

So if you have more messages in the queue, they will cycle and retries will be never detected (and failing messages will never be removed from queue).

In the end we will really need counting retries per message not globally, this is just a quick hack to restore previous behavior of MaxRetries...

**Comment by pavl00** [comment]
I've managed to do this feature some time ago: the messege is retried for X times, next try is +10 minutes. 
In a few days I will try to find my code and merge it with actual version.

**Comment by melones** [comment]
@pavl00 Did you manage to find your code?

**Comment by pavl00** [comment]
Yes. I'm testing it now.

**Comment by pavl00** [comment]
My modified version: https://github.com/pavl00/gammu
You can check if it is working for you.

**Comment by nijel** [comment]
Looks good, I've created #147 from that...

**Comment by melones** [comment]
Great! I'll test that and will give feedback.

**Comment by melones** [comment]
Test of the feature was succesfull. It works as expected! Thanks @pavl00

**Comment by nijel** [comment]
I've merged the change  and done some cleanup (see #147).
