### ISSUE TITLE
smsd doesn't accept delivery report if SMSC use different timezone

### ISSUE THREAD

**Issue by Thoajus** [gammu/gammu#132]
example:
Local system time zone is GMT+6
SMSC use time zone GMT+3 (Tele2 operator)
DeliveryReport = sms

smsd doesn't accept delivery reports:
```
Sat 2015/09/05 04:07:29 gammu-smsd[1797]: Checking for delivery report, SMSC=+79043490000, state=SendingOK
Sat 2015/09/05 04:07:29 gammu-smsd[1797]: Delivery report would match, but time delta is too big (-10800), consider increasing DeliveryReportDelay
Sat 2015/09/05 04:07:29 gammu-smsd[1797]: Failed to find SMS for TPMR=25, Number=
```
some files attached
https://gist.github.com/Thoajus/7dff41af6d42efdaed85

**Comment by Thoajus** [comment]
libgammu/misc/misc.c: GSM_GetLocalTimezoneOffset() doesn't work on my system - Linux Centos 6.7 x86_64 (see 'system.txt'): both pointers *tg,*tl look at the same CRT static variable. Function returns zero always.

I've a fix - see 'build-gammu-workaround.txt'

**Comment by nijel** [comment]
Thanks for the suggestion, I've based the fix on that, but rather used the thread safe _r variants to store the data directly into variables.

**Comment by gomanuke** [comment]
We are on 1.40 and problem is still here

Wed 2022/04/20 17:22:37 gammu-smsd[4988]: processing incoming SMS.
Wed 2022/04/20 17:22:37 gammu-smsd[4988]: Delivery report:  to
Wed 2022/04/20 17:22:37 gammu-smsd[4988]: Failed to find SMS for TPMR=0, Number=

**Comment by Thoajus** [comment]
You can try the patch I used originally for gammu 1.36.5 ([see  'build-gammu-workaround' from the first message files attached](https://gist.github.com/Thoajus/7dff41af6d42efdaed85#file-build-gammu-workaround)):
```
#!/bin/bash
patch --forward --backup --input - smsd/services/sql.c <<EOF
435c435,436
< 							SMSDSQL_Time2String(Config, Fill_Time_T(sms->SMSCTime), static_buff, sizeof(static_buff));
---
> 							// Fill_Time_T() ignores Timezone, so we need to move time from SMSC time zone to local system time zone manually
> 							SMSDSQL_Time2String(Config, Fill_Time_T(sms->SMSCTime) - sms->SMSCTime.Timezone + GSM_GetLocalTimezoneOffset(), static_buff, sizeof(static_buff));
646c647,649
< 					diff = t_time2 - t_time1;
---
> 					// Fill_Time_T() ignores Timezone, but SMSC time zone can differ from local system time zone
> 					// so both times are substracted time zone offset
> 					diff = (t_time2 - sms->SMS[i].DateTime.Timezone) - (t_time1 - GSM_GetLocalTimezoneOffset());
EOF
```
But I'm not sure about gammu 1.40

**Comment by gomanuke** [comment]
Appreciate for Your answer. 
It's sorry i have no experience to build a projects. 
Yes i see in sources sql.c where error is raised. But my efforts were to understand SQL_QUERY_SAVE_INBOX_SMS_SELECT satisfaction conditions. But no luck.

**Comment by gomanuke** [comment]
Debug shows that no chances: sql parameters are wrong

Thu 2022/04/21 10:36:28 gammu-smsd[1342]: processing incoming SMS.
Thu 2022/04/21 10:36:28 gammu-smsd[1342]: Delivery report:  to
Thu 2022/04/21 10:36:28 gammu-smsd[1342]: Execute SQL: SELECT `ID`, `Status`, `SendingDateTime`, `DeliveryDateTime`, `SMSCNumber` FROM sentitems WHERE `DeliveryDateTime` IS NULL AND `S
enderID` = '' AND `TPMR` = 0 AND `DestinationNumber` = ''
Thu 2022/04/21 10:36:28 gammu-smsd[1342]: Failed to find SMS for TPMR=0, Number=

**Comment by JACOBIN-SCTCS** [comment]
I am facing a similar error while trying to get delivery reports. Are there any fixes. Gammu Version : 1.42.0

Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Incoming LAC & CID info, ignoring
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: 1 "+CGREG: 1,29,28931"
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Checking line: +CGREG: 1,29,28931
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: AT reply state: 4
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: RECEIVED frame type 0x00/length 0x14/20
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: 2B+|43C|47G|52R|45E|47G|3A:|20 |311|2C,|322|399|2C,|322|388|399 +CGREG: 1,29,289
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: 333|311|0D |0A                                                  31..            
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: GPRS change
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: 1 "+CDSI: "SR",2"
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Checking line: +CDSI: "SR",2
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: AT reply state: 4
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: RECEIVED frame type 0x00/length 0x0F/15
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: 2B+|43C|44D|53S|49I|3A:|20 |22"|53S|52R|22"|2C,|322|0D |0A      +CDSI: "SR",2.. 
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Incoming SMS status report information
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Parsing  "SR",2
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu:  with  @r, @i
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Grabbed string from reply: "SR" (parsed 4 bytes)
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Parsed raw string "SR"
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: gammu: Parsed int 2
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: processing incoming SMS.
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: Delivery report:  to 
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: Execute SQL: SELECT `ID`, `Status`, `SendingDateTime`, `DeliveryDateTime`, `SMSCNumber` FROM sentitems WHERE `DeliveryDateTime` IS NULL AND `SenderID` = 'waveshare' AND `TPMR` = 0 AND `DestinationNumber` = ''
Sat 2025/04/26 12:17:47 gammu-smsd[5060]: Failed to find SMS for TPMR=0, Number=

**Comment by JACOBIN-SCTCS** [comment]
If anybody is facing issues with Delivery Report, You might look into the following possible suggestions which might work

1. Add the atgen_setCNMI option under [gammu] in your configuration file.  I had set the following option in my config

> atgen_setcnmi = ,,,1

References :
 a. https://docs.gammu.org/config/#option-atgen_setCNMI 
b.  https://docs.rs-online.com/5931/0900766b80bec52c.pdf [See AT+CNMI heading]


2. Modify the SMSDSQL_SaveInboxSMS function under  smsd/services/sql.c according to whether the sql query executed as a part of [Line no 741 (https://github.com/gammu/gammu/blob/2df3a8a9648b0d9101415ebf51f9a116741ba2d6/smsd/services/sql.c#L741) is returning any row from the database [Please check the smsd logs for the detailed SQL query].  In my case the destinationnumber from delivery report was missing a leading + sign due to which it was unable to fetch rows from the database.

Sample code which I had added for reference.

<img width="961" height="342" alt="Image" src="https://github.com/user-attachments/assets/913e3d13-82a2-44a3-8453-ddf7a6d32776" />

Hope this will help anybody who is stuck with delivery reports
