### ISSUE TITLE
Huawei K4510 Unknown frame

### ISSUE THREAD

**Issue by Didu75** [gammu/gammu#133]
Hi All,

I'm trying to send text messages via a Huawei K4510 and actually it's working but only once.  After sending a text messages the modem loses his connection to the network and need a hard reset to be functional again.  When running a debug it's complaining about an unknown frame and friendly asks to submit a bug report.  Well ok than, at your service :)

The *'s in the recipient number are manual editing to keep some privacy :)

[Gammu            - 1.31.90 built 08:54:06 May 23 2012 using GCC 4.6]
[Connection       - "at"]
[Connection index - 0]
[Model type       - ""]
[Device           - "/dev/ttyUSB3"]
[Running on       - Linux, kernel 4.1.6+ (#810 PREEMPT Tue Aug 18 15:19:58 BST 2015)]
Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Setting speed to 19200
[Module           - "auto"]
Escaping SMS mode
SENDING frametype 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frametype 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frametype 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "IRA""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|49I|52R|41A|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "IRA"....OK.. 
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "Vodafone (Huawei)"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x23/35
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |56V|6Fo|64d|61a|66f|6Fo AT+CGMI...Vodafo
6En|65e|20 |28(|48H|75u|61a|77w|65e|69i|29)|0D |0A |0D |0A |4FO ne (Huawei)....O
4BK|0D |0A                                                      K..             
Manufacturer info received
[Manufacturer: Huawei]
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
SENDING frametype 0x00/length 0x0E/14
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D          AT+CSCS="GSM".  
1 "AT+CSCS="GSM""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D |0D |0A  AT+CSCS="GSM"...
4FO|4BK|0D |0A                                                  OK..            
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
Getting model
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.        
1 "AT+CGMM"
2 "K4510"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x17/23
41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |4BK|344|355|311|300|0D  AT+CGMM...K4510.
0A |0D |0A |4FO|4BK|0D |0A                                      ...OK..         
Unknown model, but it should still work
[Model name: `K4510']
[Model data: `']
[Model data: `unknown']
[Connected model  - "K4510"]
Checking for OBEX support
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
[Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Escaping SMS mode
SENDING frametype 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frametype 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frametype 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "Vodafone (Huawei)"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x23/35
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |56V|6Fo|64d|61a|66f|6Fo AT+CGMI...Vodafo
6En|65e|20 |28(|48H|75u|61a|77w|65e|69i|29)|0D |0A |0D |0A |4FO ne (Huawei)....O
4BK|0D |0A                                                      K..             
Manufacturer info received
[Manufacturer: Huawei]
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
Checking for OBEX support
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
Checking for SYNCML/OBEX support
SENDING frametype 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frametype 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
Setting date & time
SENDING frametype 0x00/length 0x1F/31
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|311|355|2F/|300|399|2F/|300 AT+CCLK="15/09/0
355|2C,|311|388|3A:|322|322|3A:|355|366|2B+|300|300|22"|0D      5,18:22:56+00". 
1 "AT+CCLK="15/09/05,18:22:56+00""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x25/37
41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|311|355|2F/|300|399|2F/|300 AT+CCLK="15/09/0
355|2C,|311|388|3A:|322|322|3A:|355|366|2B+|300|300|22"|0D |0D  5,18:22:56+00"..
0A |4FO|4BK|0D |0A                                              .OK..           
Getting firmware versions
SENDING frametype 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.        
1 "AT+CGMR"
2 "11.810.09.16.11"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x21/33
41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|388|311|300 AT+CGMR...11.810
2E.|300|399|2E.|311|366|2E.|311|311|0D |0A |0D |0A |4FO|4BK|0D  .09.16.11....OK.
0A                                                              .               
Received firmware version: "11.810.09.16.11"
Number version is "11.810092"
[Firmware version - "11.810.09.16.11"]
[Connected]
Checking used: UDH len 0, UsedBytes 0, FreeText 160, UsedText 0, FreeBytes 140
Adding text
Copy 160 (max 6)
Defalt text, length 6 6
Text added
Checking at the end: UDH len 0, UsedBytes 6, FreeText 154, UsedText 6, FreeBytes 134
6 6
Entering GSM_GetSMSC
Getting SMSC
SENDING frametype 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|41A|3F?|0D                              AT+CSCA?.       
1 "AT+CSCA?"
2 "+CSCA: "+32475161616",145"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x2C/44
41A|54T|2B+|43C|53S|43C|41A|3F?|0D |0D |0A |2B+|43C|53S|43C|41A AT+CSCA?...+CSCA
3A:|20 |22"|2B+|333|322|344|377|355|311|366|311|366|311|366|22" : "+32475161616"
2C,|311|344|355|0D |0A |0D |0A |4FO|4BK|0D |0A                  ,145....OK..    
SMSC info received
Parsing +CSCA: "+32475161616",145 with +CSCA: @p, @i
Grabbed string from reply: "+32475161616" (parsed 14 bytes)
Parsed phone string "+32475161616"
Phone string decoded as "+32475161616"
Parsed int 145
Leaving GSM_GetSMSC
Entering GSM_SendSMS
Trying SMS PDU mode
SENDING frametype 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|47G|46F|3D=|300|0D                          AT+CMGF=0.      
1 "AT+CMGF=0"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frametype 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|47G|46F|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CMGF=0...OK..
SMS Submit
Recipient number "+32475******"
SMSC number "+32475161616"
SMS class -1
SMS validity ff
TPMR: 00 0
7 bit SMS, length 6, 6
Testje
Waiting for modem prompt
SENDING frametype 0x00/length 0x0B/11
41A|54T|2B+|43C|4DM|47G|53S|3D=|322|300|0D                      AT+CMGS=20.     
1 "AT+CMGS=20"
2 "> "
Checking line: > 
AT reply state: 7
RECEIVED frametype 0x00/length 0x0F/15
41A|54T|2B+|43C|4DM|47G|53S|3D=|322|300|0D |0D |0A |3E>|20      AT+CMGS=20...>  
Sending SMS
SENDING frametype 0x00/length 0x38/56
300|377|399|311|322|333|377|344|311|355|311|366|311|366|46F|366 07912374151616F6
311|311|300|300|300|42B|399|311|322|333|377|344|377|355|388|399 11000B9123747589
366|355|46F|344|300|300|300|300|46F|46F|300|366|44D|344|46F|322 65F40000FF06D4F2
399|43C|41A|45E|322|45E|300|333                                 9CAE2E03        
SENDING frametype 0x00/length 0x01/1
1A                                                              .               
Leaving GSM_SendSMS
1 "^RSSI:18"
Checking line: ^RSSI:18
AT reply state: 4
RECEIVED frametype 0x00/length 0x0A/10
5E^|52R|53S|53S|49I|3A:|311|388|0D |0A                          ^RSSI:18..      
1 "^CSNR:-77,-4"
Checking line: ^CSNR:-77,-4
AT reply state: 4
RECEIVED frametype 0x00/length 0x0E/14
5E^|43C|53S|4EN|52R|3A:|2D-|377|377|2C,|2D-|344|0D |0A          ^CSNR:-77,-4..  

UNKNOWN frame. If you can, please report it (see <http://wammu.eu/support/bugs/>). Thank you
RECEIVED frame type 0x00/length 0xe/14
5E^|43C|53S|4EN|52R|3A:|2D-|377|377|2C,|2D-|344|0D |0A          ^CSNR:-77,-4..  

1 "AT+CMGS=20"
2 "> 07912374151616F611000B912374758965F40000FF06D4F29CAE2E03"
3 "^SIMST:2"
4 "+CMS ERROR: 500"
Checking line: +CMS ERROR: 500
AT reply state: 5
RECEIVED frametype 0x00/length 0x68/104
41A|54T|2B+|43C|4DM|47G|53S|3D=|322|300|0D |0D |0A |3E>|20 |300 AT+CMGS=20...> 0
377|399|311|322|333|377|344|311|355|311|366|311|366|46F|366|311 7912374151616F61
311|300|300|300|42B|399|311|322|333|377|344|377|355|388|399|366 1000B91237475896
355|46F|344|300|300|300|300|46F|46F|300|366|44D|344|46F|322|399 5F40000FF06D4F29
43C|41A|45E|322|45E|300|333|0D |0A |0D |0A |5E^|53S|49I|4DM|53S CAE2E03....^SIMS
54T|3A:|322|0D |0A |0D |0A |2B+|43C|4DM|53S|20 |45E|52R|52R|4FO T:2....+CMS ERRO
52R|3A:|20 |355|300|300|0D |0A                                  R: 500..        
Error 500
Sent SMS on device: "/dev/ttyUSB3"
CMS Error 500: "unknown error"
[Terminating]
[Closing]

**Comment by nijel** [comment]
Please upgrade, this has been already fixed (13329d24).
