### ISSUE TITLE
Again with ^CSNR and slow boot of gammu

### ISSUE THREAD

**Issue by Bowser** [gammu/gammu#135]
Hi there,
I've encountered some troubles with that ^CSNR: command even after the upgrade (to this repository version) suggested in https://github.com/gammu/gammu/issues/133
In my case that command start to be sent by the modem (Huawei E372) close to the beginning of the communication and then continues to be received and misunderstanded by the application until it ends (but without causing any error, in my case).
It also seems (but i'm not sure) to contribute to let the start of gammu very slow, taking some long minutes without properly booting.

```
Tue 2015/09/15 02:36:18: [Gammu            - 1.36.6]
Tue 2015/09/15 02:36:18: [Connection       - "at115200"]
Tue 2015/09/15 02:36:18: [Connection index - 0]
Tue 2015/09/15 02:36:18: [Model type       - "at"]
Tue 2015/09/15 02:36:18: [Device           - "/dev/ttyUSB2"]
Tue 2015/09/15 02:36:18: [Running on       - Linux, kernel 3.16.0-4-amd64 (#1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04))]
Tue 2015/09/15 02:36:18: [Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|$
Tue 2015/09/15 02:36:18: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Tue 2015/09/15 02:36:18: Setting speed to 115200
Tue 2015/09/15 02:36:18: Escaping SMS mode
Tue 2015/09/15 02:36:18: SENDING frametype 0x00/length 0x02/2
Tue 2015/09/15 02:36:18: 1B |0D                                                          ..
Tue 2015/09/15 02:37:55: Sending simple AT command to wake up some devices
Tue 2015/09/15 02:37:55: SENDING frametype 0x00/length 0x03/3
Tue 2015/09/15 02:37:55: 41A|54T|0D                                                      AT.
Tue 2015/09/15 02:37:56: 1 "AT"
Tue 2015/09/15 02:37:56: 2 "OK"
Tue 2015/09/15 02:37:56: Checking line: OK
Tue 2015/09/15 02:37:56: AT reply state: 1
Tue 2015/09/15 02:37:56: RECEIVED frametype 0x00/length 0x09/9
Tue 2015/09/15 02:37:56: 41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..
Tue 2015/09/15 02:38:00: 1 "^RSSI:23"
Tue 2015/09/15 02:38:00: Checking line: ^RSSI:23
Tue 2015/09/15 02:38:00: AT reply state: 4
Tue 2015/09/15 02:38:00: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 02:38:00: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..
Tue 2015/09/15 02:38:00: 1 "^CSNR:-72,-4"
Tue 2015/09/15 02:38:00: Checking line: ^CSNR:-72,-4
Tue 2015/09/15 02:38:00: AT reply state: 4
Tue 2015/09/15 02:38:00: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 02:38:00: 5E^|43C|53S|4EN|52R|3A:|2D-|377|322|2C,|2D-|344|0D |0A          ^CSNR:-72,-4..
Tue 2015/09/15 02:38:00:
Tue 2015/09/15 02:38:00: UNKNOWN frame. Please report the error, see <http://wammu.eu/support/bugs/>. Thank you
Tue 2015/09/15 02:38:00: LAST SENT frame type 0x00/length 3
Tue 2015/09/15 02:38:00: 41A|54T|0D                                                      AT.
Tue 2015/09/15 02:38:00: RECEIVED frame type 0x00/length 0xe/14
Tue 2015/09/15 02:38:00: 5E^|43C|53S|4EN|52R|3A:|2D-|377|322|2C,|2D-|344|0D |0A          ^CSNR:-72,-4..
Tue 2015/09/15 02:38:00:
Tue 2015/09/15 02:38:03: 1 "^BOOT:44964621,0,0,0,99"
Tue 2015/09/15 02:38:03: Checking line: ^BOOT:44964621,0,0,0,99
Tue 2015/09/15 02:38:03: AT reply state: 4
Tue 2015/09/15 02:38:03: RECEIVED frametype 0x00/length 0x19/25
Tue 2015/09/15 02:38:03: 5E^|42B|4FO|4FO|54T|3A:|344|344|399|366|344|366|322|311|2C,|300 ^BOOT:44964621,0
Tue 2015/09/15 02:38:03: 2C,|300|2C,|300|2C,|399|399|0D |0A                              ,0,0,99..
Tue 2015/09/15 02:38:03: 1 "^RSSI:23"
Tue 2015/09/15 02:38:03: Checking line: ^RSSI:23
Tue 2015/09/15 02:38:03: AT reply state: 4
Tue 2015/09/15 02:38:03: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 02:38:03: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..
Tue 2015/09/15 02:38:03: 1 "^CSNR:-70,-2"
Tue 2015/09/15 02:38:03: Checking line: ^CSNR:-70,-2
Tue 2015/09/15 02:38:03: AT reply state: 4
Tue 2015/09/15 02:38:03: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 02:38:03: 5E^|43C|53S|4EN|52R|3A:|2D-|377|300|2C,|2D-|322|0D |0A          ^CSNR:-70,-2..
Tue 2015/09/15 02:38:03:
Tue 2015/09/15 02:38:03: UNKNOWN frame. Please report the error, see <http://wammu.eu/support/bugs/>. Thank you
Tue 2015/09/15 02:38:03: LAST SENT frame type 0x00/length 3
Tue 2015/09/15 02:38:03: 41A|54T|0D                                                      AT.

...... 

Tue 2015/09/15 02:39:27: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 02:39:27: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..
Tue 2015/09/15 02:39:27: 1 "^CSNR:-71,-4"
Tue 2015/09/15 02:39:27: Checking line: ^CSNR:-71,-4
Tue 2015/09/15 02:39:27: AT reply state: 4
Tue 2015/09/15 02:39:27: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 02:39:27: 5E^|43C|53S|4EN|52R|3A:|2D-|377|311|2C,|2D-|344|0D |0A          ^CSNR:-71,-4..
Tue 2015/09/15 02:39:27:
Tue 2015/09/15 02:39:27: UNKNOWN frame. Please report the error, see <http://wammu.eu/support/bugs/>. Thank you
Tue 2015/09/15 02:39:27: LAST SENT frame type 0x00/length 3
Tue 2015/09/15 02:39:27: 41A|54T|0D                                                      AT.
Tue 2015/09/15 02:39:27: RECEIVED frame type 0x00/length 0xe/14
Tue 2015/09/15 02:39:27: 5E^|43C|53S|4EN|52R|3A:|2D-|377|311|2C,|2D-|344|0D |0A          ^CSNR:-71,-4..
Tue 2015/09/15 02:39:27:
Tue 2015/09/15 02:39:33: 1 "^BOOT:44964621,0,0,0,99"
Tue 2015/09/15 02:39:33: Checking line: ^BOOT:44964621,0,0,0,99
Tue 2015/09/15 02:39:33: AT reply state: 4
Tue 2015/09/15 02:39:33: RECEIVED frametype 0x00/length 0x19/25
Tue 2015/09/15 02:39:33: 5E^|42B|4FO|4FO|54T|3A:|344|344|399|366|344|366|322|311|2C,|300 ^BOOT:44964621,0
Tue 2015/09/15 02:39:33: 2C,|300|2C,|300|2C,|399|399|0D |0A                              ,0,0,99..
Tue 2015/09/15 02:39:36: 1 "^RSSI:23"
Tue 2015/09/15 02:39:36: Checking line: ^RSSI:23
Tue 2015/09/15 02:39:36: AT reply state: 4
Tue 2015/09/15 02:39:36: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 02:39:36: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..
Tue 2015/09/15 02:39:36: 1 "^CSNR:-70,-2"
Tue 2015/09/15 02:39:36: Checking line: ^CSNR:-70,-2
Tue 2015/09/15 02:39:36: AT reply state: 4
Tue 2015/09/15 02:39:36: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 02:39:36: 5E^|43C|53S|4EN|52R|3A:|2D-|377|300|2C,|2D-|322|0D |0A          ^CSNR:-70,-2..
Tue 2015/09/15 02:39:36:
Tue 2015/09/15 02:39:36: UNKNOWN frame. Please report the error, see <http://wammu.eu/support/bugs/>. Thank you
Tue 2015/09/15 02:39:36: LAST SENT frame type 0x00/length 3
Tue 2015/09/15 02:39:36: 41A|54T|0D                                                      AT.
Tue 2015/09/15 02:39:36: RECEIVED frame type 0x00/length 0xe/14
Tue 2015/09/15 02:39:36: 5E^|43C|53S|4EN|52R|3A:|2D-|377|300|2C,|2D-|322|0D |0A          ^CSNR:-70,-2..
Tue 2015/09/15 02:39:36:
Tue 2015/09/15 02:39:55: Enabling echo
Tue 2015/09/15 02:39:55: SENDING frametype 0x00/length 0x05/5
Tue 2015/09/15 02:39:55: 41A|54T|45E|311|0D                                              ATE1.
Tue 2015/09/15 02:39:55: 1 "ATE1"
Tue 2015/09/15 02:39:55: 2 "OK"
Tue 2015/09/15 02:39:55: Checking line: OK
Tue 2015/09/15 02:39:55: AT reply state: 1
Tue 2015/09/15 02:39:55: RECEIVED frametype 0x00/length 0x0B/11
Tue 2015/09/15 02:39:55: 41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..
Tue 2015/09/15 02:39:55: Trying Motorola mode switch
Tue 2015/09/15 02:39:55: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 02:39:55: 41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.
```

I checked and the previous posted fix is present in the code before compiling, so it's strange that gammu is still not properly understanding that command. Another strange thing is that the command seems to be successfully received some times and some other times not.

As a little digression I saw that version error using gammu from the last version of the repo from the command line:
Error: Version of installed libGammu.so (1.36.6) is different to version of Gammu (1.36.5)

Thank you for you help and for this very useful product anyway :+1:

**Comment by nijel** [comment]
Okay, I forgot to add half of the code. Should be really fixed now.

**Comment by Bowser** [comment]
It is. No more unknown frame.

However, why gammu is taking so long (up to 5 minutes now) to enable echo?

Tue 2015/09/15 09:56:51: [Gammu            - 1.36.6]
Tue 2015/09/15 09:56:51: [Connection       - "at"]
Tue 2015/09/15 09:56:51: [Connection index - 0]
Tue 2015/09/15 09:56:51: [Model type       - "at"]
Tue 2015/09/15 09:56:51: [Device           - "/dev/ttyUSB2"]
Tue 2015/09/15 09:56:51: [Running on       - Linux, kernel 3.16.0-4-amd64 (#1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04))]
Tue 2015/09/15 09:56:51: [Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|$
Tue 2015/09/15 09:56:51: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Tue 2015/09/15 09:56:51: Setting speed to 19200
Tue 2015/09/15 09:56:51: Escaping SMS mode
Tue 2015/09/15 09:56:51: SENDING frametype 0x00/length 0x02/2
Tue 2015/09/15 09:56:51: 1B |0D                                                          ..
Tue 2015/09/15 09:56:52: Sending simple AT command to wake up some devices
Tue 2015/09/15 09:56:52: SENDING frametype 0x00/length 0x03/3
Tue 2015/09/15 09:56:52: 41A|54T|0D                                                      AT.
Tue 2015/09/15 09:56:52: 1 "AT"
Tue 2015/09/15 09:56:52: 2 "OK"
Tue 2015/09/15 09:56:52: Checking line: OK
Tue 2015/09/15 09:56:52: AT reply state: 1
Tue 2015/09/15 09:56:52: RECEIVED frametype 0x00/length 0x09/9
Tue 2015/09/15 09:56:52: 41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..
Tue 2015/09/15 09:56:53: 1 "^RSSI:23"
Tue 2015/09/15 09:56:53: Checking line: ^RSSI:23
Tue 2015/09/15 09:56:53: AT reply state: 4
Tue 2015/09/15 09:56:53: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 09:56:53: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..
Tue 2015/09/15 09:56:53: 1 "^CSNR:-66,-3"
Tue 2015/09/15 09:56:53: Checking line: ^CSNR:-66,-3
Tue 2015/09/15 09:56:53: AT reply state: 4
Tue 2015/09/15 09:56:53: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 09:56:53: 5E^|43C|53S|4EN|52R|3A:|2D-|366|366|2C,|2D-|333|0D |0A          ^CSNR:-66,-3..
Tue 2015/09/15 09:56:56: 1 "^RSSI:23"
Tue 2015/09/15 09:56:56: Checking line: ^RSSI:23
Tue 2015/09/15 09:56:56: AT reply state: 4

... Continues for 5 minutes this way ...

Tue 2015/09/15 10:01:30: Enabling echo
Tue 2015/09/15 10:01:30: SENDING frametype 0x00/length 0x05/5
Tue 2015/09/15 10:01:30: 41A|54T|45E|311|0D                                              ATE1.
Tue 2015/09/15 10:01:30: 1 "ATE1"
Tue 2015/09/15 10:01:30: 2 "OK"
Tue 2015/09/15 10:01:30: Checking line: OK
Tue 2015/09/15 10:01:30: AT reply state: 1
Tue 2015/09/15 10:01:30: RECEIVED frametype 0x00/length 0x0B/11
Tue 2015/09/15 10:01:30: 41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..

**Comment by nijel** [comment]
I've created separate issue for that - #136. Can you please post there a bit more of the log to see how frequently do these arrive? It seems that sometimes Gammu is waiting too long.
