### ISSUE TITLE
unknow frame type and non printable char

### ISSUE THREAD

**Issue by mrkrash** [gammu/gammu#137]
Hi,
I have implemented gammu-smsd on raspbian with a sim800L chip modem.
System work slowly. On log I have some non printable char and "unknow frame type" error.
Distribution is latest Raspbian on raspberry B.
Modem is SIM800L by SIMCOM.
Thi is relevant section of my config file:
> [gammu]
> port = /dev/ttyAMA0
> connection = at19200
> startinfo = yes
> logformat = textalldate
>
> [smsd]
> service = sql
> driver = native_mysql

This is an extract of my debug log where gammu recognize my modem:

> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: Getting model
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: SENDING frametype 0x00/length 0x08/8
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: 41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: 1 "AT+CGMM"
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: 2 "SIMCOM_SIM800L"
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: 3 "OK"
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: Checking line: OK
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: AT reply state: 1
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: RECEIVED frametype 0x00/length 0x20/32
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: 41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |53S|49I|4DM|43C|4FO|4DM AT+CGMM...SIMCOM
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: 5F_|53S|49I|4DM|388|300|300|4CL|0D |0A |0D |0A |4FO|4BK|0D |0A  _SIM800L....OK..
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: Unknown model, but it should still work
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: [Model name: `SIMCOM_SIM800L']
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: [Model data: `']
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: [Model data: `unknown']
> Sat 2015/09/19 18:28:22 gammu-smsd[3983]: gammu: [Connected model  - "SIMCOM_SIM800L"]

This is a sample error:

> Sat 2015/09/19 19:01:27 gammu-smsd[4111]: gammu: Entering GSM_GetSMSStatus
> Sat 2015/09/19 19:01:27 gammu-smsd[4111]: gammu: Getting SIM SMS status
> Sat 2015/09/19 19:01:27 gammu-smsd[4111]: gammu: SENDING frametype 0x00/length 0x12/18
> Sat 2015/09/19 19:01:27 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
> Sat 2015/09/19 19:01:27 gammu-smsd[4111]: gammu: 22"|0D                                                          ".              
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: [Retrying 1 type 0x00]
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: SENDING frametype 0x00/length 0x12/18
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 22"|0D                                                          ".              
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 1 "AT+CP�_="SM","�J��Hhi
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: �*'$&)�b�b��b�b��jRjRz-5)�AT+CPMS="SM","SM""
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 2 "+CPMS: 0,10,0,10,0,10"
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 3 "OK"
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: Checking line: OK
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: AT reply state: 1
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: RECEIVED frametype 0x00/length 0x61/97
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|CD |5F_|3D=|22"|53S|4DM|22"|2C,|22"|F3 |4AJ AT+CP._="SM",".J
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: A9 |A8 |48H|68h|69i|0A |D5 |2A*|27'|24$|26&|29)|82 |62b|82 |62b ..Hhi..*'$&).b.b
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 8A |82 |62b|82 |62b|8A |82 |6Aj|52R|6Aj|52R|7Az|2D-|355|29)|FF  ..b.b..jRjRz-5).
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|311|300|2C, "...+CPMS: 0,10,
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 300|2C,|311|300|2C,|300|2C,|311|300|0D |0A |0D |0A |4FO|4BK|0D  0,10,0,10....OK.
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 0A                                                              .               
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: UNKNOWN frame. If you can, please report it (see <http://wammu.eu/support/bugs/>). Thank you
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: LAST SENT frame type 0x00/length 18
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 22"|0D                                                          ".              
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: RECEIVED frame type 0x00/length 0x61/97
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|CD |5F_|3D=|22"|53S|4DM|22"|2C,|22"|F3 |4AJ AT+CP._="SM",".J
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: A9 |A8 |48H|68h|69i|0A |D5 |2A*|27'|24$|26&|29)|82 |62b|82 |62b ..Hhi..*'$&).b.b
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 8A |82 |62b|82 |62b|8A |82 |6Aj|52R|6Aj|52R|7Az|2D-|355|29)|FF  ..b.b..jRjRz-5).
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|311|300|2C, "...+CPMS: 0,10,
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 300|2C,|311|300|2C,|300|2C,|311|300|0D |0A |0D |0A |4FO|4BK|0D  0,10,0,10....OK.
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 0A                                                              .               
> Sat 2015/09/19 19:01:46 gammu-smsd[4111]: gammu: 
> Sat 2015/09/19 19:02:05 gammu-smsd[4111]: gammu: GSM_GetSMSStatus failed with error TIMEOUT[14]: Nessuna risposta nel tempo specificato. Probabilmente il telefono non è connesso.
> Sat 2015/09/19 19:02:05 gammu-smsd[4111]: gammu: Leaving GSM_GetSMSStatus
> Sat 2015/09/19 19:02:05 gammu-smsd[4111]: Error getting SMS status: Nessuna risposta nel tempo specificato. Probabilmente il telefono non è connesso. (TIMEOUT[14])

Next, Gammu re-send the same query and it's ok.
Can I do something?
Mario.

**Comment by nijel** [comment]
Isn't there some other program talking to the device? Also using newer Gammu version should help, there were some fixes for this device.
