### ISSUE TITLE
Wammu 0.37 not opening 'Send Message' window in Debian Jessie 8.1

### ISSUE THREAD

**Issue by Jcj1610** [gammu/gammu#139]
Creating a message using Ctrl+M or [Create] > [Message] results in 'Unhandled exception' error on Debian Jessie 8.1. 

![error](https://cloud.githubusercontent.com/assets/14890803/10166630/3a8f76ca-66c5-11e5-9b08-a327568485a4.png)

--------------- System information ----------------
Platform     linux2
Python       2.7.9
wxPython     3.0.1.1
Wammu        0.37
python-gammu 1.33.0
Gammu        1.33.0
Bluetooth    PyBluez
locales      en_US (UTF-8)
connection   bluephonet
device       6C:9B:02:65:1B:61
model        

------------------ Traceback ID -------------------
d897b2bd315e8fabb6045c175227b10e
-------------------- Traceback --------------------
  File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 1039, in NewMessage
    self.ComposeMessage({})
  File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 1042, in ComposeMessage
    if Wammu.Composer.SMSComposer(self, self.cfg, v, self.values, action).ShowModal() == wx.ID_OK:
  File "/usr/lib/python2.7/dist-packages/Wammu/Composer.py", line 410, in __init__
    self.sizer.AddGrowableRow(row)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 15343, in AddGrowableRow
    return _core_.FlexGridSizer_AddGrowableRow(*args, **kwargs)
-------------------- Exception --------------------
PyAssertionError: C++ assertion "!m_rows || idx < (size_t)m_rows" failed at ../src/common/sizer.cpp(1967) in AddGrowableRow(): invalid row index
---------------------------------------------------

**Comment by nijel** [comment]
This was already fixed in later releases.
