### ISSUE TITLE
Nokia 6303 Classic Unknown response

### ISSUE THREAD

**Issue by marekzukal** [gammu/gammu#14]
Tue 2013/07/30 17:21:09: 
Tue 2013/07/30 17:21:09: UNKNOWN response. If you can, please report it (see <http://cihar.com/gammu/report>). Thank you
Tue 2013/07/30 17:21:09: LAST SENT frame type 0x00/length 10
Tue 2013/07/30 17:21:09: 41A|54T|2B+|43C|50P|42B|52R|3D=|311|0D                          AT+CPBR=1.      
Tue 2013/07/30 17:21:09: RECEIVED frame type 0x00/length 0x7e/126
Tue 2013/07/30 17:21:09: 41A|54T|2B+|43C|50P|42B|52R|3D=|311|0D |0D |0A |2B+|43C|50P|42B AT+CPBR=1...+CPB
Tue 2013/07/30 17:21:09: 52R|3A:|20 |311|2C,|22"|2B+|344|322|300|377|322|355|377|388|377 R: 1,"+420725787
Tue 2013/07/30 17:21:09: 366|322|355|22"|2C,|311|344|355|2C,|22"|300|300|344|41A|300|300 625",145,"004A00
Tue 2013/07/30 17:21:09: 366|355|300|300|366|344|300|300|366|46F|300|300|366|45E|300|300 650064006F006E00
Tue 2013/07/30 17:21:09: 366|355|300|300|366|42B|300|300|322|300|300|300|377|300|300|300 65006B0020007000
Tue 2013/07/30 17:21:09: 377|322|300|300|366|311|300|300|366|333|300|300|322|300|300|300 7200610063002000
Tue 2013/07/30 17:21:09: 344|311|300|300|366|43C|300|300|366|355|300|311|366|311|22"|2C, 41006C00650161",
Tue 2013/07/30 17:21:09: 2C,|2C,|2C,|2C,|2C,|2C,|0D |0A |0D |0A |4FO|4BK|0D |0A          ,,,,,,....OK..  
Tue 2013/07/30 17:21:09: 
Tue 2013/07/30 17:21:09: GSM_GetMemory failed with error UNKNOWNRESPONSE[16]: Unknown response from phone. See <http://cihar.com/gammu/report> for information how to report it.

**Comment by nijel** [comment]
This should be fixed in recent Gammu versions since 29a5bdc2.
