### ISSUE TITLE
smsd RunonReceive/Files backend with unicode

### ISSUE THREAD

**Issue by rcoup** [gammu/gammu#143]
RunOnReceive seems to get messages like `EMOJI 🚀 TEST` as `EMOJI ?? TEST` via the `SMS_1_TEXT` environment variable passed to the RunOnReceive. That's also how it is stored in the smsd Inbox folder for the message (Files backend).

I've tried setting the encoding via the config file, but it didn't appear to change anything.
```
[gammu]
gammucoding = utf8
...
[smsd]
...
```
The docs say InboxFormat=unicode by default for the files backend. A gammu debug log is at https://gist.github.com/rcoup/9cd74e96db2c0fca9807 (just connects & receives a single message with the above).

AFAICT from the log the message PDU is `07914672477306F00404B128220008511150106362251A0045004D004F004A00490020D83DDE8000200054004500530054` which http://smspdu.benjaminerhart.com/ appears to decode correctly, so I think it's a gammu issue. The codepoint for 🚀 is `u+1f680`.

This is on OSX running Gammu 1.36.5, `$LANG=en_NZ.UTF-8`. Any suggestions?

**Comment by nijel** [comment]
It should be already fixed for database backends (see #8), but probably not yet for other places. The problem is that encoding anything above ``u+ffff`` is not possible in UCS-2 (used internally by gammu and specified for SMS messages, though it's actually using UTF-16 now).

**Comment by rcoup** [comment]
From looking at `DecodeUnicodeConsole()`, seems like it should be using `EncodeUTF8()` when `gammucoding=utf8`, which seems to support all chars? I can see `DecodeUnicode()` (the other code path) calls `DecodeWithUnicodeAlphabet()` which looks like it might do `?` substitutions...

So maybe the encoding is not being set correctly?
