### ISSUE TITLE
Huawei E180 not working snappy on smsd

### ISSUE THREAD

**Issue by pdorn87** [gammu/gammu#146]
We are trying to build a sms gateway using gammu smsd however we are experiencing some problems.
Quite often the daemon (according to the logfile) is only in an infinite loop processing RSSI data:

Fri 2015/11/20 13:13:13 gammu-smsd[23431]: gammu: 1 "^RSSI:31"
Fri 2015/11/20 13:13:13 gammu-smsd[23431]: gammu: Checking line: ^RSSI:31
Fri 2015/11/20 13:13:13 gammu-smsd[23431]: gammu: AT reply state: 4
Fri 2015/11/20 13:13:13 gammu-smsd[23431]: gammu: RECEIVED frame type 0x00/length 0x0A/10
Fri 2015/11/20 13:13:13 gammu-smsd[23431]: gammu: 5E^|52R|53S|53S|49I|3A:|333|311|0D |0A                          ^RSSI:31..  

This just keeps going on and on, and sometimes it never ends up inserting the phone into MySQL or it takes a very long time. When it is inserted, its no guarantee it's working from that point on. The outbox is not always processed and the 'UpdatedInDB' column in MySQL in not being updated. The MySQL connection is working OK and there are no errors regarding MySQL in the logfile.

This is the 'startup data' from the logfile:

Fri 2015/11/20 13:08:04 gammu-smsd[23431]: Connected to Database: xxx on xxx
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: Connected to Database native_mysql: xxx on xxx
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: Created POSIX RW shared memory at 0x76fc5000
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: Starting phone communication...
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Gammu            - 1.36.6]
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Connection       - "at"]
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Connection index - 0]
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Model type       - ""]
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Device           - "/dev/custom/pt-voda-sms"]
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Running on       - Linux, kernel 3.18.0-25-rpi2 (#26-Ubuntu SMP PREEMPT Sun Jul 5 06:46:34 UTC 2015)]
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: Locking device
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: Lockfile /var/lock/LCK..pt-voda-sms is stale. Overriding it..
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: Setting speed to 115200
Fri 2015/11/20 13:08:04 gammu-smsd[23431]: gammu: [Module           - "auto"]

Below the current config:
[gammu]
port  = /dev/custom/pt-voda-sms
connection = at
use_locking = yes
logformat = textall

[smsd]
LogFile = /var/log/gammu-smsd-pt-voda.log
DebugLevel = 4
CommTimeout = 30
SendTimeout = 30
MaxRetries = 1
ReceiveFrequency = 4
StatusFrequency = 4
LoopSleep = 1
CheckSecurity = 1
HangupCalls = 1
CheckBattery = 0
CheckSignal = 0
ResetFrequency = 0
HardResetFrequency = 0
PhoneID = pt-voda
Send = True
Receive = True

Service = SQL
Driver = native_mysql
Host = xxx
User = xxx
Password = xxx
Database = xxx

Hope you can help me get this fixed!

**Comment by nijel** [comment]
Can you try uslng latest version from Git? It contains several improvements for Huawei modems (see #4).

**Comment by pdorn87** [comment]
Hi!

Just downloaded master.zip and installed over the existing version (there's no uninstall, is there?)
Have been waiting for 2 minutes now and still it hasn't inserted itself into the DB. All I keep seeing is the RSSI communication.

Any suggestions?

**Comment by pdorn87** [comment]
It started working and started 5 instances, but now the Raspberry Pi is hanging. Have you ever tested with that much instances at the same time?

**Comment by nijel** [comment]
Not on RPI, but on regular systems I know users who are running about 100 instances..

**Comment by pdorn87** [comment]
Ok nice! The SMSD seems to be working way better at the moment, however I found another problem now. Could it be that your fix means playing with the PORTSEL and CURC command? When I stop the SMSD it appears that info like RSSI is being delivered to another TTY. This was never happening with previous versions gammu-smsd.

**Comment by nijel** [comment]
That might be the side effect. We just tell the modem that this is interface where it should act as a modem...

**Comment by pdorn87** [comment]
Ok. The problem here is that I have to shutdown the smsd when I want to send out an USSD, because smsd locks the TTY. However, because the TTY is registered as modem, I cannot use the gammu getussd command anymore (the response is being delivered to another TTY).

I guess a nice feature of SMSD would be to support sending USSD's and prevent me the hassle of stopping/starting the daemon :-)

**Comment by nijel** [comment]
I think that's already somewhere reported....

**Comment by nijel** [comment]
Anyway the locking is intentional to avoid two programs accessing same TTY (otherwise there is no guarantee that the one who wrote message will get the response). The USSD for SMSD is tracked as https://github.com/gammu/gammu/issues/150
