### ISSUE TITLE
Error at init connection - DEVICENOTEXIST

### ISSUE THREAD

**Issue by PhilipLykov** [gammu/gammu#148]
I use the latest version of SMSD from GIT on CentOS 7. I use Huawei e1552 modems and connect to them with the following config (just a part of the config file):
[gammu]
device = /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1.5:1.0-port0
connection = at

Sometime I receive the following errors in the log just after restart of the service. At that time can connect with minicom to the device specified above without any problem, it answers to 'ATI' command well.

Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Starting phone communication...
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Starting phone communication...
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Starting phone communication...
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Starting phone communication...
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Sun 2015/11/22 00:39:23 gammu-smsd[2367]: Going to 30 seconds sleep because of too much connection errors
Sun 2015/11/22 00:39:53 gammu-smsd[2367]: Starting phone communication...
Sun 2015/11/22 00:39:58 gammu-smsd[2367]: Soft reset return code: No error. (NONE[1])

Only reboot helps. Service restart does't help.

**Comment by nijel** [comment]
Are you sure you're connecting with minicom to the same device?

**Comment by PhilipLykov** [comment]
Yes, absolutely. I did it with cut and paste from the config file. I have such problem with different modems on different ports. It happened many times for last few days.

**Comment by PhilipLykov** [comment]
The problem still there:

==================
[root@smsd ~]# ls /dev/serial/by-path/ -l
total 0
lrwxrwxrwx. 1 root root 13 Dec  3 11:24 pci-0000:00:14.0-usb-0:2:1.0-port0 -> ../../ttyUSB0
lrwxrwxrwx. 1 root root 13 Dec  3 11:24 pci-0000:00:14.0-usb-0:2:1.1-port0 -> ../../ttyUSB1
lrwxrwxrwx. 1 root root 13 Dec  3 11:24 pci-0000:00:14.0-usb-0:2:1.2-port0 -> ../../ttyUSB2
lrwxrwxrwx. 1 root root 13 Dec  3 11:24 pci-0000:00:14.0-usb-0:3:1.0-port0 -> ../../ttyUSB3
lrwxrwxrwx. 1 root root 13 Dec  3 11:24 pci-0000:00:14.0-usb-0:3:1.1-port0 -> ../../ttyUSB4
lrwxrwxrwx. 1 root root 13 Dec  3 11:24 pci-0000:00:14.0-usb-0:3:1.2-port0 -> ../../ttyUSB5
lrwxrwxrwx. 1 root root 13 Dec  3 11:35 pci-0000:00:1d.0-usb-0:1.5:1.0-port0 -> ../../ttyUSB6
lrwxrwxrwx. 1 root root 13 Dec  3 11:35 pci-0000:00:1d.0-usb-0:1.5:1.1-port0 -> ../../ttyUSB7
lrwxrwxrwx. 1 root root 13 Dec  3 11:35 pci-0000:00:1d.0-usb-0:1.5:1.2-port0 -> ../../ttyUSB8
==================

==================
[root@smsd etc]# cat gammu-smsdrc2
[gammu]
device = /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1.5:1.0-port0
connection = at
#synchronizetime = yes
use_locking = yes
#gammuloc = gammu.us
startinfo = no

[smsd]
service = MYSQL
#PIN = 1234
logfile = /var/log/smsdlog_2
debuglevel = 1
phoneid = 2
#runonreceive = /some/script
commtimeout = 30
sendtimeout = 30
#MaxRetries = 1
#LoopSleep = 1
#receivefrequency = 0
CheckSecurity = 0
CheckSignal = 1
CheckBattery = 0
StatusFrequency = 15
deliveryreport = log
deliveryreportdelay = 1200
#skipsmscnumber = +48602123456
#ResetFrequency = 120
#HardResetFrequency = 600
BackendRetries = 60

# Database backends congfiguration
user = smsd
password = <hiden>
pc = localhost
database = dbsms

# DBI configuration
# driver = native_mysql
# driverspath = /usr/lib/dbd/
# Database directory for sqlite
# dbdir = /var/lib/smsd

[sql]
insert_phone = INSERT INTO phones (IMEI, ID, Send, Receive, InsertIntoDB, TimeOut, `Signal`, `NetCode`, `NetName`) VALUES (%I, %P, %1, %2, NOW(), (NOW() + INTERVAL 10 SECOND) + 0, -1, %O, %M)
find_outbox_sms_id = SELECT ID, InsertIntoDB, SendingDateTime, SenderID FROM outbox WHERE SendingDateTime < NOW() AND SendingTimeOut < NOW() AND SendBefore >= CURTIME() AND SendAfter <= CURTIME() AND ( SenderID is NULL OR SenderID = '' OR SenderID = %P ) ORDER BY Priority DESC, InsertIntoDB ASC LIMIT %1
refresh_phone_status =  UPDATE phones SET TimeOut= (NOW() + INTERVAL 10 SECOND) + 0, `Signal` = %2 WHERE IMEI = %I
==================

==================
[root@smsd ~]# minicom -D /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1.5:1.0-port0


Welcome to minicom 2.6.2

OPTIONS: I18n 
Compiled on Jun 10 2014, 03:20:53.
Port /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1.5:1.0-port0, 11:40:32

Press CTRL-A Z for help on special keys

atz
OK
ati
Manufacturer: huawei
Model: E1552
Revision: 11.608.13.02.00
IMEI: 353143039708798
+GCAP: +CGSM,+DS,+ES

OK
==================

==================
[root@smsd ssh]# tail -f /var/log/smsdlog_2
Thu 2015/12/03 11:44:26 gammu-smsd[2371]: Going to 30 seconds sleep because of too much connection errors
Thu 2015/12/03 11:44:56 gammu-smsd[2371]: Starting phone communication...
Thu 2015/12/03 11:44:56 gammu-smsd[2371]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Thu 2015/12/03 11:44:56 gammu-smsd[2371]: Going to 30 seconds sleep because of too much connection errors
Thu 2015/12/03 11:45:26 gammu-smsd[2371]: Starting phone communication...
Thu 2015/12/03 11:45:26 gammu-smsd[2371]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Thu 2015/12/03 11:45:26 gammu-smsd[2371]: Going to 30 seconds sleep because of too much connection errors
Thu 2015/12/03 11:45:56 gammu-smsd[2371]: Starting phone communication...
Thu 2015/12/03 11:45:56 gammu-smsd[2371]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Thu 2015/12/03 11:45:56 gammu-smsd[2371]: Going to 30 seconds sleep because of too much connection errors
==================

**Comment by nijel** [comment]
Can you please include full debug log (that also includes Gammu communication with phone)? See http://wammu.eu/support/bugs/
