### ISSUE TITLE
ZTE MF190 identify issue

### ISSUE THREAD

**Issue by geethupendra** [gammu/gammu#151]
Hello Team,

I'm very new to Ubuntu and linux, recently try to make a SMS gateway, (I just refer the video doc from [http://srijit.com/installing-playsms-with-gammu-in-ubuntu-server-part-3-gammu-installation-configuration-verification/])

used same Hardware (ZTE MF190, ubuntu server 15.10 - Gnome) 

Configure Files --> /etc/gammurc
[gammu]
port = /dev/ttyUSB1
connection = at9600
logfile = /var/log/gammu/gammu.log
logformat = textall

[smsd]
Service = files
InboxPath = /var/spool/gammu/inbox/
OutboxPath = /var/spool/gammu/outbox/
SentSMSPath = /var/spool/gammu/sent/
ErrorSMSPath = /var/spool/gammu/error/
InboxFormat = unicode
OutboxFormat = unicode
TransmitFormat = auto
debugLevel = 1
LogFile = /var/log/gammu/smsd.log
DeliveryReport = sms
DeliveryReportDelay = 7200
CheckSecurity = 0

------------------------------------------------------------
configure file --> /etc/wvdial.conf

[Dialer Defaults]
Init1 = ATZ
Init2 = ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
Modem Type = Analog Modem
; Phone = <Target Phone Number>
ISDN = 0
; Password = <Your Password>
New PPPD = yes
; Username = <Your Login Name>
Modem = /dev/ttyUSB1
Baud = 9600

---------------------------------------------
configure file --> wvdial.conf

root@gdsms:~# wvdialconf
Editing `/etc/wvdial.conf'.

Scanning your serial ports for a modem.

Modem Port Scan<*1>: S0   S1   S2   S3   S4   S5   S6   S7   
Modem Port Scan<*1>: S8   S9   S10  S11  S12  S13  S14  S15  
Modem Port Scan<*1>: S16  S17  S18  S19  S20  S21  S22  S23  
Modem Port Scan<*1>: S24  S25  S26  S27  S28  S29  S30  S31  
ttyUSB0<*1>: ATQ0 V1 E1 -- failed with 2400 baud, next try: 9600 baud
ttyUSB0<*1>: ATQ0 V1 E1 -- failed with 9600 baud, next try: 9600 baud
ttyUSB0<*1>: ATQ0 V1 E1 -- and failed too at 115200, giving up.
ttyUSB1<*1>: ATQ0 V1 E1 -- failed with 2400 baud, next try: 9600 baud
ttyUSB1<*1>: ATQ0 V1 E1 -- OK
ttyUSB1<*1>: ATQ0 V1 E1 Z -- OK
ttyUSB1<*1>: ATQ0 V1 E1 S0=0 -- OK
ttyUSB1<*1>: ATQ0 V1 E1 S0=0 &C1 -- OK
ttyUSB1<*1>: ATQ0 V1 E1 S0=0 &C1 &D2 -- OK
ttyUSB1<*1>: ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0 -- OK
ttyUSB1<*1>: Modem Identifier: ATI -- Manufacturer: ZTE CORPORATION
ttyUSB1<*1>: Max speed is 9600; that should be safe.
ttyUSB1<*1>: ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0 -- OK
ttyUSB2<*1>: ATQ0 V1 E1 -- OK
ttyUSB2<*1>: ATQ0 V1 E1 Z -- OK
ttyUSB2<*1>: ATQ0 V1 E1 S0=0 -- OK
ttyUSB2<*1>: ATQ0 V1 E1 S0=0 &C1 -- OK
ttyUSB2<*1>: ATQ0 V1 E1 S0=0 &C1 &D2 -- OK
ttyUSB2<*1>: ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0 -- OK
ttyUSB2<*1>: Modem Identifier: ATI -- Manufacturer: ZTE CORPORATION
ttyUSB2<*1>: Speed 9600: AT -- OK
ttyUSB2<*1>: Max speed is 9600; that should be safe.
ttyUSB2<*1>: ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0 -- OK

Found a modem on /dev/ttyUSB1.
Modem configuration written to /etc/wvdial.conf.
ttyUSB1<Info>: Speed 9600; init "ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0"
ttyUSB2<Info>: Speed 9600; init "ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0"
root@gdsms:~# 

---------------------------------------------------------
ISSUE IS --> gammu identify
No response in specified timeout. Probably phone not connected.

I just try to install modem manager GUI, and it's detecting and can sent the SMS

PLEASE BE KINDLY ANYONE CAN GIVE A SUPPORT ME TO SORT THIS....

--Attachment--
![screenshot from 2015-11-25 09-40-15](https://cloud.githubusercontent.com/assets/2115099/11388140/bde5d1ee-9358-11e5-9c22-2b58c12cfdeb.png)

**Comment by nijel** [comment]
Can you please provide Gammu log?

**Comment by geethupendra** [comment]
I found the issue,.. After 4days testing ..:)

after installing OS and configure the LAMP, then did go tasksel and install GNONE.. (on this process all PHP and some files updating..)
That's why modem was not detected,.
So i completely follow that process, it's identify the modem and send the sms NOW..

Thanks for your support nijel, anyhow i'll send the Gammu Log with in few minutes..

**Comment by geethupendra** [comment]
tail -f /var/log/gammu/smsd.log

Wed 2015/11/25 22:17:19 gammu-smsd[1510]: Going to 30 seconds sleep because of too much connection errors
Wed 2015/11/25 22:17:49 gammu-smsd[1510]: Starting phone communication...
Wed 2015/11/25 22:17:49 gammu-smsd[1510]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Wed 2015/11/25 22:17:49 gammu-smsd[1510]: Going to 30 seconds sleep because of too much connection errors
Wed 2015/11/25 22:18:19 gammu-smsd[1510]: Starting phone communication...
Wed 2015/11/25 22:18:19 gammu-smsd[1510]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Wed 2015/11/25 22:18:19 gammu-smsd[1510]: Going to 30 seconds sleep because of too much connection errors
Wed 2015/11/25 22:18:49 gammu-smsd[1510]: Starting phone communication...
Wed 2015/11/25 22:18:49 gammu-smsd[1510]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Wed 2015/11/25 22:18:49 gammu-smsd[1510]: Going to 30 seconds sleep because of too much connection errors
Wed 2015/11/25 22:19:19 gammu-smsd[1510]: Starting phone communication...
Wed 2015/11/25 22:19:19 gammu-smsd[1510]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Wed 2015/11/25 22:19:19 gammu-smsd[1510]: Going to 30 seconds sleep because of too much connection errors

Hello Nijel,
please find the gammu log

**Comment by nijel** [comment]
Didn't name of your port change?

**Comment by JHGitty** [comment]
I have a ``ZTE MF190`` at it works fine.

```ini
[gammu]
port = /dev/ttyUSB1
connection = at19200
```

```sh
$ sudo gammu identify
Device               : /dev/ttyUSB1
Manufacturer         : ZTE CORPORATION
Model                : unknown (MF190)
Firmware             : (removed)
IMEI                 : (removed)
SIM IMSI             : (removed)
```

**Comment by bagustilas** [comment]
i have same problem, can you help me , i use ubuntu 16.04 and Gammu-detect version 1.38.1
