### ISSUE TITLE
Installing with --prefix

### ISSUE THREAD

**Issue by jmssil** [gammu/gammu#152]
If we use ./configure --prefix with a local destination, in this step, it tries to write on the system:

./build-configure/contrib/cmake_install.cmake line 118

In my opinion it should not try to write on the system directories with a local install.

I commented that line so that install could reach the end.

**Comment by nijel** [comment]
The bash completion is installed to the location where it will be found, if you don't want it, disable installation with --without-completion....

**Comment by jmssil** [comment]
Thanks.

Will bash completion work if gammu is installed to a custom --prefix?

**Comment by nijel** [comment]
It should work regardless prefix.
