### ISSUE TITLE
Compiling and building question 

### ISSUE THREAD

**Issue by sergiomb2** [gammu/gammu#153]
Hello when I was compiling wammu it appears this message [1] that make me think :
Should we recompile python-gammu after update gammu to 1.36.6 ? 
and btw should we recompile wammu after update python-gammu ? 

Thanks.

[1] Checking for python-gammu ... found version 2.4 using Gammu 1.35.0 ... OK

**Comment by nijel** [comment]
It's not really needed in most cases, the API is stable. python-gammu can tell you [both compile time and run time versions](http://wammu.eu/docs/manual/python/gammu.html#gammu.Version):

```python
import gammu
print gammu.Versions()
```

But what you most likely did is to install new Gammu version to /usr/local/lib and previous version is in /usr/lib, which usually has priority in ld configuration, so python-gammu uses that one.

**Comment by sergiomb2** [comment]
Hi,
Did API change between 1.35.0 and 1.36.6 ?

I have only one gammu installed in system and : 

$ipython
import gammu
gammu.Version()
Out[5]: ('1.36.6', '2.4', '1.35.0')

Just in case, I will rebuild python-gammu and after wammu , so I guarantee the best optimization , but in future, on next releases of gammu, I slow down the rebuilds .

You are invited to test it on Fedora 21, 22 or 23 ;) [1]

Thanks.

[1] dnf  --enablerepo=updates-testing install \*ammu\*

**Comment by nijel** [comment]
No the API didn't change.

**Comment by sergiomb2** [comment]
OK rebuilds canceled :) 
Many thanks
