### ISSUE TITLE
gammu-smsd kills modem

### ISSUE THREAD

**Issue by Jancs-E** [gammu/gammu#155]
Hi!
I have such problem:
everything is ok after gammu-smsd is started, but when the first sms is being either sent of received, gammu-smsd process starts kind of dance of the death which kills modems in a minute.
All dies at "Getting SIM SMS status" (died on reception, see around end of the log file)

May be some settings are wrong?
[gammu-smsdrc.txt](https://github.com/gammu/gammu/files/46597/gammu-smsdrc.txt)

The only solution to get it back is at least USB device reset (even not the device but whole USB hub).

Modem: 05c6:6000 Qualcomm, Inc. Siemens SG75; RaspberryPI/Slackware 14.1/kernel 4.1.12/gammu 1.36.6
Janis
[gammu-smsd.log.txt](https://github.com/gammu/gammu/files/46596/gammu-smsd.log.txt)

**Comment by Jancs-E** [comment]
The situation is not much better with 1.36.7 (see log involving few successful sends and ruining reception at the end)
[gammu-smsd.log-send-rec.txt](https://github.com/gammu/gammu/files/46633/gammu-smsd.log-send-rec.txt)

**Comment by Jancs-E** [comment]
Also I do not understand how could I influence the device polling frequency - device now is polled every second for new sms-es. For me it could suffice once in a 5 secs or even less frequent.

**Comment by nijel** [comment]
You can control polling frequency by [CommTimeout](http://wammu.eu/docs/manual/smsd/config.html#option-CommTimeout) and [ReceiveFrequency](http://wammu.eu/docs/manual/smsd/config.html#option-ReceiveFrequency).

As for the error, I don't see anything obvious, can you retry with DebugLevel = 255 to log more detailed what is going on?

**Comment by Jancs-E** [comment]
It seems that explicitly setting CommTimeout=30, ReceiveFrequency=15 and LoopSleep=5 stabilizes the modem at least for reception as it worked through the night without hanging or any other adverse effects.
Ill turn them off and re-rerun with debug level 255 during the evening.

**Comment by Jancs-E** [comment]
Yes, it seems without such restrictions either modem or USB port on RasPi/USB HUB becomes overwhelmed with communication and drops dead. Now even the sending of sms does not kill the modem.

**Comment by Jancs-E** [comment]
I have no longer lack to kill the modem - during the last hour I am turning off one by one all options limiting the activity. Despite this the modem works stable even without LoopSleep, CommTimeout and ReceiveFrequency. 
System is not rebooted and not altered. Total mystery.
