### ISSUE TITLE
Sending messages out of order

### ISSUE THREAD

**Issue by godson** [gammu/gammu#162]
When using MySql there is a possibility to send messages to the queue, the same as when sending files (change the letter in the file name)?

**Comment by nijel** [comment]
You can insert messages to the queue using [gammu-smsd-inject](http://wammu.eu/docs/manual/smsd/inject.html) or [manually](http://wammu.eu/docs/manual/smsd/tables.html#injecting-a-message-using-sql).

**Comment by godson** [comment]
You did not understand me ... If you are using the file system, it is possible to send SMS directly without looking at the big queue of messages without going through all ... ... Is there such a possibility when using the database?

**Comment by nijel** [comment]
Set ``InsertIntoDB`` to past, queue is ordered by this field, also see http://wammu.eu/docs/manual/smsd/tables.html#outbox
