### ISSUE TITLE
smsd exits on HUP signal

### ISSUE THREAD

**Issue by pdorn87** [gammu/gammu#163]
Command:

start-stop-daemon --stop --signal HUP --quiet --pidfile \
  /var/run/$NAME.pid --exec $DAEMON

Result:
Thu 2015/12/10 09:47:56 gammu-smsd[25387]: Terminating communication...
Thu 2015/12/10 09:47:56 gammu-smsd[25387]: gammu: [Terminating]
Thu 2015/12/10 09:47:56 gammu-smsd[25387]: gammu: [Closing]
Thu 2015/12/10 09:47:56 gammu-smsd[25387]: Disconnecting from SQL database.

Expected result:
At least re-opening logfiles, because after running logrotate on the logfile, the logfile is not created again + the old file is kept open in memory.

**Comment by nijel** [comment]
What version is that? What operating system? Support for reloading is there since 1.22.91, but maybe it just doesn't build properly on your system...

**Comment by nijel** [comment]
See also documentation: http://wammu.eu/docs/manual/smsd/smsd.html#signals
