### ISSUE TITLE
[Database] When was a SMS sent?

### ISSUE THREAD

**Issue by JHGitty** [gammu/gammu#164]
The sql database contains the table ``inbox`` for incoming SMS.
Where can I find the information about the sending date/time of the SMS?
I've only found ``ReceivingDateTime``.

**Comment by nijel** [comment]
Unfortunately this information is not there in most cases...

**Comment by JHGitty** [comment]
Does the GSM standard (or whatever) contain any information about the date/time when an SMS was sent? If yes it should be added to the database and be empty if no information is known.

**Comment by nijel** [comment]
No it does not. The SMSC time can be optionally there, but in reality I haven't seen it set anywhere (it would IMHO reduce space for content of the message).

**Comment by JHGitty** [comment]
I would prefer to get all information which are transfered from the SMSC. The database only contains the most widely used fields. Could you provide some information how to easily receive SMS with Gammu which contains all information? I'' create my own script and database for my application.

**Comment by nijel** [comment]
It contains pretty much all information which is available. What is not there is numbering plan (whether the number is text or numeric), message flags (reject duplicates or replace message, currently AFAIK not supported by any device) and message reference. Honestly I don't see use case for these...

If you want to process raw messages, use [files backed](http://wammu.eu/docs/manual/smsd/files.html) with [InboxFormat = detail](http://wammu.eu/docs/manual/smsd/config.html#option-InboxFormat).

**Comment by JHGitty** [comment]
1. Numbering plan
I don't know any reason why we should need this information. Everybody can easily see and understand if a number use alpha characters or just numbers.

2. Message flags
Do you have more information about this? Are you sure that the devices out there are not supporting this feature? I don't feel good if a feature is in the specification but not well implemented.

3. Message Reference
Do you mean a message reference id to have a reference to understand which message has exactly be sent? I think this should be added to the database to easily have a reference - why not? Isn't it helpful for some commands to have this message reference?

**Comment by nijel** [comment]
Sorry, I was mistaken, the message reference is available only when sending message and it's already stored in the sent items table (as TPMR).

So honestly I don't really see any useful information which could be added to the inbox table.
