### ISSUE TITLE
Modem does not receive SMS

### ISSUE THREAD

**Issue by Jancs-E** [gammu/gammu#165]
Hi!
How could I debug such problem? 
I have two cheap Chinese modems representing themselves as Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem. Working well if used for 4G, able to send SMSes, but ARE NOT able to receive them!
If the sim-card contains some messages, gammu-smsd is receiving them, but not the new ones.
Gammu 1.36.8/kernel 3.18.24. Modem is plugged into desktop computer's USB.

**Comment by Jancs-E** [comment]
May be not enough power?

**Comment by nijel** [comment]
I've tried to improve initialization for your modem, can you try building version from git?

**Comment by Jancs-E** [comment]
I pulled master.zip and with it modem not initializes at all.
gammu-detect:
Phone on USB serial port Qualcomm__Incorporated Qualcomm_CDMA_Technologies_MSM
[gammu-smsd.log.txt](https://github.com/gammu/gammu/files/63054/gammu-smsd.log.txt)

**Comment by nijel** [comment]
Okay, I've reverted that. Firmware update is definitely good idea....

**Comment by Jancs-E** [comment]
Unfortunately, the problems is with gammu - on windows evrth works (interface suspiciously similar looking like wammu), including reception of SMS.
What info can i provide to you to help correct this?

**Comment by Jancs-E** [comment]
Any ideas?

**Comment by Jancs-E** [comment]
May be it has anything to do with such:
https://github.com/faucamp/python-gsmmodem/issues/60 ?

**Comment by nijel** [comment]
Gammu chooses the best what phone reports to support here. Without the log it's hard to diagnose...

**Comment by Jancs-E** [comment]
Ok, here come the log.
Strangest thing is the the log does not contain anu reference to the number I tried to send
[gammu-smsd.log.txt](https://github.com/gammu/gammu/files/117274/gammu-smsd.log.txt)
s SMS from.

**Comment by Jancs-E** [comment]
You are hero!!!! Now everything works!

**Comment by nijel** [comment]
Thanks for feedback!

**Comment by goran-mahovlic** [comment]
Hi, 
even with the newest build im still having problem with receiving SMS.
It is the same problem if I receive SMS on mobile and then put it in USB modem then it is detected ans new SMS, and if I just send message when USB modem is connected it does not appear in received messages.
Here is small log.
[log-gammu.txt](https://github.com/gammu/gammu/files/614735/log-gammu.txt)

**Comment by nijel** [comment]
@goran-mahovlic According to the log you're using 1.33.0 which is definitely not the latest version, try upgrading.

**Comment by goran-mahovlic** [comment]
Ok I will check. It compiled successfully but maybe I did something wrong. 
tnx 
I will report back

**Comment by goran-mahovlic** [comment]
Hi, 
You were right
sudo make install 
does not update /etc/init.d/gammu-smsd to new version
I have now copy and run new version and receiving is working
Tnx
