### ISSUE TITLE
[Database] All tables should have an ID (primary key)

### ISSUE THREAD

**Issue by JHGitty** [gammu/gammu#167]
All tables should have an ``id`` field. This field should be the primary key and set to ``auto_increment``.

Reason 1: It is much easier and secure to work with an id.

Reason 2: Some applications have issues if a table has no primary key. For example Doctrine 2:
```
Table 'daemons' has no primary key. Doctrine does not support reverse engineering from tables that don't have a primary key.  
```

**Comment by nijel** [comment]
Hmm, I don't think this table is used at all, so it might be better idea to drop it completely. Leaving this open for now if somebody else can see it being used...

**Comment by JHGitty** [comment]
@nijel https://github.com/gammu/gammu/search?utf8=%E2%9C%93&q=daemons

**Comment by nijel** [comment]
There is just CREATE/DROP table and documentation, so nothing really important...

**Comment by JHGitty** [comment]
Same thing for table ``gammu``:
Table gammu has no primary key. Doctrine does not support reverse engineering from tables that don't have a primary key.

``gammu`` and ``daemons`` are the only tables which have this issue.
