### ISSUE TITLE
No delivery report with ZTE MF190

### ISSUE THREAD

**Issue by JHGitty** [gammu/gammu#169]
I have a ``ZTE MF190`` but I don't know why I never get a delivery report.

1. Yes, I use the ``-report`` parameter to request a delivery report.
2. Yes, I set ``deliveryreport`` to ``log`` to see any delivery report in my log file. The log file confirms that this setting is active.
3. Yes, I tried a lot of times to sent SMS to other numbers and to my own number.
4. Yes, all successfully sent SMS are on status ``SendingOk``.

I don't get any delivery report. There is no entry in the log file that any delivery report is received.

Do you have any idea why this happens?

```sh
$ sudo gammu identify
Device               : /dev/ttyUSB1
Manufacturer         : ZTE CORPORATION
Model                : unknown (MF190)
Firmware             : (removed)
IMEI                 : (removed)
SIM IMSI             : (removed)
```

```ini
[gammu]
port = /dev/ttyUSB1
connection = at19200

[smsd]
service = sql
driver = native_mysql
host = localhost
PIN = (removed)
LogFile = syslog
User = (removed)
Database = smsd
Password = (removed)
deliveryreport = log
deliveryreportdelay = 60
```

Send and receive SMS works fine. I just don't get any delivery report. My provider is O2 Germany.

**Comment by JHGitty** [comment]
@nijel Do you know anything about this? Is there any way to detect why there is no delivery report if I enable all debug features? If you like I'll send you full debug logs via email.

**Comment by nijel** [comment]
What version do you use? Is there something about delivery reports in the log? It might be rejected due to being too old (usually caused by wrong timezone information) or coming from different SMSC. Recent Gammu versions log all this, but previous versions did silently discard such delivery reports.

**Comment by JHGitty** [comment]
I cannot find anything about this in my log files :(

**Comment by nijel** [comment]
If you don't see any errors it's most likely working correctly :-).

Also see http://wammu.eu/docs/manual/faq/smsd.html#why-received-delivery-reports-are-not-matched-to-sent-messages
