### ISSUE TITLE
Init AT commands (disable cdrom mode)

### ISSUE THREAD

**Issue by JHGitty** [gammu/gammu#170]
I have a ``ZTE MF190``.

I need these init AT commands to disable cdrom mode and enable modem mode:
```
Init1 = AT+ZOPRT=5
Init2 = AT+ZCDRUN=8
```
(Source: https://wiki.archlinux.org/index.php/ZTE_MF110/MF190)

Is there any way to automatically do this with Gammu?

**Comment by JHGitty** [comment]
@nijel Could you add that another AT command will be executed once gammu is not used anymore or something like that? Maybe we should enable cdrom mode again after usage of modem mode?

Cdrom mode (need to disable for modem mode)
AT+ZCDRUN=8 disable
AT+ZCDRUN=9 enable

Stay online
AT+ZOPRT=5

**Comment by nijel** [comment]
I don't think it would make it anyway better. We should rather query original state and restore it on disconnect. But this is something Gammu doesn't do for any state it changes...

**Comment by JHGitty** [comment]
@nijel Okay :+1:

**Comment by matahr** [comment]
Please add ZTE MF627 has the same behavor

**Comment by nijel** [comment]
Done.
