### ISSUE TITLE
Opencellid API broken

### ISSUE THREAD

**Issue by henrik1g** [gammu/gammu#172]
gammu getlocation fails.

First the URL in misc.c needs to be changed from http://www.opencellid.org/cell/get? to http://opencellid.org/cell/get?

Second the opencellid api key needs to be whitelisted. See Error Msg below.
Maybe an exeption for the "contribution policy" for gammu is possible.

<err info="Your API key must be white listed in order to run this operation. This service is free of charge as long as your application contributes to the OpenCellID project. Should your application meet this requirement, please contact markus@opencellid.org for the authorisation of your API key.

For further details please visit:
http://wiki.opencellid.org/wiki/Commercial_users
http://wiki.opencellid.org/wiki/Request_whitelisting

You can alternatively download the entire database here:
http://opencellid.org/downloads/" code="4"/>

**Comment by nijel** [comment]
The code is from times they didn't require any of that. Obviously not much people use it as it's probably broken for few years now :-).
