### ISSUE TITLE
SQLite WAL gammu-smsd

### ISSUE THREAD

**Issue by chikatambun** [gammu/gammu#177]
$ sudo cat /etc/gammu-smsdrc
[gammu]
Device = /dev/ttyUSB0
connection = at115200

[smsd]
CommTimeout = 36
SendTimeout = 36
Service = sql
Driver = sqlite3
LogFile = /var/log/smsd.log
DBDir = /engineer
Database = pygammu.sqlite
HangupCalls = 1
CheckBattery = 0
CheckSecurity = 0
SynchronizeTime = 1
StartInfo = 0
DebugLevel = 2

$ cat /var/log/smsd.log
...
2016/01/22 10:44:59 python-gammu[3818]: mode: Send=1, Receive=1
2016/01/22 10:44:59 python-gammu[3818]: deliveryreport = no
2016/01/22 10:44:59 python-gammu[3818]: phoneid =
2016/01/22 10:44:59 python-gammu[3818]: Database structures version: 13, SMSD current version: 13
2016/01/22 10:44:59 python-gammu[3818]: Connected to Database sqlite3: pygammu.sqlite on localhost
2016/01/22 10:45:00 gammu-smsd[12141]: DBI error 5: 5: database is locked
2016/01/22 10:45:00 gammu-smsd[12141]: SQL failed: UPDATE outbox SET SendingTimeOut = datetime('now', '+60 seconds') WHERE ID = '3622' AND (SendingTimeOut < datetime('now') OR SendingTimeOut IS NULL)
2016/01/22 10:45:00 gammu-smsd[12141]: SQL failure: 5: database is locked
2016/01/22 10:45:00 gammu-smsd[12141]: SQL failed (timeout): UPDATE outbox SET SendingTimeOut = datetime('now', '+60 seconds') WHERE ID = '3622' AND (SendingTimeOut < datetime('now') OR SendingTimeOut IS NULL)
2016/01/22 10:45:00 gammu-smsd[12141]: reconnecting to database!
2016/01/22 10:45:00 gammu-smsd[12141]: Reconnecting after 1 seconds...
2016/01/22 10:45:00 python-gammu[3818]: Written message with ID 3638
2016/01/22 10:45:01 gammu-smsd[12141]: SMS sent on device: "/dev/ttyUSB0" status=0, reference=251
....

Is gammu-smsd enable mode PRAGMA WAL for SQLite? In order to the Error message "DBI error 5: 5: database is locked" can be minimalized
##

**Comment by nijel** [comment]
There is no support for that right now.

**Comment by nijel** [comment]
As this is persistent setting of the database, nothing prevents you from changing this outsite gammu using `PRAGMA journal_mode=WAL;`. I don't really see need to add special support for this inside gammu.
