### ISSUE TITLE
'gammu getussd'  gives blank reply

### ISSUE THREAD

**Issue by Docbroke** [gammu/gammu#178]
gammu getussd gives blank reply in recent version (1.36.8), I am using it on arch-linux

> gammu getussd *112*02#
Press Ctrl+C to break...
USSD received
Status               : No action needed
Service reply        : ""

After downgrading to gammu-1.36.6-1-x86_64.pkg.tar.xz on arch linux, it gets working again.

>gammu getussd *112*02#
Press Ctrl+C to break...
USSD received
Status               : No action needed
Service reply        : "On DATA Pack u have 4Gb 96Mb 906kb valid until 21/05/2016   upto time of data recharge done by u."

may be related to #179

**Comment by nijel** [comment]
It's definitely caused by #179.

**Comment by Docbroke** [comment]
modem is 
DELL DW5560 WWAN Mobile Broadband HSPA MiniPCI Express Card
