### ISSUE TITLE
Some accented characters not sent correctly, fr_FR locale

### ISSUE THREAD

**Issue by hcampan** [gammu/gammu#187]
Hi all

I have a problem with some accented characters that are not sent correctly in fr_FR locale. I suspect gammu is the problem as Mobile Partner app sends them fine.

### Platform :

* OSX 10.6.8
* Macmini1,1, 2006 ;-)

### Modem, `gammu --identify` :

* Device : /dev/tty.HUAWEIMobile-Pcui (also tried with tty.HUAWEIMobile-Modem)
* Manufacturer : Huawei
* Model : E1752 (E1752)
* Firmware : 11.126.13.00.00 (latest, from what I know)

### Gammu, `gammu --version` :

* [Gammu version 1.37.0]

## Example command :
  gammu sendsms TEXT [tel_number] -text "aäáàâãåăąæbcçćčdďđeéèêëěęfghiíìîïjklĺľłmnñńň"

## Result and comparison :

* aäáàâãåăąæbcçćčdďđeéèêëěęfghiíìîïjklĺľłmnñńň (original)
* aäaàaaåaaæbccccdddeéèeeeefghiiìiijkllllmnñnn (result)

It is really strange as some do work and some don't. Identical problems with upper case.

* AÄÁÀÂÃÅĂĄÆBCÇĆČDĎĐEÉÈÊËĚĘFGHIÍÌÎÏJKLĹĽŁMNÑŃŇ (original)
* AÄAAAAÅAAÆBCçCCDDDEÉEEEEEFGHIIIIIJKLLLLMNÑNN (result)

We can also see that lower case "ç" is _converted_ to "c".
**But** upper case "Ç" is _converted_ to lower case "ç". Really weird !

I've tried with :

* -textutf8
* -inputunicode
* prepending the command with `export LC_ALL=fr_FR.UTF-8`
* GammuCoding = utf8 in `gammurc`

› Same problem. And as I already mentioned, Mobile Partner does send all characters correctly.

Any ideas ?

Thanks in advance

Hubert

**Comment by nijel** [comment]
Not being able to encode some chars in GSM encoding is expected (you can use -unicode to change to Unicode encoding for messages). However handling of Ç indeed looks strange.

**Comment by nijel** [comment]
It might be also caused by national language shift tables, which are not supported by Gammu and some of them do have ç in place where Ç is in GSM standard. Where do you check the resulting chars?

**Comment by nijel** [comment]
PS: See https://en.wikipedia.org/wiki/GSM_03.38 for more info on the topic...

**Comment by hcampan** [comment]
I do check the resulting chars on my iPhone (and Macbook Pro), recipient of my test SMS. But again, it does properly work on the same sending computer, modem and receiver iPhone with Mobile Partner app.

As for shifting tables, I looked on the link you provided and French has no shifting table yet if I understood correctly.

And last, changing to -unicode would defeat the purpose of simplicity of my workflow, meaning one-liner command. But I'm not so good at bash, so maybe I oversee how to use -unicode without having to encode my original text message.

**Comment by nijel** [comment]
You do not have to encode it, -unicode is about encoding of sent message.

**Comment by hcampan** [comment]
Sorry, I mixed between -unicode of Gammu (which I didn't know about, missed it in doc) and binary format for the AT commands. I guessed I made too many tests.

So it **does** work with -unicode on the gammu command line.

Thanks Nijel
