### ISSUE TITLE
Problem with Multiparts and Unicode in gammu-smsd

### ISSUE THREAD

**Issue by Perwol** [gammu/gammu#19]
When I receive some long multipart text messages (Unicode) - the last part is not saved. I can't to install new version, I'm using Raspberry Pi.

For expample this text (2 of 3 parts i receive):

ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó ąśżźłó !

Logs:
Wed 2013/09/04 22:13:31 gammu-smsd[3998]: Starting phone communication...
Wed 2013/09/04 22:13:39 gammu-smsd[3998]: Inserting phone info
Wed 2013/09/04 22:14:07 gammu-smsd[3998]: Read 1 messages
Wed 2013/09/04 22:14:07 gammu-smsd[3998]: Multipart message 0x6C, 1 parts of 3
Wed 2013/09/04 22:14:07 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts
Wed 2013/09/04 22:14:08 gammu-smsd[3998]: Read 1 messages
Wed 2013/09/04 22:14:08 gammu-smsd[3998]: Multipart message 0x6C, 1 parts of 3
Wed 2013/09/04 22:14:08 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 1 seconds)
Wed 2013/09/04 22:14:09 gammu-smsd[3998]: Read 1 messages
Wed 2013/09/04 22:14:09 gammu-smsd[3998]: Multipart message 0x6C, 1 parts of 3
Wed 2013/09/04 22:14:09 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 2 seconds)
Wed 2013/09/04 22:14:10 gammu-smsd[3998]: Read 1 messages
Wed 2013/09/04 22:14:10 gammu-smsd[3998]: Multipart message 0x6C, 1 parts of 3
Wed 2013/09/04 22:14:10 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 3 seconds)
Wed 2013/09/04 22:14:12 gammu-smsd[3998]: Read 2 messages
Wed 2013/09/04 22:14:12 gammu-smsd[3998]: Multipart message 0x6C, 2 parts of 3
Wed 2013/09/04 22:14:12 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 5 seconds)
Wed 2013/09/04 22:14:14 gammu-smsd[3998]: Read 2 messages
Wed 2013/09/04 22:14:14 gammu-smsd[3998]: Multipart message 0x6C, 2 parts of 3
Wed 2013/09/04 22:14:14 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 7 seconds)
Wed 2013/09/04 22:14:15 gammu-smsd[3998]: Read 2 messages
Wed 2013/09/04 22:14:15 gammu-smsd[3998]: Multipart message 0x6C, 2 parts of 3
Wed 2013/09/04 22:14:15 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 8 seconds)
Wed 2013/09/04 22:14:16 gammu-smsd[3998]: Read 2 messages
Wed 2013/09/04 22:14:16 gammu-smsd[3998]: Multipart message 0x6C, 2 parts of 3
Wed 2013/09/04 22:14:16 gammu-smsd[3998]: Incomplete multipart message 0x6C, waiting for other parts (waited 9 seconds)
Wed 2013/09/04 22:14:18 gammu-smsd[3998]: Read 2 messages
Wed 2013/09/04 22:14:18 gammu-smsd[3998]: Multipart message 0x6C, 2 parts of 3
Wed 2013/09/04 22:14:18 gammu-smsd[3998]: Incomplete multipart message 0x6C, processing after timeout

Pleease help me

**Comment by nijel** [comment]
It actually looks like Gammu does not receive the last part at all. You can configure how long it waits for all parts: http://wammu.eu/docs/manual/smsd/config.html#option-MultipartTimeout

**Comment by dmkuznetsov** [comment]
I had same problem. By default Gammu wait 10 minutes for second part of message. Just wait ~10 minutes and all will be ok.

**Comment by Jancs-E** [comment]
Actually, it is not so easy - modem has a tendency to die with long timeout. It is not clear whether it has any role if multipart message contains multi-byte characters despite Inbox supporting UTF16.
In particular case case cheap kind of Qualcomm, Inc. Siemens SG75 modem is used and the dying of the modem expresses itself as disappearance of the ttyUSB0 after some time of bounces.
In my case helped cutting of the timeout to 20 sec (I had no patience to wait for 10 min . while observing error-like message in log)
It is clear that usb GSM modems are unreliable devices - my modem dies once in 24 h for yet unclear reasons, so I had to write an automatic restart script. Fortunately, I do not need to power-cycle it like some Huawey's.

**Comment by hadimajidi** [comment]
For mysql
thanks for your explanation. For me, it works well but it has an error when I try sending long SMS. for receiving there no problem. During sending it splits SMS to multiple parts and store the first part in the outbox table and the rest in the outbox_multipart. Afterward, it sends by gsm modem but the first part stores in the sentitems table. Is there any special setting that I should do in smsd file ?
