### ISSUE TITLE
Exception with Nokia 6320i during Fetch->Info

### ISSUE THREAD

**Issue by GyrosGeier** [gammu/gammu#190]
Hi,

just got this exception, it appears to be reproducible here.

   Simon

[wammu-crash-SK4xpC.txt](https://github.com/gammu/gammu/files/136462/wammu-crash-SK4xpC.txt)

**Comment by nijel** [comment]
This should be already fixed since https://github.com/gammu/wammu/commit/bc4cd2589ada4226c7fac037d5d366c05726e764
