### ISSUE TITLE
gammu-smsd: SMSC number is lost at random times since version 1.36.8

### ISSUE THREAD

**Issue by melones** [gammu/gammu#195]
Since Gammu-smsd 1.36.8 we started experiencing issues with error "No SMSC number given. Provide it manually or use the one configured in phone". In earlier versions of smsd _this was never an issue_ that no smsc was given. But since 1.36.8 we get this error in random times, from time to time. 

Hardware type: SIMCOM SIM900 modem. 

Below I attach sample log output that shows the problem. 

> Thu 2016/03/09 12:46:31 gammu-smsd[31299]: New message to send: 25023
Thu 2016/03/09 12:46:35 gammu-smsd[31299]: SMS sent on device: "/dev/ttyS1" status=0, reference=113
Thu 2016/03/09 12:46:35 gammu-smsd[31299]: Transmitted 25023 (part: 1) to xxxxxxxx
Thu 2016/03/09 12:46:37 gammu-smsd[31299]: SMS sent on device: "/dev/ttyS1" status=0, reference=114
Thu 2016/03/09 12:46:37 gammu-smsd[31299]: Transmitted 25023 (total: 2) to xxxxxxxx
Thu 2016/03/09 12:46:39 gammu-smsd[31299]: Message: somemessage
Thu 2016/03/09 12:46:39 gammu-smsd[31299]: Message: somemessage part 2
Thu 2016/03/09 12:46:39 gammu-smsd[31299]: New message to send: 24971
Thu 2016/03/09 12:46:59 gammu-smsd[31299]: SMS sent on device: "/dev/ttyS1" status=515, reference=-1
Thu 2016/03/09 12:46:59 gammu-smsd[31299]: Error getting send status of message: Unknown error. (UNKNOWN[27])
Thu 2016/03/09 12:48:01 gammu-smsd[31299]: Message: somemessage
Thu 2016/03/09 12:48:01 gammu-smsd[31299]: Message: somemessage part 2
Thu 2016/03/09 12:48:01 gammu-smsd[31299]: New message to send: 24978
Thu 2016/03/09 13:27:15 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25024
Thu 2016/03/09 13:28:17 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:28:17 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:28:17 gammu-smsd[31388]: New message to send: 25031
Thu 2016/03/09 13:28:17 gammu-smsd[31388]: Error sending SMS: No SMSC number given. Provide it manually or use the one configured in phone. (EMPTYSMSC[31])
Thu 2016/03/09 13:29:19 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:29:19 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25025
Thu 2016/03/09 13:30:21 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:30:21 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:30:21 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25026
Thu 2016/03/09 13:31:23 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:31:23 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:31:23 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25027
Thu 2016/03/09 13:32:25 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:32:25 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:32:25 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25028
Thu 2016/03/09 13:33:27 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:33:27 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:33:27 gammu-smsd[31388]: New message to send: 25032
Thu 2016/03/09 13:33:27 gammu-smsd[31388]: Error sending SMS: No SMSC number given. Provide it manually or use the one configured in phone. (EMPTYSMSC[31])
Thu 2016/03/09 13:34:29 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25029
Thu 2016/03/09 13:35:31 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:35:31 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:35:31 gammu-smsd[31388]: New message to send: 25033
Thu 2016/03/09 13:35:31 gammu-smsd[31388]: Error sending SMS: No SMSC number given. Provide it manually or use the one configured in phone. (EMPTYSMSC[31])
Thu 2016/03/09 13:36:33 gammu-smsd[31388]: Message: somemessage
Thu 2016/03/09 13:36:33 gammu-smsd[31388]: Message: somemessage part 2
Thu 2016/03/09 13:36:33 gammu-smsd[31388]: Moved to errorbox, reached MaxRetries: 25030

You can see that at the beginning gammu-smsd is working very fine and out of a sudden we get 515 error and after that SMSC number is lost. Sometimes 515 error doesn't happen, but just after start gammu-smsd has problem with SMSC. Other times this doesn't happen and gammu-smsd sends messages without error. So it is tricky to reproduce the error. However, maybe there were changes regarding getting SMSC in code and developer can catch it fast.

**Comment by nijel** [comment]
What version were you using before?

**Comment by melones** [comment]
The previous version we used was 1.35.0

**Comment by nijel** [comment]
Eh, that's quite big diff to investigate. Can you please try something in between as well?

**Comment by antonero** [comment]
We also have that problem, with latest 1.37.3!
I hope with 1.37.4 (I can't download at the moment for compiling errors) this problem have solved!
Thanks again for your efforts!

**Comment by nijel** [comment]
I don't think that 1.37.4 has any relevant fixes. Are you using SMSC from phone or set in the configuration file? Also more verbose log (see https://wammu.eu/support/bugs/) could reveal better what went wrong...

As for older .debs, you might find them on http://snapshot.debian.org/

**Comment by antonero** [comment]
Many thanks, now I'm trying with latest 1.37.4, SMSC are read from Onda MT191UP UsbPenDrive, I put also in daemon config file, but with no success... I'll read how to send verbose log, hear you soon!

**Comment by nijel** [comment]
Also how do you create outbox messages?

**Comment by antonero** [comment]
I use kalkun libraries to create SMS in outbox. I'm trying to create logs... I have 4 daemons running, is better for you to have 4 file separated? Also gammu.log is better to have many logs as usb keys? Where can I upload them?

**Comment by nijel** [comment]
There is enough to have log for just one daemon exposing this error. You can send them to me (michal@cihar.com) or upload here.

**Comment by nijel** [comment]
I've just spotted potential issue which could cause this - it's fixed in ab7c8f0, though I'm not sure if it will really completely fix your case.

**Comment by melones** [comment]
Thanks nijel. We'll try to test it if we encounter the issue again.

**Comment by antonero** [comment]
Hi Michal, I hope my log was usefull to solve that issue! As you can see randomly daemon freezes and I have to detach and attach again gsmmodem... can I solve this tedious situation?

**Comment by nijel** [comment]
Not really, I found this problem just by inspecting code. But I'll take deeper look at it later.

**Comment by antonero** [comment]
To test your latest commit, I have to wait next release? Or you can release 1.37.5 next days?

**Comment by nijel** [comment]
You can download git code or snapshot. I might release testing 1.37.90 soon, though there are still some changes I'd like to have there.

**Comment by antonero** [comment]
I'll wainting for latest build, is there a way to register as beta tester so I can download your "nightly" .deb as this 1.37.90 mentioned above?

**Comment by nijel** [comment]
There are currently no nightly binary builds. Once 1.37.90 is out, I might upload it to Debian experimental though.

**Comment by antonero** [comment]
It's perfect, so I can download from online repository or I need to add a new PPA?
