### ISSUE TITLE
smsd delay

### ISSUE THREAD

**Issue by Armagetron** [gammu/gammu#196]
Hi everyone,

I have the following setup: Raspberry 2 with smsd, MySQL backend and an Huawei surfstick. My application also runs on the Pi and inserts about 15 SMS into the service when a certain event is triggered.

Looking into the database I noticed that between inserting the SMS and sending the first one about 20s pass while all other SMS are sent with a gap of 1-3s each.

Is there a way to reduce the time between inserting the SMS and sending the first one?

**Comment by nijel** [comment]
You can configure how often does SMSD check for both incoming and outgoing messages, see http://wammu.eu/docs/manual/smsd/config.html#option-CommTimeout

**Comment by Armagetron** [comment]
Great. Does exactly what I needed. Thanks!
