### ISSUE TITLE
Crash when USB device is reset

### ISSUE THREAD

**Issue by daladim** [gammu/gammu#198]
Hi

I have noticed that when UMTSKeeper resets the USB dongle (to recover from some errors), it leaves it in an state which is unexpected by gammu-smsd, and finally prevents gammu-smsd from handling further SMS.
Is the problem in UMTSKeeper? In Gammu? In Both? Can it be fixed?

**My setup:**
Raspberry Pi, Raspbian 7
Huawei E303 3G USB Dongle (but it probably works with every other USB dongle)
UMTSKeeper 2.07
Gammu-smsd version 1.37.1

**Steps to reproduce:**
Reset the device with the ResetUSB function (or run the following Python snippet, taken from UMTSKeeper code, as root)
```
#! /usr/bin/env python
import subprocess

def PrintMessage(msg):
  print msg

# ResetUSB - to replace resetusb.c by a Python function. This resets the USB host port.
def ResetUSB():
  #get USB bus and device numbers of modem. Replace 'grep HSDPA' with anything that is able to detect your device
  output = subprocess.Popen('lsusb | grep HSDPA', shell=True, stdout=subprocess.PIPE).communicate()[0]
  
  if output != '':
    busNr = output[4:7]
    devNr = output[15:18]
    
    PrintMessage('Trying to reset USB device %s (Bus %s, Device %s)...' % ('HSDPA', busNr, devNr))
    #~ errorCode = subprocess.call(usbResetProg + ' /dev/bus/usb/' + busNr + '/' + devNr, shell=True)
    
    #USB reset IOCtl opcode taken from http://stackoverflow.com/questions/14626395
    from fcntl import ioctl
    #define USBDEVFS_RESET  _IO('U', 20)
    USBDEVFS_RESET = ord('U') << (4*2) | 20
    
    fn = '/dev/bus/usb/%s/%s' % (busNr, devNr)
    statusCode = 0
    
    try:
      fd = open(fn, 'wb')
    except Exception, err:
      PrintMessage('Error while trying to open device file %s for writing: "%s"' % (fn, err))
      return(err)
  
    try:
      #call USB reset IOCtl function
      statusCode = ioctl(fd, USBDEVFS_RESET, 0)
    except Exception, err:
      PrintMessage('Error with USB device reset IOCtl call: "%s"' % (err,))
      return(err)
    
    PrintMessage('Device reset returned status code %u%s. Will retry to connect.' % (statusCode, (' (success)' if statusCode == 0 else '')))
    
  else:
    PrintMessage('Device %s not found for reset (perhaps modeswitch is not yet done).' % conf['deviceName'])
  
#end ResetUSB

print "will reset"
ResetUSB()
print "done."
```

**Expected result:**
SMSes keep being usable

**Actual result:**
gammu-smsd is unable to handle SMSes until the next reboot
Its log file reads multiple:
```
Wed 2016/03/16 22:37:09 gammu-smsd[2801]: Starting phone communication...
Wed 2016/03/16 22:37:09 gammu-smsd[2801]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Wed 2016/03/16 22:37:09 gammu-smsd[2801]: Going to 30 seconds sleep because of too much connection errors
Wed 2016/03/16 22:37:39 gammu-smsd[2801]: Starting phone communication...
Wed 2016/03/16 22:37:39 gammu-smsd[2801]: Error at init connection: Error opening device, it doesn't exist. (DEVICENOTEXIST[4])
Wed 2016/03/16 22:37:39 gammu-smsd[2801]: Going to 30 seconds sleep because of too much connection errors
[...on and on until the computer reboots...]
```

**Comment by nijel** [comment]
Probably the device gets different name after reset, you should set [persistent names](http://wammu.eu/docs/manual/faq/general.html#device-name-always-changes-on-linux-how-to-solve-that).

**Comment by daladim** [comment]
I *think* I saw that the device name remains the same. I'll check this asap (not within one week though).

**Comment by memento** [comment]
@daladim  : Hi ! Did the persistent names solution work for you ?
I have the same problem (Raspberry Pi 2 + Raspbian Wheezy, HUAWEI E220 3G HSDPA USB MODEM 7.2Mbps wireless network card)

**Comment by daladim** [comment]
Hi,
I haven't had time to try it yet... (I actually left my raspberry pi at my parents'. It's a remote location so I'll make more thorough experiments when I visit them. I can access it via SSH, but I don't want to risk killing the connection as I currently have no physical access to reboot it if needed).

I have made a very dirty workaround (that regularly polls the log and reboot the whole raspi in case this error is encountered). I've just posted it on my account: https://github.com/daladim/gammuResetUSBWorkaround

It should be better for both of us to spend time to fix this issue rather than using my workaround, but if you want a quick-and-dirty solution, here you go :)

**Comment by daladim** [comment]
Many thanks @nijel , as you can see here, names change after a reset
```
$ ls -la /dev/serial/by-id/
lrwxrwxrwx 1 root root  13 Jan  1  1970 usb-HUAWEI_HUAWEI_Mobile-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root  13 Jan  1  1970 usb-HUAWEI_HUAWEI_Mobile-if01-port0 -> ../../ttyUSB1
lrwxrwxrwx 1 root root  13 Jan  1  1970 usb-HUAWEI_HUAWEI_Mobile-if02-port0 -> ../../ttyUSB2

$ sudo ./reset.py
started
Trying to reset USB device HSDPA (Bus 001, Device 006)...
Device reset returned status code 0 (success). Will retry to connect.
done.

$ ls -la /dev/serial/by-id/
lrwxrwxrwx 1 root root  13 Jul 13 00:35 usb-HUAWEI_HUAWEI_Mobile-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root  13 Jul 13 00:35 usb-HUAWEI_HUAWEI_Mobile-if01-port0 -> ../../ttyUSB1
lrwxrwxrwx 1 root root  13 Jul 13 00:35 usb-HUAWEI_HUAWEI_Mobile-if02-port0 -> ../../ttyUSB3
```

I am now using persistent IDs (`/dev/serial/by-id/usb-HUAWEI_HUAWEI_Mobile-if02-port0` instead of `/dev/ttyUSB2`), and it seems to pass my quick checks.
After I force a reset, instead of hitting `DEVICENOTEXIST`, gammu now hits some `Terminating communication: Entry is empty. (EMPTY[22])` issues, but then it resets the device (again) and is able to send/receive SMSes again. Even UMTSkeeper succeeds in recovering from this forced reset without tampering with gammu!
I'll post again if I notice other errors in a few days (especially, if some UMTSkeeper-related errors arise), but it looks very promising.

Many thanks for your support! I think you can close the topic in a few weeks if I don't keep in touch (no news will be good news then) :-)
