### ISSUE TITLE
Delay beetween sms or scheduled sending?

### ISSUE THREAD

**Issue by yahuarkuntur** [gammu/gammu#199]
Hello,

I am wondering if there is a way to configure a delay beetween sending sms with gammu. The use case would be, for example: send the sms 5 or 10 seconds from each other. 
I have tried queueing the sms in the mysql backend with a 5 seconds delay, but it seems gammu sends que queued messages as fast as it can, with a small 2-3 seconds difference.

I have also noticed that in the mysql backend, in the outbox table, there is a "SendAfter" column... is this a hidden implementation to schedule sms sending? or is this a future feature?

Any of these implementations or features would be of a lot of help for many use cases.

Best regards,

**Comment by Maraumax** [comment]
Hello,

In [documentation](http://fr.wammu.eu/docs/manual/smsd/tables.html?highlight=tables#outbox) its writed:
> Send message after specified time, can be used to limit messages from being sent in night. Default value is 00:00:00

You can also look [default query](http://fr.wammu.eu/docs/manual/smsd/sql.html#option-find_outbox_sms_id).

So yes i think you can use this option :+1:

**Comment by yahuarkuntur** [comment]
@Maraumax how can I specify this parameter through gammu-smsd-inject o maybe using python-gammu?

Thanks in advance!

**Comment by Maraumax** [comment]
@yahuarkuntur You can use directly mysql command:
> mysql --host=localhost --user=gammu --password=pw smsd << EOF
INSERT INTO outbox (
   DestinationNumber,
   TextDecoded,
   CreatorID,
   SendAfter
) VALUES (
   '000000',
   'Welcome',
   'inject',
   '10:00:00'
);
EOF

**Comment by nijel** [comment]
Just to clarify: the API doesn't support this feature, so it's only possible to do it at database level.

**Comment by yahuarkuntur** [comment]
@nijel Thanks for the clarification and @Maraumax thanks for the code snippet. I will try to use the feature at database level until this is supported in the gammu api.

Cheers!

**Comment by yahuarkuntur** [comment]
Hi again,

I have tried inserting my messages directly into the outbox table, but this approach does not satisfy my use case.

The reason is that the delay I need is small (say 5-10 seconds) beetween messages, and If I queue/insert them with the SendAfter value I need, there is a small window of time beetween gammu grabbing the first message and processing the remaining messages, and my required delay does not work since the SendAfter datetime is always past the current datetime.

I hope my usecase and problem is more clear. I will gladly offer a bounty if this "delay beetween messages"  can be implemented in the gammu worker/core/api.

Cheers!

**Comment by nijel** [comment]
You can configure how often does SMSD check for both incoming and outgoing messages, that should reduce latency, see http://wammu.eu/docs/manual/smsd/config.html#option-CommTimeout

**Comment by yahuarkuntur** [comment]
It would be the best to have a similar configuration option for smsd like: 
`SendDelay`: How many seconds should SMSD wait before sending a message.

Cheers!

**Comment by nijel** [comment]
How it should be different from ``CommTimeout``? (Besides not confusing name)

**Comment by yahuarkuntur** [comment]
@nijel for example when the outbox queue is always full and we need for at least 10 seconds beetween every sent message. 

If only the name is confusing we could pick another one :)

**Comment by nijel** [comment]
How about using ``LoopSleep`` to set this delay?

**Comment by yahuarkuntur** [comment]
I assume as the docs says: "...before checking for some activity." it will affect not only sending but receiving as well? Would love to have it as a separate configuration parameter.

**Comment by nijel** [comment]
It does influence both - it's in the main loop, see http://wammu.eu/docs/manual/smsd/overview.html#smsd-operation

**Comment by yahuarkuntur** [comment]
So it will delay the entire loop! :(

In the next days I will play a bit more with the main loop options.

@nijel Thanks a lot for the pointers :)
