### ISSUE TITLE
question: correct way to decode MMS Indication message

### ISSUE THREAD

**Issue by melones** [gammu/gammu#200]
I use smsd with database backend, and I'd like to make things clear regarding receiving  MMS messages. I hope this can help not only me, but also anyone searching help with the topic.

When a MMS message is received by SMSD a database entry is created in Inbox table. The database entry  contains binary SMS, so called "MMS Indication message". The SMS binary content is in Text column of the table. The binary SMS contains basic information about MMS (sender number, link to download MMS, type, etc). I searched a lot, but I cannot find the answer to the essential question: how is the binary SMS encoded and how to decode it? This is not a standard PDU (PDU decoder https://wammu.eu/tools/pdu-decode/ won't recognize it). Can you give me a hint in what standard is the received MMS Indication message and can we decode it?

Thanks in advance

**Comment by nijel** [comment]
It's standard PDU, the web PDU decoder expects whole message, while the database contains only the payload without SMS headers. You can use GSM_DecodeMultiPartSMS for decoding the message.

Alternatively you can use RunOnReceive as it already gets the information from MMS parsed in the environment: http://wammu.eu/docs/manual/smsd/run.html#per-part-variables

**Comment by melones** [comment]
That answers my question. Issue can be closed. Thank you!
