### ISSUE TITLE
Please add support for ID 12d1:1805 Huawei U2800A

### ISSUE THREAD

**Issue by agron2017** [gammu/gammu#203]
Please either add support for this USB phone
ID 12d1:1805 Huawei Technologies Co., Ltd. AT&T Go Phone U2800A phone

or advise how to add support for this phone.

Thanks,
//Agron

**Comment by nijel** [comment]
Have you tried to use it? The basic features should work out of the box, though it might need some tweaking (as usual with Huawei devices).

**Comment by agron2017** [comment]
Yes i tried to use it, but it can't find message store. So it never sees the messages.

**Comment by nijel** [comment]
Please include debug log from the failed operation, see https://wammu.eu/support/bugs/
