### ISSUE TITLE
gammu freeze after Leaving GSM_SendSMS

### ISSUE THREAD

**Issue by Cyrille37** [gammu/gammu#204]
Hi,
I try to send SMS from a Raspberry with several phones (nokia, samsung) connected via usb.

Gammu version 1.33.0 (default with raspbian jessie-testing)

Gammu communicate with the phone, like `gammu identify` and 'gammu getsmsfolders' work fine.

But when sending a SMS a strange behavior happen: gammu freeze with message "waiting for network response".
In the log file, the freeze corresponds to the line "Leaving GSM_SendSMS".
I can wait a hour, nothing append.
But after a Ctrl-C and unplug the phone, hop! The sms go into the air network and arrive on the destination phone.

Here's the log: 
[gammu.log.txt](https://github.com/gammu/gammu/files/200481/gammu.log.txt)

The 3 last lines of this log appear after Ctrl+C:
```
[System error     - serial_read, 11, "Resource temporarily unavailable"]
[Terminating]
[Closing]
```

Any idea ?
Cheers.

**Comment by Cyrille37** [comment]
I've just compiled **gammu 1.37.0** and the problem persist.

Here is the log file, with debug on, for the command `echo `date` | gammu -d textalldate sendsms TEXT 0632330218`

[gammu.log.txt](https://github.com/gammu/gammu/files/200538/gammu.log.txt)

**Comment by Cyrille37** [comment]
Here again ;-)

So, I try without gammu and have the same problem ... Probably a raspberry/debian problem.

```
AT+CMGF=1
OK
AT+CMGS="99xxxxxxxx"
> coucou
ctrl+z
```

The ctrl+z seems to do nothing, but in fact, when I unplug the phone, hop! The SMS goes on the air and arrives into the other phone.

**Comment by Cyrille37** [comment]
Ok, I close this issue and continue at [stackoverflow](http://stackoverflow.com/questions/36371993/linux-computer-phone-communication-freeze-at-sms-send-gammu-picocom).

**Comment by nijel** [comment]
Indeed it seems like USB serial driver issues...

**Comment by Cyrille37** [comment]
@nijel But the same problem with 2 differents computers ...

**Comment by eddwinpaz** [comment]
@Cyrille37 figure it out? I've had the same problem with Debian so instead I moved to Ubuntu 11.10 then figure out the problem and moved to Ubuntu 17 it has to do with the usb-modswitch library they for some reason sometimes don't have your model so using gammu you can construct it. I can help if haven't found any solution yet. I know what is to be in trouble.. @nijel  has helped me several times hehehe.
