### ISSUE TITLE
reading Calls and SMS on Samsung GT-C3510 (Player Light)

### ISSUE THREAD

**Issue by nazmifr** [gammu/gammu#222]
Hi,
I'm using/testing Wammu, it looks awesome compared to the unusable garbage that the samsung PC studio thing was under windows...

I tried reading the Contacts on that phone, it worked nicely, then I tried reading the Calls and after about a minute it failed. When I try for the Messages or the Calendar the loading windows comes up but nothing happen, then I have "Wammu is not responding".

Is this issue something that can be fixed ? (if it's even worth to be fixed, I would totally understand that it's not but the error message asked for me to report the bug so I'm here :) )

Thanks in advance

PS: I'm under GNU/Linux Debian Jessie 64, using Gammu and python-Gammu 1.33.0 and Wammu 0.37 but it was probably included in the report

**Comment by nijel** [comment]
First try updating Gammu, there have been quite a lot of fixes meanwhile. If that doesn't work, please include debug log as described on http://wammu.eu/support/bugs/

**Comment by nazmifr** [comment]
Hi,
Thanks for the answer, sorry for the duplicate, I thought the bug file was joined automatically, I have saved it as a txt on my hard drive anyway, I'll find it back tomorrow, ok for the new version, I'll try gammu 1.37 and Wammu 0.41-1 ASAP
Cordially

**Comment by nazmifr** [comment]
I compiled the lastest version of Gammu, there is still python-wammu and wammu to do, I'll do them asap and I come back, sorry but I'm really busy these days...
