### ISSUE TITLE
gammu does not receive any SMS from Huawei E3131 on Raspbian

### ISSUE THREAD

**Issue by Aileron79** [gammu/gammu#223]
Hi!
I purchased the Huawei E3131 just to send and receive SMS. Even though the GUI of the dongle shows me SMS in the Inbox, I cannot receive the messages using gammu. I'll provide configuration details, I hope this helps solving the issue.

It took me a while to configure the dongle correctly by using usb_modeswitch to get it to the right mode.

After reboot lsusb displays the dongle as
`Bus 001 Device 005: ID 12d1:1f01 Huawei Technologies Co., Ltd.`

To get my ttyUSB0 device I run
`usb_modeswitch -v 0x12d1 -p 0x1f01 -V 0x12d1 -P 0x1442 -M 55534243000000000000000000000011060000000000000000000000000000`

Then lsusb shows
`Bus 001 Device 006: ID 12d1:1442 Huawei Technologies Co., Ltd.`

This is my .gammurc:
```
[gammu]

port = /dev/ttyUSB0
model =
connection = at
synchronizetime = yes
logfile = /var/log/gammu.log
logformat = textall
use_locking =
gammuloc =
```

Raspbian comes with gammu v1.33.0. I have also manually compiled v1.37.3. The issues are the same, I did not notice any difference. gammu --identify returned proper information about the device:

```
# gammu --identify
Device               : /dev/ttyUSB0
Manufacturer         : Huawei
Model                : unknown (E3131)
Firmware             : 22.521.23.00.00
IMEI                 : (removed)
SIM IMSI             : (removed)
```

Now there are three problems. First, gammu sometimes runs into a timeout. Second, if it does not, gammu says there are absolutely no messages available. Third, sometimes gammu claims that the dongle returned an unknown message (which hereby I report, see attachments). According to the dongle's firmware upgrade process the most recent version is installed.

```
# gammu --getallsms
No response in specified timeout. Probably phone not connected.
# gammu --getallsms
0 SMS parts in 0 SMS sequences
# gammu --getallsms
Unknown response from phone. See <http://wammu.eu/support/bugs/> for information how to report it.
```

Please note that I did not change anything between these commands. I haven't found a way to reproduce a behaviour. The latter one is quite rare. Regarding the timeout, this one sometimes takes longer than other times, in the log it looks to me if there was some kind of infinite loop which is just interrupted by a timeout. I've attached two different versions of timeout log using two different versions of gammu, but I'm not sure if it really depends on the version I use.

I've attached logs for all three cases. Please note that gammu-smsd did not work either. However, I did not investigate this any further as I assume that once the problem is fixed in gammu, it probably works with gammu-ssd as well.

If you have any hints on how to solve that problem or if you need any further information I might have forgotten to include here, please let me know.

[gammu_1.33.0_timeout.txt](https://github.com/gammu/gammu/files/361627/gammu_1.33.0_timeout.txt)
[gammu_1.33.0_unknown_message.txt](https://github.com/gammu/gammu/files/361629/gammu_1.33.0_unknown_message.txt)
[gammu_1.33.0_zero_messages.txt](https://github.com/gammu/gammu/files/361628/gammu_1.33.0_zero_messages.txt)
[gammu_1.37.3_timeout.txt](https://github.com/gammu/gammu/files/361630/gammu_1.37.3_timeout.txt)
[gammu_1.37.3_zero_messages.txt](https://github.com/gammu/gammu/files/361631/gammu_1.37.3_zero_messages.txt)
[gammu-smsd.log.txt](https://github.com/gammu/gammu/files/361634/gammu-smsd.log.txt)

**Comment by Armagetron** [comment]
Hi,

normally when usb_modeswitch is installed correctly, Raspbian should do the switch automatically.

On my Raspbian a device called "gsmmodem" is listed in addition to the ttyUSB*. You should try using this on Raspbian.
