### ISSUE TITLE
Sleep sms

### ISSUE THREAD

**Issue by nekulin** [gammu/gammu#224]
Before sending SMS, it waits for 60 seconds

http://joxi.ru/52avkykhGOdyJA

	/smsd/services/sql.c
	const char now_plus_odbc[] = "{fn CURRENT_TIMESTAMP()} + INTERVAL %d SECOND";

Can I fix it ? Why I can't quickly send a text message ?

**Comment by nijel** [comment]
It waits before retying 600 seconds (see dc0eaced), that's only hardcoded value.

All other values can be confiugured, see description of individual timeouts at http://wammu.eu/docs/manual/smsd/overview.html

**Comment by nekulin** [comment]
Check phone status - Sleep 

This prevents for the quick sending. Is it possible to implement any asynchronous

**Comment by nijel** [comment]
Unfortunately it's not that easy as asynchronous notifications on incoming messages are broken on many modems. Gammu needs to operate on features that modems support reliably.
