### ISSUE TITLE
Is not multithreaded

### ISSUE THREAD

**Issue by nekulin** [gammu/gammu#225]
When I try to send SMS

echo "Test 1" | gammu sendsms TEXT +70000000 -unicode
Then once
echo "Test 2" | gammu sendsms TEXT +70000000 -unicode

he writes that the device is busy

**Comment by nekulin** [comment]
if you take android that he is able to send and receive status messages asynchronously, and gammu does everything synchronously.

**Comment by nijel** [comment]
Indeed Gammu is synchronous (actually asynchronous command line utility would be really hard to use). If you want higher throughput use SMSD where it probably works closer to what you expect, see http://wammu.eu/smsd/

**Comment by nekulin** [comment]
It is also very long, is it possible to work directly with the command without blocking ?

**Comment by nijel** [comment]
No, you need some background daemon to make it work reliably. What is most expensive is initial modem setup to sane state and doing that with every command (this is what gammu commandline does) is really major overhead.

**Comment by nekulin** [comment]
How can I run multiple daemons to one modem, it will be busy and who puts a lock on that busy ?

**Comment by nijel** [comment]
There is just one daemon for one modem. You can send many messages through it...
