### ISSUE TITLE
Huawei E303 will not call out - which dongles will call out?  Will they call with data connected?

### ISSUE THREAD

**Issue by bobbybudnick** [gammu/gammu#229]
I have checked the compatibility list and there are several entries for this device.  Some show calling support and others do not.  When I try to call out I get "function not supported by phone".  I presume there is no workaround for this?  Why do some entries in the compatibility list for this device list working calling support?

What device has fully working calling support?  Will any support calling with an active data connection?

**Comment by nijel** [comment]
Gammu did never handle audio part of the calls, it did just initiate calls on the device, so maybe it's not that useful for modems used these days. Anyway looking at the log might reveal more information why the feature is not working...

**Comment by bobbybudnick** [comment]
Thanks for that information.  A little disappointing but I can use VOIP just as well.
