### ISSUE TITLE
Huawei E303 only receives SMS after texting ATT courtesy number 151

### ISSUE THREAD

**Issue by bobbybudnick** [gammu/gammu#230]
I am only able to receive incoming texts after sending a text to number 151, which is ATT's diagnostic number for texting.  It texts you back saying your texting is working properly.  According to ATT, if you can receive texts from this number everything is ok on your end.

After texting 151, all other incoming texts are delivered in bulk.  Texts to other numbers do not elicit incoming texts.  Outgoing texts always work perfectly.  I had considered writing a script to message 151 every three hours or so as one possible solution.  Is there a better way or a fix for this?

edit:
A text sent around 4 PM finally arrived around 8 AM the next day.  But the next text message arrived only ten minutes later so the issue is possibly fixed.

**Comment by nijel** [comment]
This really looks more like network issue than anything else. Are you able to reproduce that situation?

**Comment by bobbybudnick** [comment]
Everything seems to be working fine now.  Thanks for answering.
