### ISSUE TITLE
getussd on multiple device

### ISSUE THREAD

**Issue by fredyrommy** [gammu/gammu#235]
so i run getussd and while it's running at the same time i also run sendsms
and gammu will return on sendsms
`Error opening device, it is already opened by other application.`

i am aware that the device will be busy running getussd so no way i can run sendsms while it's running
my question is, is it only the device that busy or the gammu will too?

if i use 2 devices and run getussd on both devices at the same time
will it work or the gammu only can run getussd once each time even though i'm using 2 devices?

**Comment by nijel** [comment]
Maybe you're running SMSD in same time? See https://github.com/gammu/gammu/issues/150

**Comment by fredyrommy** [comment]
no the SMSD is not running, the getussd is work it's just the sendsms that return error opening device because the device was still used by getussd
and the getussd is also takes too long to finish, i have to wait 39 seconds to be able to use the device again even though the reply is just need 10 seconds to come

**Comment by nijel** [comment]
It should be way faster in upcoming release. However you can not run two programs on single modem interface.

**Comment by fredyrommy** [comment]
so gammu will be able to run getussd on 2 devices simultaneously?
because right now i only have 1 device and i can't buy more before i'm sure that gammu can do commands simultaneously on multiple device, that would be useless
yeah i wish you could add something like timeout in gammurc for getussd
and when will you update the new version for windows?

**Comment by fredyrommy** [comment]
@nijel could you please answer this question

**Comment by nijel** [comment]
Yes, you can have as many devices operated separately as you want. See https://wammu.eu/docs/manual/config/index.html#working-with-multiple-phones

**Comment by fredyrommy** [comment]
yes i have read that page indeed
but let's just say i connected 2 devices Phone1 and Phone2
and i started getussd on Phone1 that maybe will took at least 10 seconds
while i'm waiting on Phone1 to finish getussd, can i run another getussd on Phone 2?

but like the manual say
(however only one connection is used at one time, you can choose which one to use with gammu -s parameter)
does that means i have to wait for Phone1 to finish, to run getussd on Phone2?

**Comment by nijel** [comment]
Yes, you run separate gammu instance for every modem. The do not influence each other at all.
