### ISSUE TITLE
gammu-1.37.90 but i get error like that

### ISSUE THREAD

**Issue by tric4hyo** [gammu/gammu#236]
I have download gammu in https://ci.appveyor.com/api/buildjobs/naemayvixcu258hd/artifacts/Gammu-1.37.90-Windows.exe, but i get error like that. so i can't testing bug testing connection Oracle ODBC
![e49d5ad0-74dc-11e6-8d1f-d2b43ce205e1](https://cloud.githubusercontent.com/assets/16922625/18335746/0468f430-75ac-11e6-9887-579b6e34e169.png)

My Environment
1. Windows 10 64 bit
2. Oracle 11g XE

Best Regard's

Tri Cahyo H.K

**Comment by fredyrommy** [comment]
i got the same problem but first i got ssleay32.dll missing then after i downloaded ssleay32.dll
i got that error
win 7 64bit

**Comment by tric4hyo** [comment]
Maybe any solution for this problem?

**Comment by fredyrommy** [comment]
it looks like using 32 bit version from [https://ci.appveyor.com/project/nijel/gammu/build/100/job/2rgopuooeh87gfhn/artifacts](url)
doesn't give ssleay32.dll missing error
but haven't try anything else

**Comment by tolilul** [comment]
got the same issue, tried all of them but still got the same error

**Comment by nijel** [comment]
The error can be caused by missing appropriate C runtime, see http://www.bitdefender.com/support/how-to-solve-error-message-%22the-application-was-unable-to-start-correctly-(0x000007b)-click-ok-to-close-the-application%22-1106.html

**Comment by nijel** [comment]
...or by some other missing library.

Can you start gammu.exe or it fails as well?

**Comment by chrlrahmadan** [comment]
cannot start gammu.exe, the error came up when installing

**Comment by chrlrahmadan** [comment]
cannot start gammu.exe, the error came up when installing

**Comment by nijel** [comment]
At first you need  [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145), but still this doesn't seem to work for SMSD.

**Comment by chrlrahmadan** [comment]
i have installed Visual C++ Redistributable for Visual Studio 2015 and then restart pc, still got the error while installing

**Comment by tric4hyo** [comment]
i got the same problem after installed Visual C++ Redistributable for Visual Studio 2015.

**Comment by nijel** [comment]
I've just pushed some fixes for bundled libraries.

The x86 version works fine for me with the x86 redistributable installed, I'm waiting for x64 build to complete: https://ci.appveyor.com/project/nijel/gammu/build/195

**Comment by nijel** [comment]
Latest build works fine in my testing for bot x64 and x86 versions (with MSVC redistributable installed): https://ci.appveyor.com/project/nijel/gammu/build/196

**Comment by fredyrommy** [comment]
installed successfully

tried getussd no service reply
`USSD received
Status               : Terminated
Service reply        : ""
No response in specified timeout. Probably phone not connected.`

installing smsd service is success but won't start
`Error 1053: The service did not respond to the start or control request in a timely fashion.`

my machine is windows 7 64bit

**Comment by nijel** [comment]
Can you please share debug log from the error? Also see https://wammu.eu/support/bugs/ for troubleshooting Windows service errors.

Anyway once you have more detailed information on those, please open separate bug as these problems are certainly different than the original startup errors we had.
