### ISSUE TITLE
gammu ON WINDOWS WITH ms sql SERVER

### ISSUE THREAD

**Issue by geertvdb** [gammu/gammu#24]
hi?

I have an issue with Gammu on SQL server. when I use sql=mssql I got an error at the the start that LIMIT 1 is  not recognised.
If I use sql = access , it goes better but I have have an error on the now() buildin funxtion.
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: gammu: Received IMEI 011997000455877
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: gammu: Leaving GSM_GetIMEI
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: Execute SQL: DELETE FROM phones WHERE IMEI = '011997000455877'
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: Inserting phone info
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: Execute SQL: INSERT INTO phones (IMEI, ID, Send, Receive, InsertIntoDB, TimeOut, Client, Battery, Signal) VALUES ('011997000455877', 'receive', 'yes', 'yes', {fn CURRENT_TIMESTAMP()}, now()+#00:00:10#, 'Gammu 1.33.0, Windows Server 2007 SP1, GCC 4.7, MinGW 3.11', -1, -1)
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: SQLExecDirect failed, Code = -1, ODBC diagnostics:
Mon 2013/09/16 22:18:52 gammu-smsd[12900]: 42000:1:195:[Microsoft][SQL Server Native Client 11.0][SQL Server]'now' is not a recognized built-in function name

I try to replace the statemet in the insert_phone in the gammu_config is it does not work ( attached) 

Could you please advice?

**Comment by nijel** [comment]
You should use ``SQL = mssql``, that should give at least basic compatibility.
