### ISSUE TITLE
No response in specified timeout. Probably phone not connected.

### ISSUE THREAD

**Issue by fredyrommy** [gammu/gammu#241]
after installing gammu 8 on debian i run gammu identify and it works fine but the second or third time it says
`No response in specified timeout. Probably phone not connected.`
sometime it work only once sometime it works twice then return No response

> root@debian:~# gammu identify
> Device               : /dev/ttyUSB0
> Manufacturer         : Wavecom
> Model                : MULTIBAND  900E  1800 (MULTIBAND  900E  1800)
> Firmware             : 651b09gg.Q2406B 1828120 040802 18:22
> IMEI                 : 012345678901234
> SIM IMSI             : 510101962981217
> root@debian:~# gammu identify
> Device               : /dev/ttyUSB0
> Manufacturer         : Wavecom
> Model                : MULTIBAND  900E  1800 (MULTIBAND  900E  1800)
> Firmware             : 651b09gg.Q2406B 1828120 040802 18:22
> IMEI                 : 012345678901234
> SIM IMSI             : 510101962981217
> root@debian:~# gammu identify
> No response in specified timeout. Probably phone not connected.
> root@debian:~# gammu identify
> No response in specified timeout. Probably phone not connected.
> root@debian:~# 

gammu log

> Sun 2016/09/11 20:10:33: [Gammu            - 1.33.0 built 09:23:21 Jul 25 2013 using GCC 4.8]
> Sun 2016/09/11 20:10:33: [Connection       - "at115200"]
> Sun 2016/09/11 20:10:33: [Connection index - 0]
> Sun 2016/09/11 20:10:33: [Model type       - ""]
> Sun 2016/09/11 20:10:33: [Device           - "/dev/ttyUSB0"]
> Sun 2016/09/11 20:10:33: [Running on       - Linux, kernel 3.16.0-4-amd64 (#1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03))]
> Sun 2016/09/11 20:10:38: Serial device: DTR is up, RTS is up, CAR is down, CTS is up
> Sun 2016/09/11 20:10:38: Setting speed to 115200
> Sun 2016/09/11 20:10:40: [Module           - "auto"]
> Sun 2016/09/11 20:10:40: Escaping SMS mode
> Sun 2016/09/11 20:10:40: SENDING frametype 0x00/length 0x02/2
> Sun 2016/09/11 20:10:40: 1B |0D                                                          ..  
> Sun 2016/09/11 20:10:41: Sending simple AT command to wake up some devices
> Sun 2016/09/11 20:10:41: SENDING frametype 0x00/length 0x03/3
> Sun 2016/09/11 20:10:41: 41A|54T|0D                                                      AT.  
> Sun 2016/09/11 20:10:42: Enabling echo
> Sun 2016/09/11 20:10:42: SENDING frametype 0x00/length 0x05/5
> Sun 2016/09/11 20:10:42: 41A|54T|45E|311|0D                                              ATE1.  
> Sun 2016/09/11 20:10:44: Phone does not support enabled echo, it can not work with Gammu!
> Sun 2016/09/11 20:10:44: Init:GSM_TryGetModel failed with error TIMEOUT[14]: No response in specified timeout. Probably phone not connected.
> Sun 2016/09/11 20:10:44: [Terminating]
> Sun 2016/09/11 20:10:44: [Closing]
##

**Comment by nijel** [comment]
Can you please try with current version?

**Comment by fredyrommy** [comment]
which one is the latest version for linux?
i was just using apt-get on debian so doesn't really know the version

**Comment by fredyrommy** [comment]
i got this kind of error on vmware
![pl2303](https://cloud.githubusercontent.com/assets/22022841/18572839/e7b1afc4-7be8-11e6-823d-5e2177f99f05.png)

**Comment by nijel** [comment]
vmware USB forwarding will probably just bring another set of problems, so that's definitely not a good idea.

If you're using Debian, you can probably install packages from other suites: https://packages.debian.org/search?keywords=gammu

**Comment by fredyrommy** [comment]
does gammu have release on raspbian for raspberry pi?

**Comment by nijel** [comment]
I have no clue how rapsbian is related to Debian, but IMHO the Debian packages for armhf architecture should work there as well...

**Comment by ayoublab92** [comment]
Hey, I installed gammu under centos 7 sever, When I test the send sms 
[tooy@Gammu ~] # echo "hello" | gammu --sendsms TEXT +21622229668
No response in specified timeout. Probably phone not connected.
please How  I resolve this issue

**Comment by kopax** [comment]
I have the same issue with Fibocom L850GL on debian
