### ISSUE TITLE
help me : Tue 2016/09/20 23:03:49 gammu-smsd[6764]: No gammu configuration found (no [gammu] section in SMSD config file)!

### ISSUE THREAD

**Issue by heryhumas** [gammu/gammu#243]
Tue 2016/09/20 23:03:49 gammu-smsd[6764]: No gammu configuration found (no [gammu] section in SMSD config file)!

**Comment by nijel** [comment]
Have you created the configuration file and does it contain ```[gammu]``` section?

See our manual for instructions: https://wammu.eu/docs/manual/config/index.html#gammurc
