### ISSUE TITLE
gammu can't recconecting after Error connecting to database!

### ISSUE THREAD

**Issue by wardwar** [gammu/gammu#244]
my version ubuntu gammu 1.37.0
Initialisation failed, stopping Gammu smsd: Database connection timeout. (DB_TIMEOUT[78])
it not recconecting itself. when fail. 
so if my network fail after power down and network not found it stoping smsd it not recconecting.
please help

**Comment by nijel** [comment]
Gammu can not connect to the database, so either you have configured it wrongly or it is not running. See [our documentation](https://wammu.eu/docs/manual/smsd/config.html#option-Service) for more details.
