### ISSUE TITLE
gammu  networkinfo  not logged into network

### ISSUE THREAD

**Issue by mridulwebengineer** [gammu/gammu#245]
Hi,

I am getting this error
gammu networkinfo
Network state        : not logged into network
Packet network state : not logged into network
GPRS                 : detached

Device ZTE MF 180

Why its not enabling ??

Please help.

Thanks.

**Comment by mridulwebengineer** [comment]
gammu setautonetworklogin
Unknown error.

**Comment by nijel** [comment]
You probably want to [setpower ON](https://wammu.eu/docs/manual/gammu/index.html#cmdoption-gammu-arg-setpower) the phone.

Anyway with [debug log](https://wammu.eu/support/bugs/) it would be easier to figure out what went wrong.
