### ISSUE TITLE
Timeout Gammu

### ISSUE THREAD

**Issue by fsilveira060** [gammu/gammu#247]
Thu 2016/09/29 13:39:52: [Gammu            - 1.37.4]
Thu 2016/09/29 13:39:52: [Connection       - "at19200"]
Thu 2016/09/29 13:39:52: [Connection index - 0]
Thu 2016/09/29 13:39:52: [Model type       - "at"]
Thu 2016/09/29 13:39:52: [Device           - "/dev/ttyACM0"]
Thu 2016/09/29 13:39:52: [Running on       - Linux, kernel 4.4.0-36-generic (#55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016)]
Thu 2016/09/29 13:39:52: [Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Thu 2016/09/29 13:39:52: Serial device: DTR is up, RTS is up, CAR is down, CTS is up
Thu 2016/09/29 13:39:52: Setting speed to 19200
Thu 2016/09/29 13:39:52: Escaping SMS mode
Thu 2016/09/29 13:39:52: SENDING frame type 0x00/length 0x02/2
Thu 2016/09/29 13:39:52: 1B |0D                                                          ..              
Thu 2016/09/29 13:39:52: Sending simple AT command to wake up some devices
Thu 2016/09/29 13:39:52: SENDING frame type 0x00/length 0x03/3
Thu 2016/09/29 13:39:52: 41A|54T|0D                                                      AT.             
Thu 2016/09/29 13:39:53: 1 "AT+CIND?"
Thu 2016/09/29 13:39:53: 2 "+CIND: 4,3,1,0,0,1,1,0"
Thu 2016/09/29 13:39:53: 3 "OK"
Thu 2016/09/29 13:39:53: Checking line: OK
Thu 2016/09/29 13:39:53: AT reply state: 1
Thu 2016/09/29 13:39:53: RECEIVED frame type 0x00/length 0x29/41
Thu 2016/09/29 13:39:53: 41A|54T|2B+|43C|49I|4EN|44D|3F?|0D |0D |0A |2B+|43C|49I|4EN|44D AT+CIND?...+CIND
Thu 2016/09/29 13:39:53: 3A:|20 |344|2C,|333|2C,|311|2C,|300|2C,|300|2C,|311|2C,|311|2C, : 4,3,1,0,0,1,1,
Thu 2016/09/29 13:39:53: 300|0D |0A |0D |0A |4FO|4BK|0D |0A                              0....OK..       
Thu 2016/09/29 13:39:53: 
**Thu 2016/09/29 13:39:53: Frame not request now. Please report the error, see <http://wammu.eu/support/bugs/>. Thank you**
Thu 2016/09/29 13:39:53: LAST SENT frame type 0x00/length 3
Thu 2016/09/29 13:39:53: 41A|54T|0D                                                      AT.             
Thu 2016/09/29 13:39:53: RECEIVED frame type 0x00/length 0x29/41
Thu 2016/09/29 13:39:53: 41A|54T|2B+|43C|49I|4EN|44D|3F?|0D |0D |0A |2B+|43C|49I|4EN|44D AT+CIND?...+CIND
Thu 2016/09/29 13:39:53: 3A:|20 |344|2C,|333|2C,|311|2C,|300|2C,|300|2C,|311|2C,|311|2C, : 4,3,1,0,0,1,1,
Thu 2016/09/29 13:39:53: 300|0D |0A |0D |0A |4FO|4BK|0D |0A                              0....OK..       
Thu 2016/09/29 13:39:53: 
Thu 2016/09/29 13:40:12: Enabling echo
Thu 2016/09/29 13:40:12: SENDING frame type 0x00/length 0x05/5
Thu 2016/09/29 13:40:12: 41A|54T|45E|311|0D                                              ATE1.           
Thu 2016/09/29 13:40:22: Phone does not support enabled echo, it can not work with Gammu!
Thu 2016/09/29 13:40:22: Init:Phone->Initialise failed with error TIMEOUT[14]: No response in specified timeout. Probably phone not connected.
Thu 2016/09/29 13:40:22: [Terminating]
Thu 2016/09/29 13:40:22: [Closing]

**Comment by nijel** [comment]
Looks like multiple programs are using single modem. Maybe there is something like ModemManager talking to the phone at the same time? When this happens, both programs will "steal" the communication seeing responses on the commands they did not issue. Please stop other program and use only Gammu with the modem.
