### ISSUE TITLE
error, send message

### ISSUE THREAD

**Issue by farkbarn** [gammu/gammu#249]
Hi, i paste the .log
--------------- System information ----------------
Platform     linux2
Python       2.7.9
wxPython     3.0.1.1
Wammu        0.37
python-gammu 1.33.0
Gammu        1.33.0
Bluetooth    PyBluez
locales      es_VE (UTF-8)
connection   at460800
device       /dev/ttyUSB0
model        auto
Sun 2016/10/09 21:47:48: [Gammu            - 1.33.0 built 09:23:21 Jul 25 2013 using GCC 4.8]
Sun 2016/10/09 21:47:48: [Connection       - "at460800"]
Sun 2016/10/09 21:47:48: [Connection index - 0]
Sun 2016/10/09 21:47:48: [Model type       - ""]
Sun 2016/10/09 21:47:48: [Device           - "/dev/ttyUSB0"]
Sun 2016/10/09 21:47:48: [Running on       - Linux, kernel 3.16.0-4-amd64 (#1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03))]
Sun 2016/10/09 21:47:48: Serial device: DTR is up, RTS is up, CAR is down, CTS is up
Sun 2016/10/09 21:47:48: Setting speed to 460800
Sun 2016/10/09 21:47:48: [Module           - "auto"]
Sun 2016/10/09 21:47:48: Escaping SMS mode
Sun 2016/10/09 21:47:48: SENDING frametype 0x00/length 0x02/2
Sun 2016/10/09 21:47:48: 1B |0D                                                          ..              
Sun 2016/10/09 21:47:48: Sending simple AT command to wake up some devices
Sun 2016/10/09 21:47:48: SENDING frametype 0x00/length 0x03/3
Sun 2016/10/09 21:47:48: 41A|54T|0D                                                      AT.             
Sun 2016/10/09 21:47:49: 1 "AT"
Sun 2016/10/09 21:47:49: 2 "OK"
Sun 2016/10/09 21:47:49: Checking line: OK
Sun 2016/10/09 21:47:49: AT reply state: 1
Sun 2016/10/09 21:47:49: RECEIVED frametype 0x00/length 0x08/8
Sun 2016/10/09 21:47:49: 41A|54T|0D |0A |4FO|4BK|0D |0A                                  AT..OK..        
Sun 2016/10/09 21:47:50: Enabling echo
Sun 2016/10/09 21:47:50: SENDING frametype 0x00/length 0x05/5
Sun 2016/10/09 21:47:50: 41A|54T|45E|311|0D                                              ATE1.           
Sun 2016/10/09 21:47:50: 1 "ATE1"
Sun 2016/10/09 21:47:50: 2 "OK"
Sun 2016/10/09 21:47:50: Checking line: OK
Sun 2016/10/09 21:47:50: AT reply state: 1
Sun 2016/10/09 21:47:50: RECEIVED frametype 0x00/length 0x0B/11
Sun 2016/10/09 21:47:50: 41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Sun 2016/10/09 21:47:50: Trying Motorola mode switch
Sun 2016/10/09 21:47:50: SENDING frametype 0x00/length 0x0A/10

**Comment by nijel** [comment]
The log seems to be quite incomplete (see https://wammu.eu/support/bugs/ for information how to obtain log). Also what exactly is the problem?
