### ISSUE TITLE
Error "DBI failed to init native_mysql driver!" after upgrade to 1.37.90

### ISSUE THREAD

**Issue by yahuarkuntur** [gammu/gammu#251]
After upgrading to 1.37.90 the following errors are show in the logs:

> Oct 21 17:51:38 gammu-smsd[5067]: DBI failed to init native_mysql driver!
> Oct 21 17:51:38 gammu-smsd[5067]: Initialisation failed, stopping Gammu smsd: Failed to initialize DB driver. (DB_DRIVER[75])
> Oct 21 17:51:38 gammu-smsd[5067]: Stopping Gammu smsd: No error. (NONE[1])
> Oct 21 17:51:38 gammu-smsd[5068]: DBI failed to init native_mysql driver!
> 

Any pointers?

Thank you in advance!

**Comment by nijel** [comment]
Did you compile without mysql support? It seems to use DBI for native driver...

**Comment by yahuarkuntur** [comment]
Hi,
Im using this ppa for Ubuntu 14.04:
http://ppa.launchpad.net/nijel/ppa/ubuntu

Any ideas?

Thank you

**Comment by yahuarkuntur** [comment]
Hi,

I just updated to version 1.37.91 and everything seems to be working well :)

Thank you very much!
