### ISSUE TITLE
possible files.c typo or bug

### ISSUE THREAD

**Issue by ScrumpyJack** [gammu/gammu#257]
With files backend:

gammu-smsd-inject seems to create an empty .smsbackup file in the current working directory.

An strace shows that there is an open() function call without a path

open("OUTC20161108_124417_00_NUMBER_sms0.smsbackup", O_RDONLY|O_CREAT|O_EXCL|O_LARGEFILE, 0644) = 5

This breaks if the file is opened outside the user's permissioning environment.

Perhaps it's deliberate - would you be kind enough to mention what behaviour was intended?

There is a strcpy and a strcat, but the open() only seems to be passed Filename, instead of the result of strcat

```
diff --git a/smsd/services/files.c b/smsd/services/files.c
index 6001755..155e402 100644
--- a/smsd/services/files.c
+++ b/smsd/services/files.c
@@ -564,7 +564,7 @@ static GSM_Error SMSDFiles_CreateOutboxSMS(GSM_MultiSMSMessage * sms, GSM_SMSDCo
                 1900 + timeinfo->tm_year, timeinfo->tm_mon + 1, timeinfo->tm_mday, timeinfo->tm_hour, timeinfo->tm_min, timeinfo->tm_sec, buffer2, j, ext);
             strcpy(FullName, Config->outboxpath);
             strcat(FullName, FileName);
-            fd = open(FileName, O_CREAT | O_EXCL, 0644);
+            fd = open(FullName, O_CREAT | O_EXCL, 0644);
             if (fd >= 0) {
                 close(fd);
                 break;
```

**Comment by nijel** [comment]
This is definitely not intended, thanks for spotting. Luckily this was only in testing releases and introduced by bb4d3bd3.

**Comment by ScrumpyJack** [comment]
Neat, thanks for accepting the patch
When is the next release?

**Comment by nijel** [comment]
Soon :-). I don't have any fixed schedule yet, but probably next week.
