### ISSUE TITLE
How does the remote phone feature work?

### ISSUE THREAD

**Issue by pschmitt** [gammu/gammu#259]
Hi,

I just discovered the new new [remote phone feature](https://wammu.eu/docs/manual/config/#connecting-to-remote-phone). Sounds nice, but how do I make this work, ie. what exactly is the script supposed to do? Are there any concrete examples available somewhere?

**Comment by nijel** [comment]
AFAIK it should just forward the input/output to the device, see also #107.

**Comment by nijel** [comment]
I've now also included sample script from original issue in fad5f43870d66c54f1ac1a80cc9578d1b83076d9.

**Comment by pschmitt** [comment]
Thanks, that helps. It still timeouts, how can I debug this?

**Comment by nijel** [comment]
I guess Gammu usual debugging  will work, look at the debug log: https://wammu.eu/support/bugs/

**Comment by nijel** [comment]
Any suggestions to improve the script are welcome, I really did not use it...
