### ISSUE TITLE
How can I send UTF-16 messages using gammu-smsd-inject ? (probably a dupIicate)

### ISSUE THREAD

**Issue by pschmitt** [gammu/gammu#260]
Hi,

I have another question. Can I send UTF-16 (yes, emoji!) messages using `gammu-smsd-inject`? If yes, how?

For now I have been using [gammu-json](https://github.com/browndav/gammu-json) like so:

```
gammu-json -c /etc/gammu-smsd send RECIPIENT "EMOJIS ARE FUN 😍"
```

Using gammu-smsd-inject all emojis are replaced by `?`. What am I missing?

**Comment by nijel** [comment]
What Gammu version do you use? There has been some fixes for emojis in 62146808f25392d223c6e3d69c1ca695c9cfb574 (see  #143), which are released in 1.36.7. However I'm not sure if it fixes all what is needed to send emojis, it was more about fixing receiving them.

**Comment by pschmitt** [comment]
I'm using `community/gammu 1.37.91-1` on archlinuxarm (Raspberry Pi 2)

**Comment by nijel** [comment]
Okay, then it's probably still not resolved, I'll look into it.
