### ISSUE TITLE
SMSC returns 500 status on sending balance sms on number without plus sign

### ISSUE THREAD

**Issue by re3lex** [gammu/gammu#263]
Hi,
I have Huawei e1750 modem connected to Ubuntu 16.04.1 LTS.
Gammu version is 1.37.0
gammu-smsd service is run in background.

My GSM operator sends SMS with balance as response on SMS to number 000100 (without leading plus sign).
So I'm sending SMS to 000100:
`gammu-smsd-inject TEXT 000100 -text "bal"`

but getting status=500 as result:
```
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 1 "AT+CMGS=13"
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 2 "> 07919772929090F01100049110000000FF03E2301B"
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 3 "+CMS ERROR: 500"
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: Checking line: +CMS ERROR: 500
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: AT reply state: 5
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: RECEIVED frame type 0x00/length 0x4E/78
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 41A|54T|2B+|43C|4DM|47G|53S|3D=|311|333|0D |0D |0A |3E>|20 |300 AT+CMGS=13...> 0
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 377|399|311|399|377|377|322|399|322|399|300|399|300|46F|300|311 7919772929090F01
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 311|300|300|300|344|399|311|311|300|300|300|300|300|300|300|46F 100049110000000F
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 46F|300|333|45E|322|333|300|311|42B|0D |0A |0D |0A |2B+|43C|4DM F03E2301B....+CM
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 53S|20 |45E|52R|52R|4FO|52R|3A:|20 |355|300|300|0D |0A          S ERROR: 500..  
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: Error 500
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: SMS sent on device: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:5.1:1.0-port0" status=500, reference=-1
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: CMS Error 500: "unknown error"
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: Error getting send status of message: Unknown error. (UNKNOWN[27])
```

I have shared full log with DebugLevel=255 by this link [https://www.dropbox.com/s/d35dsu8s505xkh5/gammu.log?dl=0](https://www.dropbox.com/s/d35dsu8s505xkh5/gammu.log?dl=0)

From the other hand sms to number with leading plus sign (+000100) is working fine (means SMSC accepts it) though my operator treats it as not supported number.
I have tried to send balance request SMS using AT commands and using number without plus sign and that is working fine: SMSC accepts it correctly and I'm getting response SMS with balance within.

Since I can send SMS onto **000100** via AT command successfully but errors happened when gammu sends message to same number I suppose there is some error either in my configuration or in gammu.
Can you please help me make it working?

**Comment by re3lex** [comment]
Looking into log just noticed that gammu is sending message to number **13** for some reason rather  than 000100:
```
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 1 "AT+CMGS=13"
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 2 "> 07919772929090F01100049110000000FF03E2301B"
Sun 2016/12/18 15:10:33 gammu-smsd[2243]: gammu: 3 "+CMS ERROR: 500"
```

**Comment by re3lex** [comment]
Looks like gammu incorrectly converts recipient number 000100 in pdu package for at+cmgs command. 
I took pdu payload from the log above 07919772929090F01100049110000000FF03E2301B and decoded it using online converter. It appears that recipient number became +0100 which is wrong.

**Comment by re3lex** [comment]
Updated to latest 1.38.0 version but issue still there

**Comment by nijel** [comment]
I've tried to reproduce this and it generates `07919772929090F01100048110000000FF03E2301B`, where the number is correct. Is there some specific configuration in your case which might cause the difference?

**Comment by re3lex** [comment]
Hi nijel

my /etc/gammu-smsdrc config is here
```
# Configuration file for Gammu SMS Daemon

# Gammu library configuration, see gammurc(5)
[gammu]
device = /dev/serial/by-path/pci-0000:00:14.0-usb-0:5.1:1.0-port0
connection = at

# Debugging
logformat = textall

# SMSD configuration, see gammu-smsdrc(5)
[smsd]
service = SQL
driver = native_mysql
host = localhost
database = smsd
user = smsd
password = password
logfile = /var/log/gammu-smsd.log

ResetFrequency = 0
ReceiveFrequency = 60
StatusFrequency = 0
CheckBattery = 0
CheckSignal = 0
CheckNetwork = 0
CommTimeout = 60
SendTimeout = 60
LoopSleep = 10
CheckSecurity = 0
# Increase for debugging information
SMSC = +79272909090
Debuglevel = 1
RunOnReceive = /volume1/bin/sms/OnSmsReceive.sh

```

**Comment by re3lex** [comment]
BTW: I see that in PDU you provided above number is 0100 but I'm trying to send message to 000100

**Comment by nijel** [comment]
Ah, that's the difference, Gammu treats 00 as international prefix. That probably should be skipped for numbers starting with three zeroes...

**Comment by re3lex** [comment]
nijel, thanks for fixing!
Can you please suggest how I can get this fix on my Ubuntu 16.04.1 LTS ?

**Comment by nijel** [comment]
You can build gammu from sources. New version will be probably released in a month or so...

**Comment by re3lex** [comment]
thanks!
