### ISSUE TITLE
CentOS 7 gammu-smsd %preun issue in 1.37.91-1.1 repo rpm

### ISSUE THREAD

**Issue by pjwelsh** [gammu/gammu#267]
# yum remove libgsmsd8 gammu\* libGammu8
Loaded plugins: fastestmirror, langpacks
No Match for argument: libgsmsd8
No Match for argument: libGammu8
Resolving Dependencies
--> Running transaction check
---> Package gammu-smsd.x86_64 0:1.37.91-1.1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================
 Package               Arch              Version                 Repository            Size
============================================================================================
Removing:
 gammu-smsd            x86_64            1.37.91-1.1             installed            112 k

Transaction Summary
============================================================================================
Remove  1 Package

Installed size: 112 k
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
/var/tmp/rpm-tmp.nPelKy: line 3: syntax error near unexpected token `newline'
/var/tmp/rpm-tmp.nPelKy: line 3: `    /sbin/chkconfig --del <script>'
error: %preun(gammu-smsd-1.37.91-1.1.x86_64) scriptlet failed, exit status 2
Error in PREUN scriptlet in rpm package gammu-smsd-1.37.91-1.1.x86_64
  Verifying  : gammu-smsd-1.37.91-1.1.x86_64                                            1/1 

Failed:
  gammu-smsd.x86_64 0:1.37.91-1.1                                                           

Complete!
[root@ca4ae2 gammu]# rpm -q --scripts gammu-smsd
postinstall scriptlet (using /bin/sh):
/sbin/chkconfig --add gammu-smsd
preuninstall scriptlet (using /bin/sh):
if [ $1 = 0 ] ; then
    /sbin/service gammu-smsd stop >/dev/null 2>&1
    /sbin/chkconfig --del <script>
fi

"<script>" should be "gammu-smsd"?
"/sbin/chkconfig --del gammu-smsd"

**Comment by pjwelsh** [comment]
A couple of related notes to this:
1. CentOS 7/RHEL 7 and similar should use "systemctl" instead of "chkconfig" or "service" like:
"systemctl preset gammu-smsd" ~= "chkconfig --add gammu-smsd"
"systemctl stop gammu-smsd" = "service gammu-smsd stop"
"systemctl disable gammu-smsd" ~= "chkconfig --del gammu-smsd"
2. Having both the "/usr/libexec/systemd/system/gammu-smsd.service" and "/etc/rc.d/init.d/gammu-smsd" creates an odd situation for determining which file will be executed. For example, I was adding the "--max-fail" option to the wrong init file. Ideally on a CentOS 7/RHEL 7 and similar system, only the "/usr/libexec/systemd/system/gammu-smsd.service" should be in place.

Thanks!

**Comment by nijel** [comment]
Patches are welcome, I don't have either system to test the changes. Also I was reluctant to move to systemd utill all distros we build for are using it, but that has probably already happened...

**Comment by pjwelsh** [comment]
I can try to provide some patches! I'm not a developer, however.
As far as which distros are using systemd, I know for sure all of the el7 derivatives and  Ubuntu 15.04 and later (https://wiki.ubuntu.com/SystemdForUpstartUsers).

As a side note, is there any time frame for the .38 version for el7?

**Comment by nijel** [comment]
Here I care about Redhat, Fedora and clones, the others have different packages.

**Comment by nijel** [comment]
As for updated build it depends on CMake 3.0, not sure if I will find time for backporting it in near future...

**Comment by nijel** [comment]
I have no clue how to do that in the openSUSE buildservice I currently use for building packages. Is there something similar for CentOS or RHEL?

**Comment by nijel** [comment]
Okay, let's keep this for somebody who can help :-). I'm using Debian, have some knowledge about SUSE, but I really do not follow RHEL and clones.
