### ISSUE TITLE
RHEL 7 or CentOS 7 systemd gammu-smsd.service in wrong location

### ISSUE THREAD

**Issue by pjwelsh** [gammu/gammu#269]
Current location of /usr/lib/systemd/system/gammu-smsd.service should be:
/usr/lib/systemd/system/gammu-smsd.service
in order for RHEL 7 or CentOS 7 to pickup on the service.

The /etc/init.d/gammu-smsd location is also depreciated for these OS versions.

**Comment by nijel** [comment]
What is output of `pkg-config --variable=systemdsystemunitdir systemd` on this system?

**Comment by pjwelsh** [comment]
/usr/lib/systemd/system

**Comment by nijel** [comment]
Great, that it should be correctly installed automatically in future releases.

**Comment by pjwelsh** [comment]
Thank you! Great job as always!
