### ISSUE TITLE
GAMMU --IDNETIFY ISSUE ZTE 190MF 

### ISSUE THREAD

**Issue by bagustilas** [gammu/gammu#275]
i was follow step by step from this web [ [https://juangnakarani.wordpress.com/2015/08/22/membuat-sms-gateway-dengan-gammu-menggunakan-gsm-modem-zte-mf190-part-1/](https://juangnakarani.wordpress.com/2015/08/22/membuat-sms-gateway-dengan-gammu-menggunakan-gsm-modem-zte-mf190-part-1/) ]

    UBUNTU 16.04
    GAMMU V 1.38.1
    zTE 190MF [modem]

WVDIALCONF

```
Found a modem on /dev/ttyUSB1.
Modem configuration written to /etc/wvdial.conf.
ttyUSB1: Speed 9600; init "ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0"
ttyUSB2: Speed 9600; init "ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0"
```

GAMMURC
```
port : /dev/ttyUSB1
connection : at
```

ISSUE IS
No response in specified timeout. Probably phone not connected.

**LOG GAMMU.LOG**
```
root@denbagus:~# tail -f /var/log/gammu/gammu.log
41A|54T|0D                                                      AT.             
Enabling echo
SENDING frame type 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
Phone does not support enabled echo, it can not work with Gammu!
It might be caused by other program using the modem.
See <https://wammu.eu/docs/manual/faq/general.html#echo> for help.
Init:GSM_TryGetModel failed with error TIMEOUT[14]: No response in specified timeout. Probably phone not connected.
[Terminating]
[Closing]
```

**Comment by nijel** [comment]
It might be that some other program is using the device, see https://wammu.eu/docs/manual/faq/general.html#echo

**Comment by bagustilas** [comment]
solved, im enebled the mobile boradband in ubuntu and work thanks mr nijel

**Comment by bagustilas** [comment]
i have another problem 
```
gammu-smsd[10084]: Database structure is from older Gammu version
gammu-smsd[10084]: Initialisation failed, stopping Gammu smsd: Invalid database version. (DB_VERSION[74])
Failed to run SMSD: Invalid database version.
```

**Comment by nijel** [comment]
You need  to upgrade the database, see https://wammu.eu/docs/manual/smsd/tables.html#history-of-database-structure
