### ISSUE TITLE
sentitems table: sending status number [$100]

### ISSUE THREAD

**Issue by melones** [gammu/gammu#276]
Would it be possible to add an extra column to sentitems table with sending status number? 
Currently we have Status column, but this provide very limited information on sending errors (only SendingError or SendingOK). We don't have a detailed information what was wrong when sending fails. 

Smsd log gives this number already: 
Mon 2016/06/02 17:45:20 gammu-smsd[1864]: New message to send: 127
Mon 2016/06/02 17:45:48 gammu-smsd[1864]: SMS sent on device: "/dev/ttyS1" **status=515**, reference=-1
Mon 2016/06/02 17:45:48 gammu-smsd[1864]: Error getting send status of message: Unknown error. (UNKNOWN[27])

It would be nice to have that status number in the table as well, so one can see and troubleshoot problems  without the need to browse logs.

**Comment by melones** [comment]
@gnidorah maybe you would be interested in implementing this feature as well?

**Comment by gnidorah** [comment]
@melones Sure, thank you!
