### ISSUE TITLE
Sending multipart SMS via gammu-smsd-inject

### ISSUE THREAD

**Issue by epankov** [gammu/gammu#278]
According to manual:

`**-len len** - specify, how many chars will be read. When use thisoption and text will be longer than 1 SMS, will be splitted into morelinked SMS`

-len parameter should make gammu-smsd-inject to create multipart message.

But when i run command like this:

`C:\Programms\Gammu-1.33.0\bin>gammu-smsd-inject -c c:\programms\gammu-1.33.0\gam
murc TEXT 89610371128 -unicode -text "Тест на русском второй экземпляр, который
включает тест на длинное сообщение" -len 70`

table outbox_multipart is still empty, and i got only the first part of the message

**Comment by nijel** [comment]
With -len 70, you limit Gammu to read at most 70 chars (as mentioned in the docs you've quoted). You probably rather want -autolen instead.

**Comment by NicoHood** [comment]
But why does the autolen parameter requires a length/number attribute? I dont get the reason for this. Autolen to me means it will autodetect the length. But the parameter requires you to specify the length. `[-len len] [-autolen len]`

**Comment by nijel** [comment]
I have no clue either, sorry :-).

**Comment by NicoHood** [comment]
This sounds like a bug to me?
