### ISSUE TITLE
Automagic

### ISSUE THREAD

**Issue by ktrace** [gammu/gammu#279]
gammu has automagic dependency on ODBC.
Seems to fix it need:

> $ grep -r ODBC_FOUND .
> ./cmake/templates/gammu-config.h.cmake:#cmakedefine ODBC_FOUND
> ./cmake/FindODBC.cmake:# handle the QUIETLY and REQUIRED arguments and set ODBC_FOUND to TRUE if 
> ./cmake/FindODBC.cmake:if(ODBC_FOUND)
> ./cmake/FindODBC.cmake:      set(ODBC_FOUND FALSE)
> ./cmake/FindODBC.cmake:endif(ODBC_FOUND)
> ./smsd/CMakeLists.txt:if (HAVE_MYSQL_MYSQL_H OR LIBDBI_FOUND OR HAVE_POSTGRESQL_LIBPQ_FE_H OR ODBC_FOUND)
> ./smsd/CMakeLists.txt:endif (HAVE_MYSQL_MYSQL_H OR LIBDBI_FOUND OR HAVE_POSTGRESQL_LIBPQ_FE_H OR ODBC_FOUND)
> ./smsd/CMakeLists.txt:if (ODBC_FOUND)
> ./smsd/CMakeLists.txt:endif (ODBC_FOUND)
> ./smsd/CMakeLists.txt:if (ODBC_FOUND)
> ./smsd/CMakeLists.txt:endif (ODBC_FOUND)
> ./smsd/main.c:#ifdef ODBC_FOUND
> ./smsd/CMakeTests.txt:                if (ODBC_FOUND)
> ./smsd/CMakeTests.txt:                endif (ODBC_FOUND)
> ./smsd/inject.c:#ifdef ODBC_FOUND
> ./smsd/monitor.c:#ifdef ODBC_FOUND
> ./smsd/core.c:#if defined(HAVE_MYSQL_MYSQL_H) || defined(HAVE_POSTGRESQL_LIBPQ_FE_H) || defined(LIBDBI_FOUND) || defined(ODBC_FOUND)
> ./smsd/core.c:#if defined(ODBC_FOUND) ||  defined(LIBDBI_FOUND) || defined(HAVE_MYSQL_MYSQL_H) || defined(HAVE_POSTGRESQL_LIBPQ_FE_H)
> ./smsd/core.h:#if defined(HAVE_MYSQL_MYSQL_H) || defined(HAVE_POSTGRESQL_LIBPQ_FE_H) || defined(LIBDBI_FOUND) || defined(ODBC_FOUND)
> ./smsd/core.h:#if defined(HAVE_MYSQL_MYSQL_H) || defined(HAVE_POSTGRESQL_LIBPQ_FE_H) || defined(LIBDBI_FOUND) || defined(ODBC_FOUND)
> ./smsd/services/sql-core.h:#ifdef ODBC_FOUND
> ./smsd/services/sql-core.h:#ifdef ODBC_FOUND
> ./smsd/services/sql-core.h:#ifdef ODBC_FOUND
> ./smsd/services/sql-core.h:#ifdef ODBC_FOUND
> ./smsd/services/sql.c:#ifdef ODBC_FOUND
> ./build-configure/include/gammu-config.h:#define ODBC_FOUND
 
need all ODBC_FOUND replace with   WITH_ODBC.

**Comment by nijel** [comment]
Patches/Pull requests welcome :-).

**Comment by ktrace** [comment]
it will be very ugly patches :)
build without automagic (as i understand) - prefer more strictly for flags -DWITH_XXXXX
fix for ODBC:

> --- CMakeLists.txt	2017-02-25 23:05:05.211461959 +0300
> +++ CMakeLists.txt-	2017-02-26 21:30:49.393176711 +0300
> @@ -183,7 +183,12 @@
>  
>  # Packages in sources
>  macro_optional_find_package (MySQL)
> -macro_optional_find_package (ODBC)
> +
> +if    (WITH_unixODBC)
> +	macro_optional_find_package (ODBC REQUIRED)
> +else  (WITH_unixODBC)
> +	set(ODBC_FOUND FALSE)
> +endif (WITH_unixODBC)
>  macro_optional_find_package (Postgres)
>  macro_optional_find_package (LibDBI)
>  macro_optional_find_package (Libintl)

why it is ugly patch:
1. ODBC in your CMakelists.txt - unixODBC, libiodbc. I fix just unixODBC. 
2. it has other logic for ODBC. other libs (MySQL/PostgreSQL/etc) stay unchanged. 
3. May be more perfect solution were macro_optional_find_package fix, but but I know CMake too few

I hope Your take look on my doodles and solve that problem more pretty :)

**Comment by ktrace** [comment]
mmm?

**Comment by ktrace** [comment]
hi, Michal. sorry for noize, but what you think about fix it?

**Comment by nijel** [comment]
I simply didn't yet get to it, this is not 24x7 support ;-). Looking at it right now...

**Comment by nijel** [comment]
Looking at the existing code, where actually is the problem? There already is WITH_ODBC and it defaults to ON, so it works as expected. Actually all dependencies work this way, so it's consistent.

So if you don't want ODBC, build with -DWITH_ODBC=OFF and it will work.
