### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by hryamzik** [gammu/gammu#284]
Didn't find [this](https://wammu.eu/docs/manual/smsd/run.html#gammu-smsd-run) page on the website project so didn't make a PR, but the example there is wrong.

Here's how `env` look like on a short message:

```
SMS_MESSAGES=1
DECODED_PARTS=0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
LANG=en_US.UTF-8
SHLVL=1
SMS_1_NUMBER=+*********
SMS_1_CLASS=-1
SMS_1_TEXT=one part message!
```

That said, script will fail here:
```python
# Are there any decoded parts?
if numparts == 0:
    print('No decoded parts!')
    sys.exit(1)
```

But that's a valid message! I believe text should be taken from `SMS_1_TEXT` in this case.

```python
text = ''
if numparts == 0:
    text = os.environ['SMS_1_TEXT']
else:
    for i in range(0, numparts):
        varname = 'DECODED_%d_TEXT' % i
        if varname in os.environ:
            text = text + os.environ[varname]

```

**Comment by nijel** [comment]
The source for the documentation is here: https://github.com/gammu/gammu/blob/master/docs/manual/smsd/run.rst

However the example is separate here: https://github.com/gammu/gammu/blob/master/contrib/smsd-scripts/receive-python

**Comment by hryamzik** [comment]
Thanks!
