### ISSUE TITLE
Huawei E372 compatibility issue : stop receiving/sending sms after less than one hour

### ISSUE THREAD

**Issue by dlamalice** [gammu/gammu#286]
Hello,

I'm trying to build a sms server with Raspberry and Huawei E372 usb dongle and I have issues with Gammu.
I've tried differents versions (1.33 which is in raspbian, compiled 1.37.4, 1.37.91 and 1.38.1) but I've the same issue : after a moment without doing anything, it's impossible to send or recieve sms.
I don't see error in logs.

Any idea ?
Thanks.
[gammu-smsd.log](https://drive.google.com/open?id=0B5hZVqJIAP6vMzZmUDVENThsUms)

**Comment by nijel** [comment]
Looks like usual problem with Huawei devices, I've added configuration for it.

You can probably workaround it by configuring `model = E3276`.

**Comment by hryamzik** [comment]
Is there the same issue with E150?

**Comment by nijel** [comment]
Probably, if the log looks similar. I've added it now as well.

The problem is that we can not do this for all Huawei devices as some of them crash on the setup commands...

**Comment by hryamzik** [comment]
I don't have enough statistics yet but seen gamma-smsd process stuck and not responding to USR1 commands.
