### ISSUE TITLE
PHONE_ID missing

### ISSUE THREAD

**Issue by hryamzik** [gammu/gammu#290]
Gammu version 1.38.1

I don't get the `PHONE_ID` env variable.  Luckily arguments work as well so the workaround is to use them:

```
RunOnReceive = /unknown/handleme.py -p somephone
PhoneID = somephone
```

**Comment by nijel** [comment]
As you can see in the [documentation](https://wammu.eu/docs/manual/smsd/run.html#envvar-PHONE_ID), this feature is "New in version 1.38.2.". So it can't work in older versions, sorry. See also https://github.com/gammu/gammu/pull/283

**Comment by hryamzik** [comment]
Oh, I expected to get latest version in official PPA and didn't even check it. Got it now...

**Comment by nijel** [comment]
1.38.2 was not yet released :-)
