### ISSUE TITLE
USSD on Huawei E150

### ISSUE THREAD

**Issue by hryamzik** [gammu/gammu#294]
First of all, it doesn't work with gammu. But works with AT commands. Somehow...

Modem exposes 3 ttyUSB devices, `0` can be used for reading sms but I didn't manage to get USSD with it. `2`, however, worked in `GSM` mode:

```
AT+CSCS?
+CSCS: "GSM"

OK
^BOOT:40292778,0,0,0,255
AT+CUSD=1,"AA184C3602", 15

OK

^RSSI:21

+CUSD: 0,"04110430043B0430043D04410020003500320035002E0032003500200440002E",72

^RSSI:21
```

Decrypted [here](http://smstools3.kekekasvi.com/topic.php?id=288) with `UCS2`.

`^` directives just appear randomly and are not related to USSD.

**Comment by nijel** [comment]
IMHO this should work fine since 22ba52a53595db6e8b0bfe408c0af296a650b49e. The `^` messages are unsolicited codes which Gammu turns of. The USSD should work on any device since above commit as Gammu configures current device to be able to use them.

**Comment by hryamzik** [comment]
What's  your release process, do you have CI for packages? Looks like having latest master in a separate PPA could be useful.

**Comment by nijel** [comment]
No, there are no packages for master, the packages are created manually on release.

**Comment by hryamzik** [comment]
Is this process documented? I think I could try to automate it with travis for master branch.

**Comment by nijel** [comment]
I'm using stock [git-buildpackage](http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.html) workflow, the packaging vcs is here: https://anonscm.debian.org/git/collab-maint/gammu.git
