### ISSUE TITLE
Invalid default value for 'ReceivingDateTime'

### ISSUE THREAD

**Issue by yahuarkuntur** [gammu/gammu#295]
At the time of creating the MySQL backend for gammu, the following error shows:

```
brian@localhost:~/gammu-1.38.1/docs/sql$ mysql -u root -p smsd < mysql.sql 
Enter password: 
ERROR 1067 (42000) at line 29: Invalid default value for 'ReceivingDateTime'

```
The version of MySQL server is 5.7.17 on Ubuntu 16.04 x64 bits.

Any pointers?

Thanks in advance!

**Comment by yahuarkuntur** [comment]
After some research, adding:
```
SET SQL_MODE='ALLOW_INVALID_DATES';
``` 
at the start of the SQL script allows the creation of the gammu tables.

Source: http://stackoverflow.com/questions/9192027/invalid-default-value-for-create-date-timestamp-field

**Comment by nijel** [comment]
Use docs/sql/mysql-strict.sql instead. See also #254 (unfortunately there is no universal way see http://stackoverflow.com/a/17498167/225718).
