### ISSUE TITLE
8bit SMS - Change Coding Group (TP-DCS)

### ISSUE THREAD

**Issue by logscl** [gammu/gammu#297]
Hello,

For a specific use-case, I need to send a 8bit (binary) SMS to a very picky appliance. 
The message must have a very specific TP-CDS: a coding of 8bit data, and the Class must be 3 (TE-specific).

To send my sms with Gammu, I used the "outbox" table of the database. I have filled the following fields :
Text: Some Hex data
DestinationNumber: the recipient
Coding: '8bit'
Class: 3.

To verify that the SMS is correcly formatted, I sent a message to a COM modem plugged to my computer to read the raw PDU.
With the SMS I sent using the "outbox" table, the TP-DCS HEX value is the following : 17 (or 0001 0111 in binary). 
But my appliance is only accepting the following TP-DCS HEX : F7 (1111 0111 in binary).

According to the GSM 03.38 specification (http://www.etsi.org/deliver/etsi_gts/03/0338/05.00.00_60/gsmts_0338v050000p.pdf - page 8) the correct TP-DCS for a binary message must have the bits 7..4 to 1111 (bits 7..4 with a value of 0001 seems to be a reserved coding group). Unfortunately, I am not a SMS specialist and I could be wrong.

Do you have any Idea how I can change the coding group of the binary SMS ?

I'm using Gammu 1.38.0.

Please ask if you need more information.

Best regards,
Logan

**Comment by nijel** [comment]
This is currently hardcoded, see https://github.com/gammu/gammu/blob/master/libgammu/service/sms/gsmsms.c#L1048

Also if you look at more recent specification (still 10 yeas old, see https://github.com/gammu/gsm-docs/blob/master/standards/etsi/gsmts_0338v050300p.pdf, or current one http://www.etsi.org/deliver/etsi_ts/123000_123099/123038/10.00.00_60/ts_123038v100000p.pdf), 8-bit encoding is valid in both cases.

But on the other side it should do no harm using the older version of specs here, I'll adjust the code.
