### ISSUE TITLE
problem receiving MMS

### ISSUE THREAD

**Issue by melones** [gammu/gammu#298]
I was testing receiving of MMS messages according to the docs: https://wammu.eu/docs/manual/smsd/run.html  however I could not make it work.

I receive MMS correctly according to smsd-log:
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Received message from: 48660212345
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Received message from: 48660212345
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Read 2 messages
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Multipart message 0x75, 2 parts of 2
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Inserted message id 288
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Inserted message id 289
Wed 2017/03/22 15:32:16 gammu-smsd[23385]: Starting run on receive: /mnt/scripts/daemon.sh 288 289
Wed 2017/03/22 15:32:16 gammu-smsd[18662]: Process finished successfully

The following script: 
```
#!/bin/sh
if [ "$DECODED_1_MMS_ADDRESS" ] ; then
echo "$DECODED_1_MMS_ADDRESS" "$DECODED_1_MMS_SENDER" "$DECODED_1_MMS_TITLE" >> /tmp/smsd-mms.log
fi
```
outputs nothing to the file. With database backend RunOnReceive script outputs only ID variable as parameter to RunOnReceive script. No other global variables are set.  

Am I doing anything wrong?

**Comment by nijel** [comment]
Can you please post the data from the message as well?

**Comment by melones** [comment]
The message contained a photo, without text.

**Comment by nijel** [comment]
I mean the MMS indication message. Either as seen in the SMSD logs (preferably) or as stored in the database by SMSD.

**Comment by buildog** [comment]
I've the same issue, **$DECODED_1_MMS_ADDRESS** is empty

I'm using a Quectel GSM/GPRS M95

###  .bin created : 

```
application/v|
00000010  6e 64 2e 77 61 70 2e 6d  6d 73 2d 6d 65 73 73 61  |nd.wap.mms-messa|
00000020  67 65 00 af 84 8c 82 98  38 31 33 34 33 39 37 34  |ge......xxxxx|
00000030  40 6d 6d 73 31 00 8d 92  89 18 80 2b 33 32 34 37  |@mms1......+3247|
00000040  36 34 39 33 32 31 31 2f  54 59 50 45 3d 50 4c 4d  |xxxxxxx/TYPE=PLM|
00000050  4e 00 96 00 8f 81 86 81  8a 80 8e 03 03 e1 7b 88  |N.............{.|
00000060  05 81 03 03 f4 80 83 68  74 74 70 3a 2f 2f 6d 74  |.......http://mt|
00000070  73 2f 3f 69 64 3d 38 31  33 34 33 39 37 34 00     |s/?id=xxxxx.|
```

### RunOnReceive script

```sh
#!/bin/sh

for i in `seq $SMS_MESSAGES` ; do
        wget  "http://localhost:8080/?id=$SMS_1_NUMBER&value=$SMS_1_TEXT&mss_addr=$DECODED_1_MMS_ADDRESS&mms_sender=$DECODED_1_MMS_SENDER&mms_title=$DECODED_$
done
```

which wget `/?id=+32xxxxxx&value=&mss_addr=&mms_sender=+32xxxxxx/TYPE=PLMN&mms_title=`

**Comment by buildog** [comment]
@nijel thanks, I updated to 1.38.2, look like the process run fine but it dosen't detect the MMS as a multipart message: 

```
Tue 2017/03/28 18:07:03 gammu-smsd[1072]: Received message from: +32xxxx
Tue 2017/03/28 18:07:03 gammu-smsd[1072]: Read 1 messages
Tue 2017/03/28 18:07:03 gammu-smsd[1072]: Received IN20170328_200639_00_++32xxxx.bin
Tue 2017/03/28 18:07:03 gammu-smsd[1101]: Starting run on receive: /var/spool/gammu/mms.sh IN20170328_200639_00_++32xxxx.bin 
Tue 2017/03/28 18:07:03 gammu-smsd[1072]: Process finished successfully
```

so I still have an empty `$DECODED_1_MMS_ADDRESS`

**Comment by nijel** [comment]
Can you enabled debug log (see https://wammu.eu/support/bugs/) and post log from receiving the message? SMSD should wait for other message parts if it's multipart message. Anyway please do that in separate issue as it's most likely different problem.
