### ISSUE TITLE
Merging multi-part messages also from inbox and outbox tables.

### ISSUE THREAD

**Issue by navennn** [gammu/gammu#301]
Hi, 

I wrote a PHP frontend to Gammu but I've stumbled across one major issue that I do not know how to resolve. That is- all SMS messages are split (like 130 something characters in each). So when I list them in my application, multi-part messages is split to a few rows. 
I've managed to solve this for 'sentitems' table since there is a column called 'SequencePosition'. 

Is there a way to do similar stuff for outbox and inbox tables? 

Since the documentation advises it, I am using gammu-smsd-inject command.
MySQL, PHP.

**Comment by nijel** [comment]
The messages are stored as sent over GSM network. For outbox, the first part is on outbox table, remaining parts in outbox_multipart ones, there is SequencePosition to see ordering.

For inbox, there is currently no processed information exposed, you would have to concatenate message based on UDH field.

**Comment by navennn** [comment]
> The messages are stored as sent over GSM network. For outbox, the first part is on outbox table, remaining parts in outbox_multipart ones, there is SequencePosition to see ordering.
For outbox as well as sentitems? I can't see that in the 'outbox' table structure.

> For inbox, there is currently no processed information exposed, you would have to concatenate message based on UDH field.
I can see it there. 
Is that it https://en.wikipedia.org/wiki/User_Data_Header ?
Is the hex unique every time?

**Comment by nijel** [comment]
For sentitems it's in SequencePosition.

As for UDH, the one you will needs most likely is [explained in docs for creating multipart messages](https://wammu.eu/docs/manual/smsd/tables.html#injecting-long-message-using-sql).

**Comment by navennn** [comment]
I will be trying it out. Thank you!

**Comment by ilyadavydyuk** [comment]
Can you give an example for concat sms by UDH?
