### ISSUE TITLE
gammu-smsd performance

### ISSUE THREAD

**Issue by yarmooh** [gammu/gammu#302]
Hello Michal,

We are investigating performance of the gammu-smsd (1.38.0 and 1.38.2) when sending huge batch of messages.
With this config in smsdrc file:
```
# Communication frequency settings
commtimeout = 10
sendtimeout = 30
maxretries = 2
#receivefrequency = 0
statusfrequency = 180
```
I've noticed that after sending a message, gammu waits 1-3s to get next message from outbox. 
Is it possible to setup that 'timeout' value, or even make gammu not wait at all?

**Comment by melones** [comment]
Hi, 
To the above, I verified this with a log file. Wait time is exactly 3-4 seconds between log entry with "SMS sent on device: " and log entry informing about next message in queue "New message to send: ". 

Below is a piece of smsd log. 

Sun 2017/03/26 06:25:17 gammu-smsd[2642]: New message to send: 21056
Sun 2017/03/26 06:25:17 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:25:20 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=206
Sun 2017/03/26 06:25:20 gammu-smsd[2642]: Transmitted 21056 (total: 1) to 123416326
Sun 2017/03/26 06:25:24 gammu-smsd[2642]: Message: This is a sample text contanining national chars like: koń i żółw poszli dróżką po kość i gwóźdź dla sępa. pawęż chwyć, źródła broń kąśliwie. weź maść
Sun 2017/03/26 06:25:24 gammu-smsd[2642]: New message to send: 21060
Sun 2017/03/26 06:25:24 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:25:27 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=207
Sun 2017/03/26 06:25:27 gammu-smsd[2642]: Transmitted 21060 (total: 1) to 123416765
Sun 2017/03/26 06:25:31 gammu-smsd[2642]: Message: This is a sample text contanining national chars like: koń i żółw poszli dróżką po kość i gwóźdź dla sępa. pawęż chwyć, źródła broń kąśliwie. weź maść
Sun 2017/03/26 06:25:31 gammu-smsd[2642]: New message to send: 21062
Sun 2017/03/26 06:25:31 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:25:34 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=208
Sun 2017/03/26 06:25:34 gammu-smsd[2642]: Transmitted 21062 (total: 1) to 123417106
Sun 2017/03/26 06:25:38 gammu-smsd[2642]: Message: This is a sample text contanining national chars like: koń i żółw poszli dróżką po kość i gwóźdź dla sępa. pawęż chwyć, źródła broń kąśliwie. weź maść
Sun 2017/03/26 06:25:38 gammu-smsd[2642]: New message to send: 21066
Sun 2017/03/26 06:25:38 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:25:41 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=209
Sun 2017/03/26 06:25:41 gammu-smsd[2642]: Transmitted 21066 (total: 1) to 123417829
Sun 2017/03/26 06:25:44 gammu-smsd[2642]: Message: This is a sample text contanining national chars like: koń i żółw poszli dróżką po kość i gwóźdź dla sępa. pawęż chwyć, źródła broń kąśliwie. weź maść
Sun 2017/03/26 06:25:44 gammu-smsd[2642]: New message to send: 21064
Sun 2017/03/26 06:25:44 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:25:47 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=210
Sun 2017/03/26 06:25:47 gammu-smsd[2642]: Transmitted 21064 (total: 1) to 123417365
Sun 2017/03/26 06:25:51 gammu-smsd[2642]: Message: This is a sample text contanining national chars like: koń i żółw poszli dróżką po kość i gwóźdź dla sępa. pawęż chwyć, źródła broń kąśliwie. weź maść
Sun 2017/03/26 06:25:51 gammu-smsd[2642]: New message to send: 21070
Sun 2017/03/26 06:25:51 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:25:54 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=211
Sun 2017/03/26 06:25:54 gammu-smsd[2642]: Transmitted 21070 (total: 1) to 123419031
Sun 2017/03/26 06:25:58 gammu-smsd[2642]: Message: This is a sample text contanining national chars like: koń i żółw poszli dróżką po kość i gwóźdź dla sępa. pawęż chwyć, źródła broń kąśliwie. weź maść
Sun 2017/03/26 06:25:58 gammu-smsd[2642]: New message to send: 21068
Sun 2017/03/26 06:25:58 gammu-smsd[2642]: Message without SMSC, assuming you want to use the one from phone
Sun 2017/03/26 06:26:01 gammu-smsd[2642]: SMS sent on device: "/dev/ttyACM6" status=0, reference=212
Sun 2017/03/26 06:26:01 gammu-smsd[2642]: Transmitted 21068 (total: 1) to 123418599

**Comment by nijel** [comment]
At least one second delay is expected due to [LoopSleep](https://wammu.eu/docs/manual/smsd/config.html#option-LoopSleep). But IMHO it's not really needed there, I'll adjust the code to avoid it if not necessary.
