### ISSUE TITLE
gammu ussd issue

### ISSUE THREAD

**Issue by yarmooh** [gammu/gammu#304]
Hello,
I'm using Telit HE910-D modem. I've got issue with gammu trying to check ussd code:
```
gammu getussd *101#
Press Ctrl+C to break...
*** glibc detected *** gammu: free(): invalid next size (fast): 0x01f9b2f0 ***
Aborted
```
Attached are gammulog and strace. Gammu 1.38.2 compiled natively at raspbian wheezy.
[gammulog.txt](https://github.com/gammu/gammu/files/912677/gammulog.txt)
[strace.txt](https://github.com/gammu/gammu/files/912678/strace.txt)

**Comment by nijel** [comment]
Can you please run gammu in gdb and obtain backtrace of the failure?

**Comment by nijel** [comment]
Nevermind, I've probably found that, the allocation buffer was too small for UCS2 charset.

**Comment by yarmooh** [comment]
Hello Michal,

I've compiled latest git repo (1.38.3) and tried to issuse same command as in first post. It still doesn't work good, I'm attaching logfile.  Should I extend logging?
[ussd.txt](https://github.com/gammu/gammu/files/927708/ussd.txt)

**Comment by yarmooh** [comment]
@nijel can you please have a look at it?

**Comment by mozzee** [comment]
facing similar problem on my testbed. It works fine for the regular USSD string like *100# but if you try to execute a long string like *100*1*2# then it throw 

[root@localhost]# gammu 3 getussd "*202*41*1982#"
Press Ctrl+C to break...
*** glibc detected *** gammu: free(): invalid next size (fast): 0x0000000000725ae0 ***

complete block attached
[getussd-error.txt](https://github.com/gammu/gammu/files/979703/getussd-error.txt)

**Comment by nijel** [comment]
@mozzee This should be fixed in 3864ba7

@yarmooh Phone reports that the AT command is not supported.

**Comment by yarmooh** [comment]
Hello Michal,
I'd like to reopen that issue, because I think that this is the gammu issue that ussd codes dont work in my case.
I'm running newest 1.38.5 now, and running 
`gammu getussd *101#` gives just the 
`Press Ctrl+C to break...`
nothing more. 
Running the same query when using Minicom, gives me answer:

`AT+CUSD=1,"*101#",15`
`OK`
`+CUSD: 2,"Pozostalo Ci 19,63zl do wykorzystania do 2018-05-17 23:59:59. Dodatko5`

I'm attaching gammulog.
[gammu.txt](https://github.com/gammu/gammu/files/1260197/gammu.txt)

**Comment by nijel** [comment]
It seems that this device doesn't like UCS2 as charset for USSD...

**Comment by yarmooh** [comment]
So can we fix that somehow?

**Comment by nijel** [comment]
Certainly - either fix the device to behave according to standards or implement workaround for that in Gammu.
