### ISSUE TITLE
Incorrect timestamp (ignoring Timezone and DST)

### ISSUE THREAD

**Issue by premiero** [gammu/gammu#305]
There is an issue with incorrect timestamp - it is ignoring both DST and timezone. I live in Poland. We have +1 GMT. ATM we also have +1 DST, so when message is comming I got incorrect values like this one:

Sample message  from table inbox (Real receive time was 14:24:40)

UpdatedInDB | ReceivingDateTime
----------- | -----------------
2017-04-13 14:24:40 | 2017-04-13 12:24:08

As You can see, values at database shows 2 hours difference, which is not true. 

Another sample from table sentitems:
(The message was sent at 2017-04-13 14:06:23)

UpdatedInDB | InsertIntoDB | SendingDateTime | DeliveryDateTime
----------- | -----------------| -----------------| -----------------
2017-04-13 14:06:55 | 2017-04-13 12:06:23 | 2017-04-13 14:06:42 | 2017-04-13 12:06:44

How can i correct this? It is really important to me. Is there a way to chanege it @code, so i could compile it on my own after fix?

I'm using 13.8.2

**Comment by nijel** [comment]
The difference between these values is that some use database timestamp functions (UpdatedInDB), while other take timestamp as received from network and format it (ReceivingDateTime).

The formatting is done by [SMSDSQL_Time2String](https://github.com/gammu/gammu/blob/master/smsd/services/sql.c#L283), which doesn't handle timezones at all. AFAIR the timezone information however should be present in those timestamps, so this function should be fixed to correctly include timestamp in generated string.

**Comment by melones** [comment]
@premiero which database backend are you using?

**Comment by premiero** [comment]
@melones It is PostgreSQL indeed.
