### ISSUE TITLE
SQL error when retry of multipart message [$250]

### ISSUE THREAD

**Issue by jan-kratochvil** [gammu/gammu#311]
Hi, I see in my log this entry, does anybody know, what does it mean?

```
Thu 2017/05/18 14:38:47 gammu-smsd[544]: Moved to errorbox, reached MaxRetries: 2919
Thu 2017/05/18 14:38:47 gammu-smsd[544]: Error code: 1062, Error: Duplicate entry '2919-1' for key 'PRIMARY'
Thu 2017/05/18 14:38:47 gammu-smsd[544]: SQL failure: 79
Thu 2017/05/18 14:38:47 gammu-smsd[544]: Error writing to database (SMSDSQL_AddSentSMSInfo)
Thu 2017/05/18 14:38:47 gammu-smsd[544]: Error code: 1062, Error: Duplicate entry '2919-2' for key 'PRIMARY'
Thu 2017/05/18 14:38:47 gammu-smsd[544]: SQL failure: 79
Thu 2017/05/18 14:38:47 gammu-smsd[544]: Error writing to database (SMSDSQL_AddSentSMSInfo)
```

**Comment by jan-kratochvil** [comment]
could be related to this #274

**Comment by jan-kratochvil** [comment]
It's probably some issue with error retry and multipart, first I see:
```
Thu 2017/05/18 14:17:53 gammu-smsd[544]: New message to send: 2919
Thu 2017/05/18 14:17:53 gammu-smsd[544]: Message without SMSC, using configured one
Thu 2017/05/18 14:17:59 gammu-smsd[544]: SMS sent on device: "/dev/ttyACM0" status=0, reference=75
Thu 2017/05/18 14:17:59 gammu-smsd[544]: Transmitted 2919 (part: 1) to +420776187594
Thu 2017/05/18 14:17:59 gammu-smsd[544]: Message without SMSC, using configured one
Thu 2017/05/18 14:18:04 gammu-smsd[544]: SMS sent on device: "/dev/ttyACM0" status=0, reference=76
Thu 2017/05/18 14:18:04 gammu-smsd[544]: Transmitted 2919 (part: 2) to +420776187594
Thu 2017/05/18 14:18:04 gammu-smsd[544]: Message without SMSC, using configured one
Thu 2017/05/18 14:18:13 gammu-smsd[544]: SMS sent on device: "/dev/ttyACM0" status=535, reference=-1
Thu 2017/05/18 14:18:13 gammu-smsd[544]: Error getting send status of message: Unknown error. (UNKNOWN[27])
```
strange is, why 535 is unknown, when in the libgammu/phone/at/atgen.c its ERR_BUSY

after that i see:
```
Thu 2017/05/18 14:28:37 gammu-smsd[544]: New message to send: 2919
Thu 2017/05/18 14:28:37 gammu-smsd[544]: Message without SMSC, using configured one
Thu 2017/05/18 14:28:42 gammu-smsd[544]: SMS sent on device: "/dev/ttyACM0" status=0, reference=113
Thu 2017/05/18 14:28:42 gammu-smsd[544]: Transmitted 2919 (part: 1) to +420776187594
Thu 2017/05/18 14:28:42 gammu-smsd[544]: Error code: 1062, Error: Duplicate entry '2919-1' for key 'PRIMARY'
Thu 2017/05/18 14:28:42 gammu-smsd[544]: SQL failure: 79
Thu 2017/05/18 14:28:42 gammu-smsd[544]: Error writing to database (SMSDSQL_AddSentSMSInfo)
Thu 2017/05/18 14:28:42 gammu-smsd[544]: Error setting sent status: Error in executing SQL query. (SQL[79])
Thu 2017/05/18 14:28:58 gammu-smsd[544]: Received message from: +420776187594
Thu 2017/05/18 14:28:58 gammu-smsd[544]: Read 1 messages
Thu 2017/05/18 14:28:58 gammu-smsd[544]: Delivery report: Delivered to +420776187594
Thu 2017/05/18 14:28:58 gammu-smsd[544]: Failed to find SMS for TPMR=113, Number=
```
that's the retry atempt, and it looks as sent OK, but gammu looks confused...

after this there is the error from the first post at 14:38

**Comment by nijel** [comment]
Indeed there seems to be problem in handling situations when one part of multipart message fails, this is what happens in SMSD_SendSMS:

1. Finds new message to send
2. Sends first part
3. Stores successful sending info in the database
4. Fails to send second part
5. The outbox is not altered now as the message hasn't been fully sent.
6. On next iteration, the message to send is found again
7. Sends first part
8. Tries to stores successful sending info in the database, but it's already there

**Comment by jan-kratochvil** [comment]
I have done few tests and questions is, why use multipart table at all? If I insert two separate messages into outbox with multipart false but with correct UDH, it works as expected and I have correct behavior when message send fail and need to retry.
I have even tested on my LG delaying parts as much as 10mins and it works OK. But the phone does not display the message untill all parts are received!

**Comment by nijel** [comment]
Yes it will work fine if you have single SMSD running on the database. With more of them (and without SenderID set), each part might be picked up by different SMSD and they will not be properly concatenated at receiver due to each coming from different number.

**Comment by jan-kratochvil** [comment]
I understand.
In that case its probably necessary to add status fields to outbox and outbox_multipart and update those, plus change sending process mentioned above. Is that correct?

**Comment by nijel** [comment]
That seems to be the best way to track state of multipart messages...
