### ISSUE TITLE
USB Dongle Won't Send SMS and Daemon Still Running.

### ISSUE THREAD

**Issue by textveloper** [gammu/gammu#314]
Currently, Gammu version 1.30.0 built 18:20:41 on Jul 27 2011 using GCC 4.6 I've installed Ubuntu 11.10 and Have 1 Huawei E1756 USB Dongle. But after 24 hours of usage. The Dongle just sits there and does not send or receive SMS but the daemon still refreshes table phones with the right dongle. My Question is. There is a way using bash or a command to be able to restart the dongle or figure out when the usb isn't sending SMS?

Thanks in Advance.

**Comment by nijel** [comment]
Can you please try whether applying d9a1665 helps?
