### ISSUE TITLE
Improve SMSD delivery report matching

### ISSUE THREAD

**Issue by nijel** [gammu/gammu#319]
> I have been entering number like `0048xxxxxxxxx` but delivery reports has been changing `00` into a `+` sign. Sending to a valud number fixes the issue.

See https://stackoverflow.com/q/44762522/225718

**Comment by tbitowt** [comment]
I'd like to handle this issue. 
I'm thinking that simple fix like this below should work fine.

`Before sending message, change '00' on the beginning of destination number to '+'`
