### ISSUE TITLE
466 - smsd-daemon-null-gid (Failed)

### ISSUE THREAD

**Issue by mozzee** [gammu/gammu#324]
make test  showing below for 1.38.4 on CentOS 7

99% tests passed, 1 tests failed out of 852

Total Test time (real) = 160.39 sec

The following tests FAILED:
        466 - smsd-daemon-null-gid (Failed)
Errors while running CTest
make[1]: *** [test] Error 8
make[1]: Leaving directory `/usr/local/src/gammu-1.38.4/build-configure'
make: *** [test] Error 2

**Comment by nijel** [comment]
Can you please run the tests verbosely to see what went wrong? Following command should do that:

```
make -C build-configure test ARGS=--output-on-failure
```

**Comment by mozzee** [comment]
It says 

`466/852` Test #466: smsd-daemon-null-gid ................................................................***Failed    0.00 sec
Wrong group `name/id!` 

while I am installed it as ROOT

**Comment by nijel** [comment]
What is output of `id -g` command on your system? Does the group this shows exist in /etc/groups?

**Comment by mozzee** [comment]
`[root@localhost gammu-1.38.4]# id -g
0
[root@localhost gammu-1.38.4]# grep -iw 0 /etc/group
root:x:0:
`
