### ISSUE TITLE
USSD empty response  

### ISSUE THREAD

**Issue by nadirbelarouci** [gammu/gammu#326]
I'm trying to send a ussd code 
gammu getussd "*200#"
and all what i get is 
Press Ctrl+C to break...

I sent a message instead and it worked fine.
config file:
[gammu]
port = com10
connection = at
logFile = gammu.log
logFormat = textAll

[smsd]
service = sql
Driver = odbc
host = smsd
sql = mysql
user = smsd
password = password

logs: 

[Gammu            - 1.38.4]
[Connection       - "at"]
[Connection index - 0]
[Model type       - ""]
[Device           - "com10"]
[Running on       - Windows Server 2007 SP1]
Device is \\.\COM10
Serial device: DTR is up, RTS is up
Setting speed to 0
[Module           - "auto"]
Escaping SMS mode
SENDING frame type 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frame type 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frame type 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "UCS2""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x20/32
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|55U|43C|53S|322|22"|0D |0A |0D |0A |4FO|4BK|0D |0A  : "UCS2"....OK..
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
SENDING frame type 0x00/length 0x0E/14
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D          AT+CSCS="GSM".  
1 "AT+CSCS="GSM""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D |0D |0A  AT+CSCS="GSM"...
4FO|4BK|0D |0A                                                  OK..            
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
Getting model
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.        
1 "AT+CGMM"
2 "MF667"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x17/23
41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |4DM|46F|366|366|377|0D  AT+CGMM...MF667.
0A |0D |0A |4FO|4BK|0D |0A                                      ...OK..         
Unknown model, but it should still work
[Model name: `MF667']
[Model data: `']
[Model data: `unknown']
[Connected model  - "MF667"]
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "ZTE CORPORATION"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x21/33
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |5AZ|54T|45E|20 |43C|4FO AT+CGMI...ZTE CO
52R|50P|4FO|52R|41A|54T|49I|4FO|4EN|0D |0A |0D |0A |4FO|4BK|0D  RPORATION....OK.
0A                                                              .               
Manufacturer info received
[Manufacturer: ZTE]
Checking for OBEX support
SENDING frame type 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frame type 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
SENDING frame type 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
[Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Escaping SMS mode
SENDING frame type 0x00/length 0x02/2
1B |0D                                                          ..              
Sending simple AT command to wake up some devices
SENDING frame type 0x00/length 0x03/3
41A|54T|0D                                                      AT.             
1 "AT"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x09/9
41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Enabling echo
SENDING frame type 0x00/length 0x05/5
41A|54T|45E|311|0D                                              ATE1.           
1 "ATE1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x0B/11
41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Trying Motorola mode switch
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
1 "AT+MODE=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x13/19
41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
52R|0D |0A                                                      R..             
Seems not to be supported
Enabling CME errors
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
1 "AT+CMEE=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
1 "AT+CSCS=?"
2 "+CSCS: ("IRA","GSM","UCS2")"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x2F/47
41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Chosen GSM as normal charset
Chosen UCS2 as unicode charset
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
1 "AT+CGMI"
2 "ZTE CORPORATION"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x21/33
41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |5AZ|54T|45E|20 |43C|4FO AT+CGMI...ZTE CO
52R|50P|4FO|52R|41A|54T|49I|4FO|4EN|0D |0A |0D |0A |4FO|4BK|0D  RPORATION....OK.
0A                                                              .               
Manufacturer info received
[Manufacturer: ZTE]
Checking for OBEX support
SENDING frame type 0x00/length 0x0B/11
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
1 "AT+CPROT=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
4FO|52R|0D |0A                                                  OR..            
Checking for SYNCML/OBEX support
SENDING frame type 0x00/length 0x0C/12
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
1 "AT+SYNCML=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x15/21
41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
52R|4FO|52R|0D |0A                                              ROR..           
SENDING frame type 0x00/length 0x0D/13
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
1 "AT$TSSPCSW=?"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x16/22
41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
52R|52R|4FO|52R|0D |0A                                          RROR..          
Getting firmware versions
SENDING frame type 0x00/length 0x08/8
41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.        
1 "AT+CGMR"
2 "BD_HDW5MF667V1.0.0B01"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x27/39
41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |42B|44D|5F_|48H|44D|57W AT+CGMR...BD_HDW
355|4DM|46F|366|366|377|56V|311|2E.|300|2E.|300|42B|300|311|0D  5MF667V1.0.0B01.
0A |0D |0A |4FO|4BK|0D |0A                                      ...OK..         
Received firmware version: "BD_HDW5MF667V1.0.0B01"
Number version is "56671,000100"
[Firmware version - "BD_HDW5MF667V1.0.0B01"]
[Connected]
Entering GSM_SetIncomingUSSD
Enabling incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D                          AT+CUSD=1.      
1 "AT+CUSD=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=1...OK..
Leaving GSM_SetIncomingUSSD
Entering GSM_DialService
SENDING frame type 0x00/length 0x0F/15
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|55U|43C|53S|322|22"|0D      AT+CSCS="UCS2". 
1 "AT+CSCS="UCS2""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x15/21
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|55U|43C|53S|322|22"|0D |0D  AT+CSCS="UCS2"..
0A |4FO|4BK|0D |0A                                              .OK..           
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "UCS2""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x20/32
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|55U|43C|53S|322|22"|0D |0A |0D |0A |4FO|4BK|0D |0A  : "UCS2"....OK..
SENDING frame type 0x00/length 0x24/36
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|300|300|322|41A|300 AT+CUSD=1,"002A0
300|333|322|300|300|333|300|300|300|333|300|300|300|322|333|22" 032003000300023"
2C,|311|355|0D                                                  ,15.            
1 "AT+CUSD=1,"002A0032003000300023",15"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x2A/42
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|300|300|322|41A|300 AT+CUSD=1,"002A0
300|333|322|300|300|333|300|300|300|333|300|300|300|322|333|22" 032003000300023"
2C,|311|355|0D |0D |0A |4FO|4BK|0D |0A                          ,15...OK..      
Leaving GSM_DialService
1 "+CME ERROR: 258"
Checking line: +CME ERROR: 258
AT reply state: 6
RECEIVED frame type 0x00/length 0x11/17
2B+|43C|4DM|45E|20 |45E|52R|52R|4FO|52R|3A:|20 |322|355|388|0D  +CME ERROR: 258.
0A                                                              .               

UNKNOWN frame. Please report the error, see <https://wammu.eu/support/bugs/>. Thank you
RECEIVED frame type 0x00/length 0x11/17
2B+|43C|4DM|45E|20 |45E|52R|52R|4FO|52R|3A:|20 |322|355|388|0D  +CME ERROR: 258.
0A                                                              .               

Entering GSM_SetIncomingUSSD
SENDING frame type 0x00/length 0x0E/14
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D          AT+CSCS="GSM".  
1 "AT+CSCS="GSM""
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x14/20
41A|54T|2B+|43C|53S|43C|53S|3D=|22"|47G|53S|4DM|22"|0D |0D |0A  AT+CSCS="GSM"...
4FO|4BK|0D |0A                                                  OK..            
SENDING frame type 0x00/length 0x09/9
41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
1 "AT+CSCS?"
2 "+CSCS: "GSM""
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1F/31
41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
Terminating possible incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D                          AT+CUSD=2.      
1 "AT+CUSD=2"
2 "ERROR"
Checking line: ERROR
AT reply state: 3
RECEIVED frame type 0x00/length 0x13/19
41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+CUSD=2...ERRO
52R|0D |0A                                                      R..             
Disabling incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D                          AT+CUSD=0.      
1 "AT+CUSD=0"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=0...OK..
Leaving GSM_SetIncomingUSSD
[Terminating]
[Closing]

**Comment by grosjo** [comment]
Hi
@nijel the bug is still the same for me.
How to fix this ?
