### ISSUE TITLE
Receiving SMS  delayed

### ISSUE THREAD

**Issue by goxofy** [gammu/gammu#328]
Hello , my device is Huawei E1780 and it can work with gammu-smsd.

But I found that my device received sms delayed, for example, I use another phone send a sms to my number, it will receive this sms after 20 minutes.  I have tried to set theReceiveFrequency =5 and LoopSleep = 0 but no effect. 

 please help me.

gammu-smsd is running on my Raspberry Pi2

Thank you very much.

**Comment by gamba47** [comment]
This is a network failiure if you don't see anything else in your logs.

gamba47
