### ISSUE TITLE
No USSD response on Huawei E3131

### ISSUE THREAD

**Issue by thekvs** [gammu/gammu#330]
I was trying to run "*100#" USSD command but gammu utility didn't return any response. See attached files for logs and used configuration. I was using gammu "1.38.4" on Raspberry Pi.

[gammu.log.txt](https://github.com/gammu/gammu/files/1179282/gammu.log.txt)
[gammurc.txt](https://github.com/gammu/gammu/files/1179283/gammurc.txt)

**Comment by thekvs** [comment]
Aforementioned USSD command works with gammu 1.38.1. See attached log file.
[gammu-1.38.1.log.txt](https://github.com/gammu/gammu/files/1179654/gammu-1.38.1.log.txt)

**Comment by thekvs** [comment]
1.38.3 doesn't work.
1.38.2 fails with message `*** Error in `/opt/gammu-1.38.2/bin/gammu': free(): invalid next size (fast): 0x00e8b220 ***`.

**Comment by michael-dev** [comment]
Also broken in 1.38.5~20170917-1 .

**Comment by nijel** [comment]
Can you please try it with 1591fbe87ac26ed21621848cf9dcd7671b6b32ec?

**Comment by thekvs** [comment]
Still doesn't work. Log file attached, configuration file is the same.
[gammu.log.txt](https://github.com/gammu/gammu/files/1485399/gammu.log.txt)

**Comment by nijel** [comment]
Thanks for testing. Probably there is no other way than bringing back old code, I've tried that in 4b4737e80, can you please test again?

**Comment by nijel** [comment]
Fix confirmed in https://github.com/gammu/gammu/issues/316#issuecomment-346791064.
