### ISSUE TITLE
Modem Pool with one Imei and Multiple port

### ISSUE THREAD

**Issue by khairu-aqsara** [gammu/gammu#334]
i have 1 modem connected with 16 port of sim card,each config connected to same database on my server,send and receive sms all working like a charm, each port have smsd services, like

```
gammu-smsd -c /etc/gammu-smsdrc-modem1 --pid /var/run/gammu-smsdrc-modem1 --daemon
gammu-smsd -c /etc/gammu-smsdrc-modem2 --pid /var/run/gammu-smsdrc-modem2 --daemon
```

each port have their own `PhoneID`, like `modem1` and `modem2`, the problem is why phones tables in gammu databases keep replacing the data with last `gammu-smsd` services run ?

ex: if i run the first config, then phones tables will contains all informations , like signal, IMEI from 1st port, but when i run 2nd gammu-smsd data from 1st port will gone, changed from 2nd port config

here is my `smsdrc` config from `modem1 /etc/gammu-smsdrc-modem1`

```
[gammu]
port = /dev/ttyUSB0
model =
connection = at115200
synchronizetime = yes
logfile = /var/log/gammu-smsdrc-modem1
logformat = nothing
use_locking =
gammuloc =

[smsd]
service=sql
logfile=/var/log/gammu-smsdrc-modem1
debuglevel=0
Driver=native_mysql
User=root
Password=root
PC=localhost
Database=test
PhoneID=modem1
```
here is my smsd config from `modem2 /etc/gammu-smsdrc-modem2`

```
[gammu]
port = /dev/ttyUSB1
model =
connection = at115200
synchronizetime = yes
logfile = /var/log/gammu-smsdrc-modem2
logformat = nothing
use_locking =
gammuloc =

[smsd]
service=sql
logfile=/var/log/gammu-smsdrc-modem2
debuglevel=0
Driver=native_mysql
User=root
Password=root
PC=localhost
Database=test
PhoneID=modem2
```

after some reading on API Doc of gammu, i have figure it out, yes like the first one, it because i use one modem with 16 port of sim card, gammu just detect singel IMEI even the modem have 16 port, quick answer for my question come from `smsd/services/sql.c`

```
if (SMSDSQL_option(Config, SQL_QUERY_DELETE_PHONE, "delete_phone",
    "DELETE FROM phones WHERE ", ESCAPE_FIELD("IMEI"), " = %I", NULL) != ERR_NONE) {
    return ERR_UNKNOWN;
}

.......
.......
.......

if (SMSDSQL_option(Config, SQL_QUERY_UPDATE_RECEIVED, "update_received",
    "UPDATE phones SET ",
        ESCAPE_FIELD("Received"), " = ", ESCAPE_FIELD("Received"), " + 1"
        " WHERE ", ESCAPE_FIELD("IMEI"), " = %I", NULL) != ERR_NONE) {
    return ERR_UNKNOWN;
}
```

i know i have to modify that code in other sql run trough PhoneID not By IMEI, but can we make that changes from SMSD Config File , like or similiar like this one ? because not every body can compiling the sources

```
[tables]
phones

[phones_key]
ID
```

**Comment by sikumkum** [comment]
i have the same problem also.. working on win10 pro with 16 modem pool..
not working

**Comment by wcypierre** [comment]
Had this issue as well and read this back then (few years ago) and couldn't get it.

Had some time today and with chatgpt (didn't really helped much though) and going through the docs, you will need these 2 changes

Tested this on gammu 1.42.0 + MySQL backend

1. Change the gammu config file to change the query to include filtering against the phone id field + imei
2. Drop the phones table PK and readd it using composite PK of ID + IMEI

Add this to the end of your gammu config file

```
[sql]
delete_phone = DELETE FROM phones WHERE ID = %P AND IMEI = %I
update_sent = UPDATE phones SET Sent = Sent + 1 WHERE ID = %P AND IMEI = %I
refresh_phone_status = UPDATE phones SET TimeOut= (NOW() + INTERVAL 10 SECOND) + 0, Battery = %1, `Signal` = %2 WHERE ID = %P AND IMEI = %I
update_received = UPDATE phones SET Received = Received + 1 WHERE ID = %P AND IMEI = %I
```


```
ALTER TABLE `phones`
CHANGE `ID` `ID` text(50) COLLATE 'utf8mb4_general_ci' NOT NULL;

ALTER TABLE phones DROP PRIMARY KEY, ADD PRIMARY KEY(ID(50), IMEI);
```

Adjust the 50, and utf8mb4_general_ci accordingly
