### ISSUE TITLE
Cannot Access Received SMS placed in Location 0

### ISSUE THREAD

**Issue by chaozdjinn** [gammu/gammu#337]
I want to get individual sms via **getsms** command but the 1st sms in received is in Location 0.
getsms does not allow location 0 but starts at 1

:>gammu --getallsms

Location 0, folder "Inbox", SIM memory, Inbox folder
SMS message
SMSC number          : "+yyzzzzzzzzzz"
Sent                 : Time Here
Coding               : Default GSM alphabet (no compression)
Remote number        : "zzzzzzzzzzz"
Status               : Read

adfasdfasdfasdfsdf

Location 1, folder "Inbox", SIM memory, Inbox folder
SMS message
SMSC number          : "+yyxxxxxxxxxx"
Sent                 : time here
Coding               : Default GSM alphabet (no compression)
Remote number        : "zzzzzzzzzzz"
Status               : UnRead

ssssssssssss

2 SMS parts in 2 SMS sequences
- - - - - - - -  - - - - - - - - - - - - - - - - - - - - - - - - - 

:> gammu --getsmsfolders
1. "                         Inbox", SIM memory, Inbox folder
2. "                        Outbox", SIM memory, Outbox folder
3. "                         Inbox", phone memory, Inbox folder
4. "                        Outbox", phone memory, Outbox folder

:> gammu --getsms 1 0
Error: Please enumerate locations from 1

**Comment by nijel** [comment]
The phone most likely needs to set F_SMS_LOCATION_0 flag in gammu, what modem do you use?

**Comment by chaozdjinn** [comment]
I have a Huawei e1552

**Comment by camachorm** [comment]
How do you set the F_SMS_LOCATION_0 flag?

**Comment by chaozdjinn** [comment]
Yes I want to know too.. want to continue testing..

**Comment by chaozdjinn** [comment]
Confirmed fixed...
Downloaded the master zip file... uncompressed, configure, make, make install =D

**Comment by romanrm** [comment]
Why does this check exist in the first place?
I now face the same problem with ZTE MF823D. Will you add models which enumerate SMS from zero manually, one by one? Seriously?...

**Comment by nijel** [comment]
We do this for historical reasons how locations are handled inside Gammu. Patches to change this are seriously welcome.

**Comment by romanrm** [comment]
For the record, adding

    Features = sms_location_0

into the config file, seems to work as a workaround for now.
Thanks
