### ISSUE TITLE
Issue with Huawei modem E169 modem after gamma-smsd update from 1.33.0 to 1.38.1

### ISSUE THREAD

**Issue by JimPitbar** [gammu/gammu#351]
Hello
I am facing a very similar issue than #138. I am using a Huawei 3G USB key E169. It is currently working fine on a Rasp PI3 with Gammu-smsd version 1.33.0
I recently installed a new Rasp PI3 and I got (from apt-get) Gammu-smsd version 1.38.1
Unfortunately, I am now facing unpredictable results where 50% of the time Gammu-smsd can't connect to the key and sometimes it can! The thing I noticed is that each time the problem occurs, I noticed my list of USB devices becomes (/dev/ttyUSB1 USB2 USB3) instead of (/dev/ttyUSB0 USB1 USB2) as if the device got closed and reopened. I am joining the logfile corresponding to the situation where the first start is ok and after a reboot of the machine, it does not work any longer. Your help would be precious
Many thanks
Jim
[logout2.txt](https://github.com/gammu/gammu/files/1298837/logout2.txt)

**Comment by nijel** [comment]
Try using more recent Gammu version, it should behave better with Huawei devices, see https://github.com/gammu/gammu/issues/138.

**Comment by JimPitbar** [comment]
Hi Nijel, sorry for my late reply, just tried it today and it did fix my issue so Thx a lot,
Best, Jim
