### ISSUE TITLE
ATH does not work (call hangup)

### ISSUE THREAD

**Issue by leonardpitzu** [gammu/gammu#357]
phone number masked with aaaaaaaaaa
i am using a custom build of the master branch

Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Leaving GSM_CancelCall                                                                                                                                            
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 1 "RING"                                                                                                                                                          
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Checking line: RING                                                                                                                                               
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: AT reply state: 4                                                                                                                                                 
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: RECEIVED frame type 0x00/length 0x06/6                                                                                                                            
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 52R|49I|4EN|47G|0D |0A                                          RING..                                                                                            
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Incoming call info                                                                                                                                                
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Ring detected - ignoring                                                                                                                                          
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 1 "+CRING: VOICE"                                                                                                                                                 
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Checking line: +CRING: VOICE                                                                                                                                      
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: AT reply state: 4                                                                                                                                                 
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: RECEIVED frame type 0x00/length 0x0F/15                                                                                                                           
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 2B+|43C|52R|49I|4EN|47G|3A:|20 |56V|4FO|49I|43C|45E|0D |0A      +CRING: VOICE..                                                                                   
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Incoming call info                                                                                                                                                
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Ring detected - ignoring                                                                                                                                          
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 1 "+CLIP: "aaaaaaaaaa",161,"",,"",0"                                                                                                                              
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Checking line: +CLIP: "aaaaaaaaaa",161,"",,"",0                                                                                                                   
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: AT reply state: 4                                                                                                                                                 
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: RECEIVED frame type 0x00/length 0x22/34                                                                                                                           
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 2B+|43C|4CL|49I|50P|3A:|20 |22"|300|377|322|322|377|377|344|322 +CLIP: "07227742                                                                                  
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 377|300|22"|2C,|311|366|311|2C,|22"|22"|2C,|2C,|22"|22"|2C,|300 70",161,"",,"",0                                                                                  
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: 0D |0A                                                          ..                                                                                                
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Incoming call info                                                                                                                                                
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: CLIP detected                                                                                                                                                     
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Parsing +CLIP: "aaaaaaaaaa",161,"",,"",0                                                                                                                          
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu:  with +CLIP: @p,@0                                                                                                                                                
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Grabbed string from reply: "aaaaaaaaaa" (parsed 12 bytes)                                                                                                         
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Parsed phone string "aaaaaaaaaa"                                                                                                                                  
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: gammu: Phone string decoded as "aaaaaaaaaa"                                                                                                                              
Tue 2017/09/26 11:56:17 gammu-smsd[4664]: Incoming call! # avail? 1 aaaaaaaaaa

**Comment by nijel** [comment]
You mean that HangupCalls does not work? I see no ATH in the posted log...

**Comment by leonardpitzu** [comment]
the call does not hang up and the script triggered by the incoming call is running in an endless loop

**Comment by leonardpitzu** [comment]
calls are coming in but it keeps ringing (call is not actually hung up and the script in RunOnIncomingCall is called indefinitely.
attached are the settings and a part of the log (this part keeps repeating).
please let me know if i am doing something wrong and/or how i can help you out debuging this.

[log.txt](https://github.com/gammu/gammu/files/1393576/log.txt)
[settings.txt](https://github.com/gammu/gammu/files/1393577/settings.txt)

**Comment by nijel** [comment]
Well this time it looks like the modem actually ignores the ATH, not sure if there is something Gammu can do better...

**Comment by leonardpitzu** [comment]
in the stable release the call correctly hung up (modem responds correctly to ATH). if it's the modem i'll try another one (have to get it first) but if it's software maybe we can fix it...

**Comment by nijel** [comment]
Strange, there was really no difference in handling calls. Can you please retest with older version now?

**Comment by leonardpitzu** [comment]
sure. i'll test .4 and .5 releases and report back.

**Comment by leonardpitzu** [comment]
i have tested both .4 and .5 releases. both releases expressed the same problem, that is the call was not hang up. i fixed this removing my manually set parameters:
receivefrequency = 60
statusfrequency = 60
loopsleep = 10
after this the .4 release worked as expected. the .5 release hung up the call but the RunOnIncomingCall script was executed every a few seconds in a infinite loop. the script is basic - echo $1; exit 0
[5.txt](https://github.com/gammu/gammu/files/1394278/5.txt)
