### ISSUE TITLE
Wammu crashes everytime i try to import an .ics file

### ISSUE THREAD

**Issue by DrAxelbauer** [gammu/gammu#36]
Hi evreyone!
I tried to import a .ics file to bring it to my phone, but during the process of importing there occurs a segmentation fault which brings wammu to crash. 

Here is the log file:
http://paste.opensuse.org/70405119

MY system: Opensuse 13.1 Kernel 3.11
GAmmu: 0.36
Python: 2.7.5

THanks for help!

Some more information if i try it with gammu:
gammu --restore /home/benji/Schreibtisch/benji.ics -yes
*** stack smashing detected ***: gammu terminated
Speicherzugriffsfehler

ACtually also trying it with a .vcs file won´t work out:

gammu --restore /home/benji/Schreibtisch/Kwrite.vcs -yes
Unbekannter Fehler.

**Comment by nijel** [comment]
No chance to reproduce without more data.
