### ISSUE TITLE
conection with a blackberry curve 8520 (bluetooth) string indices must be integer

### ISSUE THREAD

**Issue by raresbaicu** [gammu/gammu#37]
--------------- System information ----------------
Platform     linux2
Python       2.7.3
wxPython     2.8.12.1
Wammu        0.36
python-gammu 1.31.90
Gammu        1.31.90
Bluetooth    PyBluez
locales      ro_RO (UTF-8)
connection   blueat
device       CC:55:AD:CB:23:03
model        obex
Sat 2013/12/28 23:11:59: [Gammu            - 1.31.90 built 16:37:44 Jun  9 2012 using GCC 4.7]
Sat 2013/12/28 23:11:59: [Connection       - "bluephonet"]
Sat 2013/12/28 23:11:59: [Connection index - 0]
Sat 2013/12/28 23:11:59: [Model type       - ""]
Sat 2013/12/28 23:11:59: [Device           - "CC:55:AD:CB:23:03"]
Sat 2013/12/28 23:11:59: [Running on       - Linux, kernel 3.2.0-4-486 (#1 Debian 3.2.53-2)]
Sat 2013/12/28 23:11:59: Looking for suitable channel for PHONET
Sat 2013/12/28 23:11:59: Device CC:55:AD:CB:23:03
Sat 2013/12/28 23:13:43:    Channel 2 - "Voice gateway" (score=0)
Sat 2013/12/28 23:13:43:    Channel 3 - "Hands-free" (score=0)
Sat 2013/12/28 23:13:43:    Channel 4 - "BlackBerry Desktop Service P:0x2359FFFC R:0x03 V:0x20204" (score=0)
Sat 2013/12/28 23:13:43:    Channel 6 - "SIM Access" (score=0)
Sat 2013/12/28 23:13:43:    Channel 1 - "Phonebook Access PSE" (score=0)
Sat 2013/12/28 23:13:43: No suitable bluetooth channel found!
Sat 2013/12/28 23:13:43: Init:GSM_TryGetModel failed with error NOTSUPPORTED[21]: Function not supported by phone.
Sat 2013/12/28 23:13:43: [Gammu            - 1.31.90 built 16:37:44 Jun  9 2012 using GCC 4.7]
 41A|54T|2B+|43C|43C|4CL|4BK|3F?|0D                              AT+CCLK?.       
Sat 2013/12/28 23:38:40: 1 "AT+CCLK?"
Sat 2013/12/28 23:38:40: 2 "ERROR"
Sat 2013/12/28 23:38:40: Checking line: ERROR
Sat 2013/12/28 23:38:40: AT reply state: 3
Sat 2013/12/28 23:38:40: RECEIVED frametype 0x00/length 0x13/19
Sat 2013/12/28 23:38:40: 41A|54T|2B+|43C|43C|4CL|4BK|3F?|0D |0A |0D |0A |45E|52R|52R|4FO AT+CCLK?....ERRO
Sat 2013/12/28 23:38:40: 52R|0D |0A                                                      R..             
Sat 2013/12/28 23:38:40: GSM_GetDateTime failed with error NOTSUPPORTED[21]: Function not supported by phone.
Sat 2013/12/28 23:38:40: Leaving GSM_GetDateTime
Sat 2013/12/28 23:39:10: Entering GSM_GetSignalQuality
Sat 2013/12/28 23:39:10: Getting signal quality info
Sat 2013/12/28 23:39:10: SENDING frametype 0x00/length 0x07/7
Sat 2013/12/28 23:39:10: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Sat 2013/12/28 23:39:10: 1 "AT+CSQ"
Sat 2013/12/28 23:39:10: 2 "+CSQ: 25,99"
Sat 2013/12/28 23:39:10: 3 "OK"
Sat 2013/12/28 23:39:10: Checking line: OK
Sat 2013/12/28 23:39:10: AT reply state: 1
Sat 2013/12/28 23:39:10: RECEIVED frametype 0x00/length 0x1B/27
Sat 2013/12/28 23:39:10: 41A|54T|2B+|43C|53S|51Q|0D |0A |2B+|43C|53S|51Q|3A:|20 |322|355 AT+CSQ..+CSQ: 25
Sat 2013/12/28 23:39:10: 2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                      ,99....OK..     
Sat 2013/12/28 23:39:10: Signal quality info received
Sat 2013/12/28 23:39:10: Parsing +CSQ: 25,99 with +CSQ: @i, @i
Sat 2013/12/28 23:39:10: Parsed int 25
Sat 2013/12/28 23:39:10: Parsed int 99
Sat 2013/12/28 23:39:10: Leaving GSM_GetSignalQuality
Sat 2013/12/28 23:39:10: Entering GSM_GetBatteryCharge
Sat 2013/12/28 23:39:10: Getting battery charge
Sat 2013/12/28 23:39:10: SENDING frametype 0x00/length 0x07/7
Sat 2013/12/28 23:39:10: 41A|54T|2B+|43C|42B|43C|0D                                      AT+CBC.         
Sat 2013/12/28 23:39:10: 1 "AT+CBC"
Sat 2013/12/28 23:39:10: 2 "+CBC: 0,96"
Sat 2013/12/28 23:39:10: 3 "OK"
Sat 2013/12/28 23:39:10: Checking line: OK
Sat 2013/12/28 23:39:10: AT reply state: 1
Sat 2013/12/28 23:39:10: RECEIVED frametype 0x00/length 0x1A/26
Sat 2013/12/28 23:39:10: 41A|54T|2B+|43C|42B|43C|0D |0A |2B+|43C|42B|43C|3A:|20 |300|2C, AT+CBC..+CBC: 0,
Sat 2013/12/28 23:39:10: 399|366|0D |0A |0D |0A |4FO|4BK|0D |0A                          96....OK..      
Sat 2013/12/28 23:39:10: Battery level received
Sat 2013/12/28 23:39:10: Parsing +CBC: 0,96 with +CBC: @i, @i
Sat 2013/12/28 23:39:10: Parsed int 0
Sat 2013/12/28 23:39:10: Parsed int 96
Sat 2013/12/28 23:39:10: Leaving GSM_GetBatteryCharge
Sat 2013/12/28 23:39:10: Entering GSM_GetDateTime
Sat 2013/12/28 23:39:10: Getting date & time
Sat 2013/12/28 23:39:10: SENDING frametype 0x00/length 0x09/9
Sat 2013/12/28 23:39:10: 41A|54T|2B+|43C|43C|4CL|4BK|3F?|0D                              AT+CCLK?.       
Sat 2013/12/28 23:39:10: 1 "AT+CCLK?"
Sat 2013/12/28 23:39:10: 2 "ERROR"
Sat 2013/12/28 23:39:10: Checking line: ERROR
Sat 2013/12/28 23:39:10: AT reply state: 3
Sat 2013/12/28 23:39:10: RECEIVED frametype 0x00/length 0x13/19
Sat 2013/12/28 23:39:10: 41A|54T|2B+|43C|43C|4CL|4BK|3F?|0D |0A |0D |0A |45E|52R|52R|4FO AT+CCLK?....ERRO
Sat 2013/12/28 23:39:10: 52R|0D |0A                                                      R..             
Sat 2013/12/28 23:39:10: GSM_GetDateTime failed with error NOTSUPPORTED[21]: Function not supported by phone.
Sat 2013/12/28 23:39:10: Leaving GSM_GetDateTime
Sat 2013/12/28 23:39:40: Entering GSM_GetSignalQuality
Sat 2013/12/28 23:39:40: Getting signal quality info
Sat 2013/12/28 23:39:40: SENDING frametype 0x00/length 0x07/7
Sat 2013/12/28 23:39:40: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Sat 2013/12/28 23:39:40: 1 "AT+CSQ"
Sat 2013/12/28 23:39:40: 2 "+CSQ: 25,99"
Sat 2013/12/28 23:39:40: 3 "OK"
Sat 2013/12/28 23:39:40: Checking line: OK
Sat 2013/12/28 23:39:40: AT reply state: 1
Sat 2013/12/28 23:39:40: RECEIVED frametype 0x00/length 0x1B/27
Sat 2013/12/28 23:39:40: 41A|54T|2B+|43C|53S|51Q|0D |0A |2B+|43C|53S|51Q|3A:|20 |322|355 AT+CSQ..+CSQ: 25
Sat 2013/12/28 23:39:40: 2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                      ,99....OK..     
Sat 2013/12/28 23:39:40: Signal quality info received
Sat 2013/12/28 23:39:40: Parsing +CSQ: 25,99 with +CSQ: @i, @i
Sat 2013/12/28 23:39:40: Parsed int 25
Sat 2013/12/28 23:39:40: Parsed int 99
Sat 2013/12/28 23:39:40: Leaving GSM_GetSignalQuality
Sat 2013/12/28 23:39:40: Entering GSM_GetBatteryCharge
Sat 2013/12/28 23:39:40: Getting battery charge
Sat 2013/12/28 23:39:40: SENDING frametype 0x00/length 0x07/7
Sat 2013/12/28 23:39:40: 41A|54T|2B+|43C|42B|43C|0D                                      AT+CBC.         
Sat 2013/12/28 23:39:40: 1 "AT+CBC"
Sat 2013/12/28 23:39:40: 2 "+CBC: 0,96"
Sat 2013/12/28 23:39:40: 3 "OK"
Sat 2013/12/28 23:39:40: Checking line: OK
Sat 2013/12/28 23:39:40: AT reply state: 1
Sat 2013/12/28 23:39:40: RECEIVED frametype 0x00/length 0x1A/26
Sat 2013/12/28 23:39:40: 41A|54T|2B+|43C|42B|43C|0D |0A |2B+|43C|42B|43C|3A:|20 |300|2C, AT+CBC..+CBC: 0,
Sat 2013/12/28 23:39:40: 399|366|0D |0A |0D |0A |4FO|4BK|0D |0A                          96....OK..      
Sat 2013/12/28 23:39:40: Battery level received
Sat 2013/12/28 23:39:40: Parsing +CBC: 0,96 with +CBC: @i, @i
Sat 2013/12/28 23:39:40: Parsed int 0
Sat 2013/12/28 23:39:40: Parsed int 96
Sat 2013/12/28 23:39:40: Leaving GSM_GetBatteryCharge
Sat 2013/12/28 23:39:40: Entering GSM_GetDateTime
Sat 2013/12/28 23:39:40: Getting date & time
Sat 2013/12/28 23:39:40: SENDING frametype 0x00/length 0x09/9
Sat 2013/12/28 23:39:40: 41A|54T|2B+|43C|43C|4CL|4BK|3F?|0D                              AT+CCLK?.       
Sat 2013/12/28 23:39:40: 1 "AT+CCLK?"
Sat 2013/12/28 23:39:40: 2 "ERROR"
Sat 2013/12/28 23:39:40: Checking line: ERROR
Sat 2013/12/28 23:39:40: AT reply state: 3
Sat 2013/12/28 23:39:40: RECEIVED frametype 0x00/length 0x13/19
Sat 2013/12/28 23:39:40: 41A|54T|2B+|43C|43C|4CL|4BK|3F?|0D |0A |0D |0A |45E|52R|52R|4FO AT+CCLK?....ERRO
Sat 2013/12/28 23:39:40: 52R|0D |0A                                                      R..             
Sat 2013/12/28 23:39:40: GSM_GetDateTime failed with error NOTSUPPORTED[21]: Function not supported by phone.
Sat 2013/12/28 23:39:40: Leaving GSM_GetDateTime
![screenshot from 2013-12-28 23 35 52](https://f.cloud.github.com/assets/6278138/1818507/d8d33692-7008-11e3-8fa4-2b11f98844f4.png)
![screenshot from 2013-12-28 23 34 27](https://f.cloud.github.com/assets/6278138/1818508/e42c2b3e-7008-11e3-952f-5ad3511fe63e.png)
![screenshot from 2013-12-28 23 42 17](https://f.cloud.github.com/assets/6278138/1818509/f7595704-7008-11e3-8ddf-3c2329366a33.png)
![screenshot from 2013-12-29 00 04 33](https://f.cloud.github.com/assets/6278138/1818535/1a5ce4de-700c-11e3-9acb-879c8054fd04.png)

**Comment by nijel** [comment]
Fixed in git.

**Comment by raresbaicu** [comment]
Hi!
Ok i will try to see if it handles ok, BUT NOT WRITE NOW :)


Rares Baicu 


     On Friday, March 20, 2015 5:03 PM, Michal Čihař <notifications@github.com> wrote:
   

 Fixed in git.—
