### ISSUE TITLE
SQL syntax error on Gammu 1.38.5

### ISSUE THREAD

**Issue by gustikpw** [gammu/gammu#375]
i have an Error, someboby help me please...

# Database backends congfiguration
host = smsd_odbc
user = root
password =
pc = localhost
database = smsd

# DBI configuration
driver = ODBC

gammu-smsd: SQLExecDirect failed, Code = -1, ODBC diagnostics:
gammu-smsd: 42000:1:1064:[MySQL][ODBC 5.3(w) Driver][mysqld-5.5.5-10.1.9-MariaDB]You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Signal) VALUES ("354429043141434", "510109162412535", "", "",

gammu-smsd: Post initialisation failed, stopping Gammu smsd: Error in executing SQL query. (SQL[79])
Failed to run SMSD: Error in executing SQL query.

**Comment by nijel** [comment]
Uee `sql= mysql` in the configuration file when using odbc, see https://wammu.eu/docs/manual/smsd/odbc.html#limitations

**Comment by gustikpw** [comment]
Very Thank full for your help.
