### ISSUE TITLE
SendingTimeOut in mysql is 10 minutes, unable to decrease

### ISSUE THREAD

**Issue by DavidMarekCZ** [gammu/gammu#383]
This is more like a feature request, or my stupidity - but in outbox when sis wasnt sent the "SendingTimeOut " is set to 10 minutes from now. In documentation i found out it shoud be 60 seconds, not 600:

UPDATE outbox SET SendingTimeOut = (NOW() + INTERVAL 60 SECOND) + 0
WHERE ID = %1 AND (SendingTimeOut < NOW() OR SendingTimeOut IS NULL)

Or is it somewhere else?
It would be nice to setup this in config of smsd, because I have no idea how to change it :)

**Comment by nijel** [comment]
Anyway I've added configuration option to customize that in 2eae286d0bbf21d2c76c4bda93a9c5a6e37daaa6.
