### ISSUE TITLE
1.39.0 - onincomingcall not working as expected

### ISSUE THREAD

**Issue by leonardpitzu** [gammu/gammu#390]
runonincomingcall triggers correctly - it correctly launches a test script which appends a timestamp to a file. The expected behaviour is for the script to be executed only once (write 1 timestamp to the test file). Instead every few seconds a timestamp is being written to the file.
Call is being correctly hang up very fast.
This has been so since the first release containing runonincomingcall.

short excerpt from log:
Wed 2018/02/14 21:42:06 gammu-smsd[4705]: Incoming call! # avail? 1 <phone_number>

Wed 2018/02/14 21:42:06 gammu-smsd[4705]: Incoming call! # hanging up @1518637326 0.

Wed 2018/02/14 21:42:06 gammu-smsd[4705]: Incoming call! # avail? 1 <phone_number>

Wed 2018/02/14 21:43:24 gammu-smsd[4705]: Call ended(6).

Wed 2018/02/14 21:43:24 gammu-smsd[6378]: Starting run on incoming call: /root/on_call.sh <phone_number>
Wed 2018/02/14 21:43:24 gammu-smsd[4705]: Process finished successfully
Wed 2018/02/14 21:43:24 gammu-smsd[4705]: Incoming call! # avail? 1 <phone_number>

Wed 2018/02/14 21:43:24 gammu-smsd[4705]: Incoming call! # hanging up @1518637404 0.

Wed 2018/02/14 21:43:24 gammu-smsd[4705]: Incoming call! # avail? 1 <phone_number>

Wed 2018/02/14 21:44:03 gammu-smsd[4705]: Call ended(6).

Wed 2018/02/14 21:44:03 gammu-smsd[4705]: Call ended(6).

Wed 2018/02/14 21:44:03 gammu-smsd[6461]: Starting run on incoming call: /root/on_call.sh <phone_number>
Wed 2018/02/14 21:44:03 gammu-smsd[4705]: Process finished successfully
Wed 2018/02/14 21:44:03 gammu-smsd[4705]: Incoming call! # avail? 1 <phone_number>

Wed 2018/02/14 21:44:03 gammu-smsd[4705]: Incoming call! # hanging up @1518637443 0.

Wed 2018/02/14 21:44:03 gammu-smsd[4705]: Incoming call! # avail? 1 <phone_number>

**Comment by leonardpitzu** [comment]
similar to #376

**Comment by toushin-taishi** [comment]
I would like to report that this is happening to me as well using Gammu version 1.39.0, but unlike leonardpitzu, not in endless loop. The number of script execution triggered by the RunOnIncomingCall parameter varies from one call to another. Sometimes 1, but most of the times 3, the maximum that I experience so far is 5 script executions.

I'm using a multi-modem configuration (5 modems).
Modem information:
Manufacturer : Wavecom
Model : MULTIBAND 900E 1800 (MULTIBAND 900E 1800)
Firmware : 641b09gg.Q2403A 1320676 061804 14:38

This is my gammu-smsd config:

[gammu]
device = /dev/ttyxxxx
connection= at115200
[smsd]
Service = sql
Driver = native_mysql
LogFile = /var/log/smsd/xxxx.log
User = xxxx
Password = xxxx
PC = localhost
Database = smsd
MaxRetries = 10
CheckBattery = 0
CheckSecurity = 0
DebugLevel = 1
HangupCalls = 1
DeliveryReport = log
PhoneID = xxxx
RunOnReceive = /usr/local/bin/runonreceive_per_msg.sh
RunOnIncomingCall = /usr/local/bin/runonreceive_per_call.sh

**Comment by melones** [comment]
Fixed in #459
