### ISSUE TITLE
USSD "Not Supported" on Wavecom M1306B

### ISSUE THREAD

**Issue by toni-ismail** [gammu/gammu#399]
Hi All,

I have a problem when I run USSD on gammu to check balance, there is return "Not Supported".
My Environment : 
- Windows 10 x64
-  Gammu 1.39.0

My Modem
Device               : COM4:
Manufacturer    : Wavecom
Model               : MULTIBAND  900E  1800 (MULTIBAND  900E  1800)
Firmware           : 652b09gg.Q2406A 428 052103 09:21
IMEI                  : 012345678901234
SIM IMSI           : 510018731661249

When I run `gammu getussd *123#` it show
`Press Ctrl+C to break...
USSD received
Status               : Not supported
Service reply        : ""`

this is the Log 
[gammulog.txt](https://github.com/gammu/gammu/files/1855867/gammulog.txt)

But when I trying to run from putty (direct AT command) it seems work.
![image](https://user-images.githubusercontent.com/5292780/38027533-23e58fc2-32ba-11e8-9351-09ea28254457.png)

Thanks for your help.

**Comment by toni-ismail** [comment]
When I try with Gammu 1.33.0, It's works. 
![image](https://user-images.githubusercontent.com/5292780/38065261-7adec65a-332c-11e8-8abb-dfb0006dc66f.png)


Maybe I'll change to Gammu 1.33 instead.
Thank you very much.

**Comment by toni-ismail** [comment]
Finally, when I'm change configuration and add `features=USSD_GSM_CHARSET` it's works.

config looks like that
![image](https://user-images.githubusercontent.com/5292780/38071973-7463b534-334e-11e8-8b60-20e740c8d9de.png)

The result like this
![image](https://user-images.githubusercontent.com/5292780/38071922-48eeef40-334e-11e8-80c3-7d7beab557cd.png)

And SMSD Inject works too, with additional config `features=USSD_GSM_CHARSET and CheckSecurity=0`

smsdrc config like this
![image](https://user-images.githubusercontent.com/5292780/38072038-d56c223a-334e-11e8-9bf9-27f4b69af1e2.png)
![image](https://user-images.githubusercontent.com/5292780/38072051-dfe28e3e-334e-11e8-838d-2c8591655e68.png)

And the result like this
![image](https://user-images.githubusercontent.com/5292780/38072082-05e131da-334f-11e8-9523-ea29264d963c.png)

Thank you very much.
Hope this help anyone who have same issue.

**Comment by vieckzand** [comment]
@toni-ismail It's work for me. Thank's for your solution

**Comment by adesurya** [comment]
Hy @toni-ismail  and @vieckzand.

I'm using Wavecom (syscom) q10 with firmware 652a09gg.Q2406B 244 112706 00:44.
I'm also got error like @toni-ismail . when i executed gammu ussd *888#, i received status Not Supported and Service Reply : "".

for configuration file, i already setting gammurc likethis

![image](https://user-images.githubusercontent.com/8553962/62186303-0447fd00-b390-11e9-8fc6-24bf0aa6237e.png)

When i add features=USSD_GSM_CHARSET, i got error when gammu identify.
anyone can help me?
