### ISSUE TITLE
Centos7 system is not functioning properly.

### ISSUE THREAD

**Issue by seohyunxian** [gammu/gammu#428]
I can't speak English。
Can only be roughly described.

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core)
Release:        7.5.1804
Codename:       Core

I can start the gammu-smsd service, but I can't access my device.
>gammu identify
Error opening device. Unknown,busy or no permissions.

Gammu service is normal if gammu-smsd service is turned off.
>systemctl stop gammu-smsd
>gammu identify
Device              : /dev/ttyACM0
manufacturer            : Nokia
model               : unknown (Nokia 5230)
firmware               : V ICPR72_11w16.1,28-07-11
IMEI                 : 351683053760821
SIM IMSI             : 460012865622787

gammu-smsdrc configure:

[gammu]
port = /dev/ttyACM0
connection = at19200
logfile = /var/log/gammu/gammu.log
logformat = textall

[smsd]
Service = files
InboxPath = /var/spool/gammu/inbox/
OutboxPath = /var/spool/gammu/outbox/
SentSMSPath = /var/spool/gammu/sent/
ErrorSMSPath = /var/spool/gammu/error/
InboxFormat = unicode
OutboxFormat = unicode
TransmitFormat = auto
debugLevel = 1
LogFile = /var/log/gammu/smsd.log
DeliveryReport = sms
DeliveryReportDelay = 7200
CheckSecurity = 0

Thank you for any help you give.

**Comment by seohyunxian** [comment]
>cat /var/log/gammu/smsd.log

Sun 2018/09/30 00:04:35 gammu-smsd[503]: Using FILES service
Sun 2018/09/30 00:04:35 gammu-smsd[503]: Configuring Gammu SMSD...
Sun 2018/09/30 00:04:35 gammu-smsd[503]: SHM token: 0x103440c (16991244)
Sun 2018/09/30 00:04:35 gammu-smsd[503]: Warning: No PIN code in /etc/gammu-smsdrc file
Sun 2018/09/30 00:04:35 gammu-smsd[503]: CommTimeout=30, SendTimeout=30, ReceiveFrequency=15, ResetFrequency=0, HardResetFrequency=0
Sun 2018/09/30 00:04:35 gammu-smsd[503]: checks: CheckSecurity=0, CheckBattery=1, CheckSignal=1, CheckNetwork=1
Sun 2018/09/30 00:04:35 gammu-smsd[503]: mode: Send=1, Receive=1
Sun 2018/09/30 00:04:35 gammu-smsd[503]: deliveryreport = sms
Sun 2018/09/30 00:04:35 gammu-smsd[503]: phoneid =
Sun 2018/09/30 00:04:35 gammu-smsd[503]: Inbox is "/var/spool/gammu/inbox/" with format "unicode"
Sun 2018/09/30 00:04:35 gammu-smsd[503]: Outbox is "/var/spool/gammu/outbox/" with format "unicode" and transmission format "auto"
Sun 2018/09/30 00:04:35 gammu-smsd[503]: Sent SMS moved to "/var/spool/gammu/sent/"
Sun 2018/09/30 00:04:35 gammu-smsd[503]: SMS with errors moved to "/var/spool/gammu/error/"
Sun 2018/09/30 00:04:35 gammu-smsd[517]: Created POSIX RW shared memory at 0x7fc3a9590000
Sun 2018/09/30 00:04:35 gammu-smsd[517]: Starting phone communication...
Sun 2018/09/30 00:20:44 gammu-smsd[517]: Stopping Gammu smsd: no error。 (NONE[1])
Sun 2018/09/30 00:20:44 gammu-smsd[517]: Terminating communication...

**Comment by kstuart** [comment]
I don't use CentOS, but you could run `journalctl -b -f` command in a second terminal, then issue your command in the other terminal to try and get more details on the issue.

You may need a udev rule, for example:
*/etc/udev/rules.d/50-nokia.rules*
```
ATTRS{idVendor}=="$$", ATTRS{idProduct}=="$$", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="$$", ATTRS{idProduct}=="$$", ENV{MTP_NO_PROBE}="1"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="$$", ATTRS{idProduct}=="$$", MODE:="0666"
KERNEL=="ttyACM*", ATTRS{idVendor}=="$$", ATTRS{idProduct}=="$$", MODE:="0666"
```
Replacing the **$$**'s with the vendor and product IDs from `journalctl`, `dmesg` or `lsusb`

If your nokia is a proper MTP device (unlikely) then you don't need the MTP_NO_PROBE line, ID_MM_DEVICE_IGNORE ensures the ModemManager ignores the device.

You can also run `udevadm control --reload` as root after adding rule, and re-plugin your device.

**Comment by sergiomb2** [comment]
are you using package from epel 7 ?

**Comment by seohyunxian** [comment]
@sergiomb2 
yes epel7 

>yum install gammu
