### ISSUE TITLE
GAMMU ODBC MS SQL error

### ISSUE THREAD

**Issue by serlev72** [gammu/gammu#431]
i just configure GAMMU on Windows with ODBC driver on Microsoft SQL server 2014

when i run gammu-smsd with configuration file there is this  error :

gammu-smsd: SQLExecDirect failed, Code = -1, ODBC diagnostics:
gammu-smsd: 42000:1:102:[Microsoft][ODBC SQL Server Driver][SQL Server]Syntaxe incorrecte vers '1'.

gammu-smsd: Table gammu not found, disconnecting!
gammu-smsd: Failed to open table gammu
gammu-smsd: Initialisation failed, stopping Gammu smsd: Error in executing SQL query. (SQL[79])
Failed to run SMSD: Error in executing SQL query.

I read the trace on ODBC driver and i've got this error in the SELECT

smsdrc          4220-1f90	ENTER SQLExecDirect 
		HSTMT               0x0000025AB46BAE90
		UCHAR *             0x000000EE16FAF420 [      -3] "SELECT  * FROM gammu  LIMIT 1\ 0"
		SDWORD                    -3

smsdrc          4220-1f90	EXIT  SQLExecDirect  with return code -1 (SQL_ERROR)
		HSTMT               0x0000025AB46BAE90
		UCHAR *             0x000000EE16FAF420 [      -3] "SELECT  * FROM gammu  LIMIT 1\ 0"
		SDWORD                    -3

		DIAG [42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Syntaxe incorrecte vers '1'. (102) 

can you help me ?

**Comment by serlev72** [comment]
problem solved

**Comment by muzamilindra** [comment]
> problem solved

I have the same case, using ODBC SQL server, may I see your sql string script in smsdrc?
