### ISSUE TITLE
Problem with delivery reports - gammu 1.4

### ISSUE THREAD

**Issue by docdave911** [gammu/gammu#452]
HI, I wonder if anyone can help me?  I am running gammu 1.4 under windows, with Huawei K4505. 

Great program, really useful, and all working just  fine, except for delivery reports - config file is:

# Delivery report configuration
deliveryreport = sms
deliveryreportdelay = 10

Messages sent with deliveryreport set to 'yes' as well.

But no sms are created, and when I try changing config to log, no entries in log file either.

Debug log shows that  SMS reports appear to be received, but not processed.... I have attached a full copy of  the report, but put in what seems to be the relevant section seems to be:

There seem to be quite alot of repeated actions in the full log, which might be normal (?) and no obvious errors....

If anyone can help me with this I would  be very grateful; I have done alot of searching, and delivery reports can be an issue, but I cant see where to go from here...

Many thanks.. David. 

Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Entering GSM_GetSMSStatus
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Getting SIM SMS status
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: SENDING frame type 0x00/length 0x12/18
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 22"|0D                                                          ".              
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 1 "AT+CPMS="SM","SM""
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 2 "+CPMS: 0,10,0,10,0,10"
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 3 "OK"
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Checking line: OK
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: AT reply state: 1
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: RECEIVED frame type 0x00/length 0x31/49
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|311|300|2C, "...+CPMS: 0,10,
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 300|2C,|311|300|2C,|300|2C,|311|300|0D |0A |0D |0A |4FO|4BK|0D  0,10,0,10....OK.
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 0A                                                              .               
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: SMS status received
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Parsing +CPMS: 0,10,0,10,0,10 with +CPMS: @i, @i, @0
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Parsed int 0
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Parsed int 10
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Used : 0
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Size : 10
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Getting phone SMS status
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: SENDING frame type 0x00/length 0x12/18
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 22"|0D                                                          ".              
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 1 "AT+CPMS="ME","ME""
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 2 "+CPMS: 0,16,0,16,0,10"
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 3 "OK"
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Checking line: OK
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: AT reply state: 1
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: RECEIVED frame type 0x00/length 0x31/49
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|311|366|2C, "...+CPMS: 0,16,
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 300|2C,|311|366|2C,|300|2C,|311|300|0D |0A |0D |0A |4FO|4BK|0D  0,16,0,10....OK.
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: 0A                                                              .               
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: SMS status received
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Parsing +CPMS: 0,16,0,16,0,10 with +CPMS: @i, @i, @0
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Parsed int 0
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Parsed int 16
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Used : 0
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Size : 16
Sun 2019/03/17 11:41:31 gammu-smsd: gammu: Leaving GSM_GetSMSStatus
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Entering GSM_GetSMSStatus
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Getting SIM SMS status
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: SENDING frame type 0x00/length 0x12/18
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 22"|0D                                                          ".              
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 1 "AT+CPMS="SM","SM""
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 2 "+CPMS: 0,10,0,10,0,10"
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 3 "OK"
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Checking line: OK
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: AT reply state: 1
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: RECEIVED frame type 0x00/length 0x31/49
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|53S|4DM|22"|2C,|22"|53S|4DM AT+CPMS="SM","SM
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|311|300|2C, "...+CPMS: 0,10,
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 300|2C,|311|300|2C,|300|2C,|311|300|0D |0A |0D |0A |4FO|4BK|0D  0,10,0,10....OK.
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 0A                                                              .               
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: SMS status received
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Parsing +CPMS: 0,10,0,10,0,10 with +CPMS: @i, @i, @0
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Parsed int 0
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Parsed int 10
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Used : 0
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Size : 10
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Getting phone SMS status
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: SENDING frame type 0x00/length 0x12/18
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 22"|0D                                                          ".              
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 1 "AT+CPMS="ME","ME""
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 2 "+CPMS: 0,16,0,16,0,10"
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 3 "OK"
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Checking line: OK
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: AT reply state: 1
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: RECEIVED frame type 0x00/length 0x31/49
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|2C,|22"|4DM|45E AT+CPMS="ME","ME
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 22"|0D |0D |0A |2B+|43C|50P|4DM|53S|3A:|20 |300|2C,|311|366|2C, "...+CPMS: 0,16,
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 300|2C,|311|366|2C,|300|2C,|311|300|0D |0A |0D |0A |4FO|4BK|0D  0,16,0,10....OK.
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: 0A                                                              .               
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: SMS status received
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Parsing +CPMS: 0,16,0,16,0,10 with +CPMS: @i, @i, @0
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Parsed int 0
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Parsed int 16
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Used : 0
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Size : 16
Sun 2019/03/17 11:41:46 gammu-smsd: gammu: Leaving GSM_GetSMSStatus

[smsdlog.txt](https://github.com/gammu/gammu/files/2975077/smsdlog.txt)

**Comment by docdave911** [comment]
Update: I think I have found the answer.  o2 network in uk does not support delivery reports, so have to force one by typing *0# before the text in the message. Iwill see if this work.s

**Comment by melones** [comment]
Issue resolved by author
