### ISSUE TITLE
gammu-1.40.0 deletesms fails with "The type of memory is not available or has been disabled".

### ISSUE THREAD

**Issue by kovinesinsila** [gammu/gammu#460]
Hello,

Ericsson N5321gw and F5521gw cards, both SM and ME memory:
`$ gammu getsms 2 3`
`Location 3, folder "Outbox", SIM memory`
`SMS message`
`Class                : 1`
`Coding               : Default GSM alphabet (no compression)`
`Remote number        : "1111"`
`Status               : UnSent`

`test`

`$ gammu deletesms 2 3`
`The type of memory is not available or has been disabled.`

Log: [gammu-1.40.0.txt](https://github.com/gammu/gammu/files/3065854/gammu-1.40.0.txt)
For comparison 1.39.0 log where it works: [gammu-1.39.0.txt](https://github.com/gammu/gammu/files/3065855/gammu-1.39.0.txt)

**Comment by grosjo** [comment]
Same issue here

**Comment by shining-fnml** [comment]
I confirm. My phone is a Huawei E352 running on Debian Buster and 1.40.0 is in the packaging system. I compiled from source both 1.39 and 1.41. The first can delete messages and the second can't

**Comment by ardelliery** [comment]
It's true I have the same problem on debian buster gammu 1.40.0 version with Huawei E169. 
I am no more able to delete SMS with python-gammu. Even the same message gammu.ERR_MEMORY_NOT_AVAILABLE: {'Text': 'The type of memory is not available or has been disabled.', 'Where': 'DeleteSMS', 'Code': 81}.
It did the job in a old version on rapsberry PI

**Comment by jwilk** [comment]
FWIW, `deleteallsms` still works.

**Comment by ardelliery** [comment]
> FWIW, deleteallsms still works.

True, command line gammu deleteallsms works but, I can not do it directly in my python code, and that's the problem, because it's an robot which responds automatically, and when sim is full the robot cannot do anymore it's job! If I interrupt the process to launch the os gammu deleteallsms command line, I risk to lose an arriving message. I would have preferred to delete the SMS one by one. 
If no solution is available, I will find a workaround!

**Comment by ocalvo** [comment]
I am hitting the same issue, I am using python-gammu and I cannot find a way to call DeleteAllSMS.
Has anyone find a workaround?

**Comment by ocalvo** [comment]
@nijel When is the next release of gammu?

**Comment by nijel** [comment]
I haven't scheduled one, but it's probably time to do that. I'll try to to it today.

**Comment by bohns** [comment]
I compiled 1.42 and tested this. It is still failing:

Fri 2020/10/23 11:11:23: [Gammu            - 1.42.0]
Fri 2020/10/23 11:11:23: [Connection       - "at19200"]
Fri 2020/10/23 11:11:23: [Connection index - 0]
Fri 2020/10/23 11:11:23: [Model type       - ""]
Fri 2020/10/23 11:11:23: [Device           - "/dev/ttyUSB1"]
Fri 2020/10/23 11:11:23: [Running on       - Linux, kernel 5.4.51-v7l+ (#1333 SMP Mon Aug 10 16:51:40 BST 2020)]
Fri 2020/10/23 11:11:23: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Fri 2020/10/23 11:11:23: Setting speed to 19200
Fri 2020/10/23 11:11:23: [Module           - "auto"]

...
Fri 2020/10/23 11:11:27: Entering GSM_DeleteSMS
Fri 2020/10/23 11:11:27: Location = 1, Folder = 0
Fri 2020/10/23 11:11:27: SMS folder 0 & location 1 -> ATGEN folder 1 & location 1
Fri 2020/10/23 11:11:27: Requested memory not available for reading: XX (-1238362640)
Fri 2020/10/23 11:11:27: GSM_DeleteSMS failed with error MEMORY_NOT_AVAILABLE[81]: The type of memory is not available or has been disabled.
Fri 2020/10/23 11:11:27: Leaving GSM_DeleteSMS

**Comment by kstuart** [comment]
@bohns as a sanity check could you please test with the gammu program `deletesms` command to verify that works for you.

**Comment by bohns** [comment]
@kstuart Which release of gammu would you like me to try this on? 

I fell back to 1.38 because it was functional.

**Comment by kstuart** [comment]
@bohns, with current 1.42 release please, this is working on my system but I may be the only person to have tested. If it doesn't work please set your config `debuglevel` to 255 and attach the full log for that run (please attach it and not paste it as a comment).

If anyone else is also able to test this please do.

**Comment by bohns** [comment]
@kstuart I reinstalled 1.42 and yes, the gammu program deletesms does work.

**Comment by kstuart** [comment]
@bohns that's great, thanks for testing it.

**Comment by vcrasmariu** [comment]
Hello,

I'm experiencing the same problem with gammu v1.40 on Raspbian BUSTER (HW is: Raspberry Pi 4). Currently, there is no update available through APT.
Do you guys have a standalone compiled v1.42 that I can use?

Thank you.

Kind regards,
Victor

**Comment by ocalvo** [comment]
I am seeing this issue still hitting.

**Comment by kstuart** [comment]
@ocalvo the issue appears to be in the python bindings though, not gammu itself, are you aware of  gammu/python-gammu/issues/39

**Comment by ocalvo** [comment]
> @ocalvo the issue appears to be in the python bindings though, not gammu itself, are you aware of [gammu/python-gammu/issues/39](https://github.com/gammu/python-gammu/issues/39)

Thanks so much for the link, I have confirmed that in fact this is a problem in python-gammu, I have created a PR with the [fix](https://github.com/gammu/python-gammu/pull/45)

**Comment by eve-kendall** [comment]
Hello,
I try me too, to delete SMS with python3 and python3-gammu 3.2.4-1, but I can't do it.

I resume my problems : 
- I am on debian bulleyes and use : gammu 1.42.0-5 -- libgsmsd8 1.42.0-5 and python3-gammu 3.2.4-1.
- I can extract all informations from modem gsm with gammu in command line and with python3-gammu with python code.
- I can send sms with gammu in command line and with python3-gammu with python code.
- I can delete sms with gammu in command line (gammu deleteallsms 3)
- But I can't delete sms with python3-gammu with python code.
- The documentation python3-gammu seems to be clear but it don't work. Parameters to get messages and delete seems to be the same like in documentation (Location=0, Folder=3).
I see on github the post : https://github.com/gammu/python-gammu/issues/39 and the quick "attempt to fix python-gammu" from kstuart but I don't understand how to correct the "gammu.c"
If you have some free time to tell me how to do it, thank you in advance

![sm-GetNextSMS-sm-DeleteSMS](https://user-images.githubusercontent.com/104782415/166269920-fb1feae7-9114-4f6c-bbae-193d8653bbf0.png)
