### ISSUE TITLE
SMS sometimes not delivered

### ISSUE THREAD

**Issue by alrf** [gammu/gammu#48]
System:
Description:    Ubuntu 12.04.3 LTS
Release:        12.04
Codename:       precise

Gammu+Gammu-SMSD version 1.31.0

SMSD config (/etc/gammu-smsdrc):
```
[gammu]
port = /dev/ttyUSB3
connection = at
logformat = textall
CheckSecurity = 0
[smsd]
CheckSecurity = 0
TransmitFormat = unicode
LogFile = /var/log/gammu-smsd
debuglevel = 1

Service = SQL
Driver = native_pgsql
User = user
Password = pw
Host = localhost:5432
Database = smsd
```

My GSM-modem:
Manufacturer : huawei
No flags section in the config file.
Model        : E171
Product name : E171
Revision     : 21.156.00.00.143

Description problem:
I send sms on gsm-modem number, sms can be delivered (and have record in DB, all ok!) but sometimes sms not delivered (I'm not getting SMS delivery report, also no record in DB with this sms). After a while SMS can reach, but sometimes need insert SIM into telephone (and sms will be delivered) and after that insert back into GSM-modem..
I have this in my smsd-log:
```
Fri 2014/04/04 10:32:23 gammu-smsd[29626]: Received message from: +7<my_number>
Fri 2014/04/04 10:32:23 gammu-smsd[29626]: Read 1 messages
Fri 2014/04/04 10:32:23 gammu-smsd[29626]: Inserted message id 35
Fri 2014/04/04 10:46:02 gammu-smsd[29626]: Error getting SMS status: Unknown response from phone. See <http://wammu.eu/support/bugs/> for information how to report it. (UNKNOWNRESPONSE[16])
Fri 2014/04/04 10:48:30 gammu-smsd[29626]: Received message from: +7<my_number>
Fri 2014/04/04 10:48:30 gammu-smsd[29626]: Read 1 messages
Fri 2014/04/04 10:48:30 gammu-smsd[29626]: Inserted message id 36
```

Unknown response from phone - I think, this is in moment when sms can't be delivered..

**Comment by nijel** [comment]
It's hard to tell what went wrong without debug log, please see http://wammu.eu/support/bugs/ for information how to obtain it.
