### ISSUE TITLE
Error insert sentitems, conection odbc pgsql

### ISSUE THREAD

**Issue by ideat** [gammu/gammu#504]
Mon 2019/11/25 05:14:55 gammu-smsd: Execute SQL: INSERT INTO sentitems ("CreatorID", "ID", "SequencePosition", "Status", "SendingDateTime", "SMSCNumber", "TPMR", "SenderID", "Text", "DestinationNumber", "Coding", "UDH", "Class", "TextDecoded", "InsertIntoDB", "RelativeValidity", "StatusCode")  VALUES ('admin', '1', 1, 'SendingOKNoReport', now(), '+59170700000', 6, '', '0048006F006C00610020006A006F0073006500200073006F006E00200031003A0031003400200061006D', '60700381', 'Default_No_Compression', '', -1, 'Hola jose son 1:14 am', '{ ts \'2023-05-25 11:28:52\' }', 255, -1)
Mon 2019/11/25 05:14:55 gammu-smsd: SQLExecDirect failed, Code = -1, ODBC diagnostics:
Mon 2019/11/25 05:14:55 gammu-smsd: 42601:1:1:ERROR: syntax error at or near "2023";
Error while executing the query

**Comment by melones** [comment]
Hi @ideat , 
Did you happen to resolve this issue?

**Comment by melones** [comment]
No response from user.
