### ISSUE TITLE
Any cdma modern works fine with gammu?i I tried EC121,EC122 but not work

### ISSUE THREAD

**Issue by andyhuai** [gammu/gammu#511]
I have a cdma phone card, ande I bought EC121,EC122, but not work with gammu.

any suggest device can work fine with cdma ?

**Comment by melones** [comment]
Hi, 
Cdma networks usually use 3GPP2 standard for SMS encoding. See the specification 3GPP2 C.S0015-B for more details. Gammu use 3GPP standards for SMS and at the moment it doesn't support 3GPP2 SMS
