### ISSUE TITLE
error when build

### ISSUE THREAD

**Issue by gemaalief** [gammu/gammu#519]
hi there, 
i'm trying to build gammu with cmake, and i came to this error

> [ 76%] Building C object tests/CMakeFiles/sql-parse-date.dir/sql-parse-date.c.o
In file included from /Users/gemaalief/Documents/work/c/gammu/tests/sql-parse-date.c:8:
In file included from /Users/gemaalief/Documents/work/c/gammu/tests/../smsd/services/sql.h:6:
In file included from /Users/gemaalief/Documents/work/c/gammu/tests/../smsd/services/../core.h:15:
/Users/gemaalief/Documents/work/c/gammu/tests/../smsd/services/../services/sql-core.h:34:10: error: 'sql.h' file not found with <angled> include; use "quotes" instead
#include <sql.h>
         ^~~~~~~
         "sql.h"
/Users/gemaalief/Documents/work/c/gammu/tests/../smsd/services/../services/sql-core.h:35:10: fatal error: 'sqlext.h' file not found
#include <sqlext.h>
         ^~~~~~~~~~
2 errors generated.
make[2]: *** [tests/CMakeFiles/sql-parse-date.dir/sql-parse-date.c.o] Error 1
make[1]: *** [tests/CMakeFiles/sql-parse-date.dir/all] Error 2
make: *** [all] Error 2

i already have sql.h and sql.ext on my /usr/local/include

> lrwxr-xr-x   1 gemaalief  admin    50 Feb 28 06:53 msodbcsql17 -> ../Cellar/msodbcsql17/17.5.1.1/include/msodbcsql17
lrwxr-xr-x   1 gemaalief  admin    40 Feb 28 05:52 mysql -> ../Cellar/mysql@5.6/5.6.47/include/mysql
lrwxr-xr-x   1 gemaalief  admin    38 Feb 28 06:34 sql.h -> ../Cellar/unixodbc/2.3.7/include/sql.h
lrwxr-xr-x   1 gemaalief  admin    39 Apr 18  2019 sqldb.h -> ../Cellar/freetds/1.1.4/include/sqldb.h
lrwxr-xr-x   1 gemaalief  admin    41 Feb 28 06:34 sqlext.h -> ../Cellar/unixodbc/2.3.7/include/sqlext.h
lrwxr-xr-x   1 gemaalief  admin    42 Apr 18  2019 sqlfront.h -> ../Cellar/freetds/1.1.4/include/sqlfront.h
lrwxr-xr-x   1 gemaalief  admin    41 Feb 28 06:34 sqlspi.h -> ../Cellar/unixodbc/2.3.7/include/sqlspi.h
lrwxr-xr-x   1 gemaalief  admin    43 Feb 28 06:34 sqltypes.h -> ../Cellar/unixodbc/2.3.7/include/sqltypes.h
lrwxr-xr-x   1 gemaalief  admin    43 Feb 28 06:34 sqlucode.h -> ../Cellar/unixodbc/2.3.7/include/sqlucode.h

can you help me with this? thank you

**Comment by yarmooh** [comment]
Hi @gemaalief 
> error: 'sql.h' file not found with include; use "quotes" instead
Haven't you changed anything in the cloned files? Please remove repo, and re-clone again.

**Comment by gemaalief** [comment]
i didn't change anything, it work now when building without ODBC
