### ISSUE TITLE
Message Rec Issues

### ISSUE THREAD

**Issue by geethupendra** [gammu/gammu#524]
Hello,

I have an issue with receiving a message like (0Ë ?õUùê) this and stuck the dongle, is there a way to flushed.

Thanks
Geeth

**Comment by melones** [comment]
Please use command:
```
gammu deletesms folder start [stop]
or
gammu deleteallsms folder

```
The syntax description for those commands can be found [here](https://wammu.eu/docs/manual/gammu/)
