### ISSUE TITLE
gammu-smsd works only when i do a service stop/start, why?

### ISSUE THREAD

**Issue by Elrick91** [gammu/gammu#526]
Good morning, everyone,

I installed and configured GammuSMSD 1.40.0-1 on a Debian Buster distribution.
When I use the following commands I get no results while the service is started:

root@Jeedom:~# nano /etc/gammu-smsdrc
root@Jeedom:~# sudo service gammu-smsd start
root@Jeedom:~# echo "Test tutoandco" | gammu-smsd-inject TEXT 06XXXXXXX
(Hidden phone number)

I have to make a stop/start to receive the message on my mobile phone:
root@Jeedom:~# sudo service gammu-smsd stop
root@Jeedom:~# sudo service gammu-smsd start

My orders to send are never taken into account even though the service is started, do you know where this problem comes? How can I fix it?

I also use the Jeedom application on this distribution but the 4G dongle is not set to use it for the moment.
I plan to use it once I've solved the above problem.
Do you know if the GammuSMSD application and Jeedome will be able to use my 4G dongle without any problem?

Thank you in advance for your help.

UPDATE : The problem was due to Jeedom with plugin SMS. > SOLVED!

**Comment by melones** [comment]
Problem solved by the user. Issue is closed.

> UPDATE : The problem was due to Jeedom with plugin SMS. > SOLVED!
