### ISSUE TITLE
inbox SMS is not put into DB/PgSQL with Dummy driver

### ISSUE THREAD

**Issue by tenzap** [gammu/gammu#531]
Hello,

I use the dummy driver to do some tests with kalkun

I try to add a message into the inbox of the "phone" (dummy driver in fact) using py-Gammu

If I use the "files" storage backend, the messages are well saved in the local directory and removed from the "phone".
However, if I use a postgresql db, the SMS's don't enter the DB, although they are removed from the "inbox" folder on the "dummy-phone"

With the Postgresql driver, according to the gammu-smsd logs the SMS are well read, but there is no SQL INSERT query in the log.

**Python**
```
import gammu
import sys

# Create state machine object
sm = gammu.StateMachine()

# Read ~/.gammurc
sm.ReadConfig(Filename="/etc/gammu-smsdrc")
# Connect to phone
sm.Init()

messageTest = {
    'Text': 'python-gammu testing message',
    'SMSC': {'Location': 1},
    'Number': '+33611111111',
    'Folder': 1,
}
sm.AddSMS(messageTest)
sm.GetSMS(1,1)
```
Output is as follows (since `'InboxFolder': 1` it means the message is really in an InboxFolder, moreover since it does work with the files backend, the problem is unlikely to be the message)
```
[{'RejectDuplicates': 0, 'SMSCDateTime': datetime.datetime(2020, 4, 25, 17, 15, 56), 'Class': -1, 'Name': u'', 'InboxFolder': 1, 'Text': u'python-gammu testing message', 'SMSC': {'DefaultNumber': u'', 'Format': 'Text', 'Number': u'', 'Validity': 'Max', 'Location': 0, 'Name': u''}, 'ReplaceMessage': 0, 'Coding': 'Default_No_Compression', 'Number': u'+33611111111', 'DateTime': datetime.datetime(2020, 4, 25, 17, 15, 56), 'DeliveryStatus': 0, 'State': 'UnSent', 'MessageReference': 0, 'Length': 28, 'Location': 10001, 'Memory': 'SM', 'ReplyViaSameSMSC': 0, 'UDH': {'Text': '', 'ID16bit': -1, 'AllParts': -1, 'ID8bit': -1, 'PartNumber': -1, 'Type': 'NoUDH'}, 'Type': 'Submit', 'Folder': 1}]
```

**/etc/gammu-smsdrc**
```
[gammu]
model = dummy
connection = none
device = /home/****/gammu-dummy
port=/home/****/gammu-dummy
name=

[smsd]
service = SQL
driver = native_pgsql
host = localhost
database = kalkun
user = ****
password = ****

;service = files
;InboxPath=/tmp/
;OutboxPath=/tmp/

Receive = true

logfile = /root/gammu-smsd.log
DebugLevel = 255
```

**gammu-smsd.log** are attached. One using "Files" & one using "SQL"

BTW, I don't understand why when using SQL it always makes a SELECT... FROM **outbox**

[gammu-smsd.log-file.txt](https://github.com/gammu/gammu/files/4533349/gammu-smsd.log-file.txt)
[gammu-smsd.log-psql.txt](https://github.com/gammu/gammu/files/4533350/gammu-smsd.log-psql.txt)

Problem is also with 1.41.0

Edit: With a real phone (sony ericsson) configured with AT connection, reception of a SMS sent to myself does actually fill the database into the "inbox" table.

**Comment by tenzap** [comment]
Seems like adding this line to the Message does the trick with dummy driver
`'Type': 'Deliver',`
```
messageTest = {
    'Text': 'python-gammu testing message',
    'SMSC': {'Location': 1,},
    'Number': '+33611111111',
    'Folder': 1,
    'Type': 'Deliver',
}
```
I leave this open since I don't know if this is normal or not.

**Comment by melones** [comment]
Resolved by user.
