### ISSUE TITLE
Cannot connect to Samsung SGH-B320: "Unknown model type string. Check config file."

### ISSUE THREAD

**Issue by Gymnasiast** [gammu/gammu#535]
OS: Ubuntu 20.04, AMD64
Gammu version: 1.41.0-1 

Relevant section of .gammurc:
```
[gammu1]
device = 00:23:3A:F4:06:E4
model = SGH-B320
name = Jupiter
connection = blueat
synchronizetime = no
logfile =
logformat = nothing
use_locking =
gammuloc =
```

Attempted commands:
```
michael@Marcus-Aurelius:~$ gammu --section 1 --identify
Unknown model type string. Check config file.
michael@Marcus-Aurelius:~$ gammu 1 text --identify
Unknown model type string. Check config file.
```

I have tried connecting to this phone, both through Wammu and through Gammu directly. Most attempts result in this message, changing `blueat` to `bluefbus` results in a message saying my phone does not support this.

My computer could pair with the phone no problem. Connecting to one of my other phones (Nokia 6230i) was not a problem either.

I hope I have provided enough information. I will gladly provide more if needed.

**Comment by melones** [comment]
I understand that you are you trying to connect via Bluetooth. Can you first try a connection via USB cable?

**Comment by Gymnasiast** [comment]
Unfortunately, this phone does not seem to have come with one. It has a proprietary USB connection, so I cannot use a standard one either.

**Comment by melones** [comment]
Your phone model is not on the [list of supported phones](https://wammu.eu/phones/). That it why you get "Unknown model type" error. 

You may try to put a different model name in gammu config that is similar to yours, but it won't guarantee it will work.

**Comment by Gymnasiast** [comment]
I see. How can I find what I need to specify exactly? For example, if I wanted to override the model to a "Samsung SGH-B510", would I then put
`model = SGH-B510`
or
`model = "Samsung SGH-B510"`? Is there is a list of supported `model =` string I can check?

**Comment by melones** [comment]
Please create a new entry for your phone here: https://wammu.eu/phones/new/
