### ISSUE TITLE
When receivers phone is off stuck SMS

### ISSUE THREAD

**Issue by jvalters** [gammu/gammu#537]
Hello, I'm using gammu-smsd-inject with configuration all works perfectly, but now I have a problem, that I don't know, how to resolve. 

When sending an SMS to a mobile phone, that is on a different network and if the mobile phone is turned off, our SMS gets stuck and it doesn't send any other SMS.
Gmmu configuration:
`[gammu]
port = /dev/ttyUSB1
connection = AT
speed = 9600

[smsd]
# MySQL Connection
service = sql
driver = native_mysql
host = 127.0.0.1
user = dbuser
password = dbpass
database = dbname
# SMSD configuration, see gammu-smsdrc(5)
[smsd]
OutboxFormat = unicode
TransmitFormat = unicode
PIN = 0000
RetryTimeout = 1
MultipartTimeout = 2
MaxRetries = 1
ResetFrequency = 4
HardResetFrequency = 20
DeliveryReport = sms
DeliveryReportDelay = 30
PhoneID = first
logfile = /var/log/sms_log
debuglevel = 255
StatusFrequency = 0
CommTimeout = 2
SendTimeout = 1
HangupCalls = 1
LoopSleep = 0
CheckSecurity = 0
`

Can you please advise, how can I resolve this problem or how to unstuck?
The error that I see is: "+CMS ERROR: 38 "

**Comment by melones** [comment]
Hi, 
Please provide a log file that shows your problem.

**Comment by melones** [comment]
No log provided. It's impossible to investigate the case further.
