### ISSUE TITLE
wammu tries an inappropriate ioctl on usb port on fedora 20

### ISSUE THREAD

**Issue by peterjbay** [gammu/gammu#54]
Here will appear debug messages from Gammu...
Sun 2014/07/06 16:03:39: [Gammu            - 1.33.0 built 02:27:50 Sep  8 2013 using GCC 4.8]
Sun 2014/07/06 16:03:39: [Connection       - "at"]
Sun 2014/07/06 16:03:39: [Connection index - 0]
Sun 2014/07/06 16:03:39: [Model type       - ""]
Sun 2014/07/06 16:03:39: [Device           - "/dev/phone"]
Sun 2014/07/06 16:03:39: [Running on       - Linux, kernel 3.14.9-200.fc20.x86_64 (#1 SMP Thu Jun 26 21:40:51 UTC 2014)]
Sun 2014/07/06 16:03:39: [System error     - tcgetattr in serial_open, 25, "Inappropriate ioctl for device"]
Sun 2014/07/06 16:03:39: Init:GSM_TryGetModel failed with error DEVICEOPENERROR[2]: Error opening device. Unknown, busy or no permissions.
Sun 2014/07/06 16:03:39: Entering GSM_SetIncomingSMS
Sun 2014/07/06 16:03:39: Entering GSM_SetIncomingCall
Sun 2014/07/06 16:03:39: Entering GSM_SetIncomingCB
Sun 2014/07/06 16:03:39: Entering GSM_SetIncomingUSSD

**Comment by nijel** [comment]
What device do you try to connect to?

**Comment by sergiomb2** [comment]
Fedora user please use official rpms , that I had packaged 

    dnf install gammu python-gammu wammu
