### ISSUE TITLE
[bug] No way to set SMSC due to "Empty entry"

### ISSUE THREAD

**Issue by kopax** [gammu/gammu#541]
Hi, I have the following:

```bash
kopax@master-letort-01:~$ gammu getsmsc 1 
Empty entry.
kopax@master-letort-01:~$ gammu setsmsc 1 "+33695000695"
Empty entry.
kopax@master-letort-01:~$ gammu setsmsc 2 "+33695000695"
Invalid location. Maybe too high?
kopax@master-letort-01:~$ gammu setsmsc 3 "+33695000695"
Invalid location. Maybe too high?
kopax@master-letort-01:~$ gammu setsmsc 0 "+33695000695"
Error: Invalid SMSC location: 0
kopax@master-letort-01:~$ gammu setsmsc 1 "+33695000695"
Empty entry.
kopax@master-letort-01:~$ gammu setsmsc 1 '+33695000695'
Empty entry.
kopax@master-letort-01:~$ gammu setsmsc 1 '"+33695000695"'
Empty entry.
```

The smsc is required for sending sms with my sim card. **It work fine** with `mmcli` since I can pass the `smsc` when sending the message `mmcli -m 0 --messaging-create-sms="text='Hello world',number='+336xxxxxx89',smsc='+33695000695'" -v`, but with gammu it fail because the `setsmsc` program seems broken.

I use gammu 1.40.0, do you have an idea what is going ?

Thank you for helping to unlock the situation with gammu

**Comment by kopax** [comment]
I was able to send the sms using `echo "Hello world" | gammu sendsms TEXT +336XXXXXX99 -smscnumber +33695000695`, but this cause issue to use a default, and running service such as https://github.com/pajikos/sms-gammu-gateway is not possible.

Do you have a clue on how I can set smsc on my sim card?

**Comment by melones** [comment]
You may try to set SMSC number with AT command before running gammu. Just create a short script which would send 
AT+CSCA="+33695000695"

and it should fix your problem.
