### ISSUE TITLE
Nokia 6133 Unknown Model

### ISSUE THREAD

**Issue by n8henrie** [gammu/gammu#57]
I am trying to get my [Nokia 6133](http://www.gsmarena.com/nokia_6133-1736.php) to work with Gammu, but I'm not having much luck. I'm primarily using a CA-53 cable (should be DKU2 compatible), but have also tried with blueotooth.

My main goal is to be able to send and receive SMS as a daemon. I'm sure it's possible, because I have it working in Gnokii (using `dku2libusb`), but I'd prefer the more robust environment of Gammu.

I can get `gamma --identify` to work with `connection = at`. 

```
Device               : /dev/ttyACM0
Manufacturer         : Nokia
Model                : unknown (Nokia 6133)
Firmware             : V 05.60,17-11-06
IMEI                 : REDACTED
SIM IMSI             : REDACTED
```

using this config:

```
model = 6133
connection = at                                                                                                                                                                                                
synchronizetime = yes
logfile = gammu_log.txt
logformat = textalldate
use_locking =
gammuloc =
```

Though obviously the logs show: `Configured model 6133 is not known, retrying with auto detection!`

However, I don't think the `at` mode will let me access the SMS messages, since I can't even get them using at commands directly, e.g. `screen /dev/ttyACM0` and `AT+CMGL`, etc. So instead, I'm trying using both `fbususb` and `dku2` connections (I have `libusb-1.0.0-dev` installed). However, I'm having no luck there, either.

Also, as the Nokia 6131 appears to be essentially identical to the 6133, I've tried using that as the model.

config:

```
# port = /dev/ttyACM0
# device = /dev/ttyACM0
# model = 6133
connection = fbususb                                                                                                                                                                                           
synchronizetime = yes
logfile = gammu_log.txt
logformat = textalldate
use_locking =
gammuloc =
```

`gammu --identify` -> `Unknown model type string. Check config file.`

Log:

```
Wed 2014/09/17 10:45:07: WARNING: phone not known, please report it to authors (see <http://wammu.eu/support/bugs/>). Thank you.
Wed 2014/09/17 10:45:07: Init:GSM_RegisterAllPhoneModules failed with error UNKNOWNMODELSTRING[19]: Unknown model type string. Check config file.
```

If I uncomment the model it is the same -- unknown model string.

If I change the model to `6131` and try again, I get:

```
Device               : /dev/ttyACM0
Manufacturer         : Nokia
Model                : unknown (RM-126)
Firmware             : 05.60 M (17-11-06)
Hardware             : 8009
IMEI                 : REDACTED
Can not access SIM card.
```

which looks promising, but when I try `gammu --getallsms` it seems to lock up. I see  `Frame not request now. If you can, please report it (see <http://wammu.eu/support/bugs/>). Thank you` in the logs, then a bunch of stuff like:

```
10:49:00: Failed to read from usb (-7)!
Wed 2014/09/17 10:49:00: Operation timed out
Wed 2014/09/17 10:49:01: Failed to read from usb (-7)!
Wed 2014/09/17 10:49:01: Operation timed out
Wed 2014/09/17 10:49:01: RECEIVED frametype 0x0A/length 0x06/6
Wed 2014/09/17 10:49:01: 01 |81 |00 |1E |40@|5B[                                         ....@[          
Wed 2014/09/17 10:49:01: Network level changed to: 64
Wed 2014/09/17 10:49:02: RECEIVED frametype 0x0A/length 0x06/6
Wed 2014/09/17 10:49:02: 01 |81 |00 |1E |3F?|5B[                                         ....?[          
Wed 2014/09/17 10:49:02: Network level changed to: 63
Wed 2014/09/17 10:49:03: RECEIVED frametype 0x0A/length 0x06/6
```

Repeats endlessly.

If I change the connection to `dku2`, I get the same thing, with a bunch of 

```
Wed 2014/09/17 10:51:07: Failed to read from usb (-7)!
Wed 2014/09/17 10:51:07: Operation timed out
```

messages. At either `dku2` or `fbususb`, at the top of the log is something promising:

```
Wed 2014/09/17 10:50:23: Trying to open device, config=1, c_iface=11, c_alt=0, d_iface=12, d_alt=1
Wed 2014/09/17 10:50:23: Configuration change not required, unhooking only required interfaces!
Wed 2014/09/17 10:50:23: Claiming USB control interface...
Wed 2014/09/17 10:50:23: Configuring USB control interface...
Wed 2014/09/17 10:50:23: Claiming USB data interface...
Wed 2014/09/17 10:50:23: Configuring USB data interface...
Wed 2014/09/17 10:50:23: Connected!
```

One thing I've noticed is that with Gnokii, to work I have to specify memory type `IN` to work, I can't use `ME` or `SM`, perhaps that has something to do with it?

Thanks for any help!

**Comment by lukyrys** [comment]
I have same problem, with Nokia 6230 (dku2phonet) 
Gammu version 1.36.3

**Comment by nijel** [comment]
@lukyrys please open separate issue for that with debug log snippets.

**Comment by lukyrys** [comment]
@nijel Yes, thanks, I opened it #118
