### ISSUE TITLE
Samsung GT-B2710 not recognized

### ISSUE THREAD

**Issue by ghost** [gammu/gammu#6]
Hi, when I try to connect my Samsung-Phone with wammu I always get this bug:
Sie haben keine Rechte für das Gerät /dev/ttyACM0! Vielleicht müssen Sie Mitglied der Gruppe dialout sein
You have no rights for the machine /dev/ttyACM0! Maybe you have to be member of the group dialout.
It also happens, when I restart the phone and unlock the SIM via wammu. How can I fix it?

**Comment by Armagetron** [comment]
Sorry for posting here again but I cannot get my B2710 to work.

I connect it to my computer via USB and let wammu run an auto-detection. However when I try to fetch the messages from the phone wammu freezes and I have to kill the process. Can someone point out how to configure it correctly?
