### ISSUE TITLE
SMS not sent OK, error code probably 1

### ISSUE THREAD

**Issue by Sig2018** [gammu/gammu#624]
That is one of the error messages I got when trying to send and SMS in gammu-smsd. SMS doesn't go out.
I'm running Gammu 1.4 on Peppermint 10 (Ubuntu)
Connection is with Nokia 6131 using Bluetooth.
But the curious thing is the SMS's are sent when I use Wammu and the same phone
Please check the complete log below and see if you can help me in some way.
Thank you!

gammu: Entering   GSM_SendSMS
gammu: Recipient number   "xxxxxxxxxxx"
gammu: SMSC number   "+xxxxxxxxxx"
gammu: SMS class -1
gammu: SMS validity ff
gammu: TPMR: 00 0
gammu: 7 bit SMS, length 29, 33
gammu: Hi u there, good morning!! @admin
gammu: Sending sms
gammu: SENDING frame type 0x02/length   0x57/87
gammu: 00 \|01 \|00 \|02 \|00 \|00 \|00   \|55U\|55U\|01 \|02 \|4DM\|311\|00 \|00 \|00    .......UU..M1...
gammu: 00 \|04 \|82 \|10 \|01 \|08 \|0B \|81   \|65e\|79y\|15 \|333\|27'\|F2 \|00 \|00    ........ey.3'...
gammu: 00 \|00 \|82 \|10 \|02 \|07 \|06 \|91   \|65e\|19 \|06 \|300\|70p\|00 \|00 \|00    ........e..0p...
gammu: 00 \|00 \|08 \|04 \|01 \|FF \|80 \|23#\|1D   \|21!\|C8 \|344\|A8 \|0E \|A2 \|A3    .......#.!.4....
gammu: CB \|F2 \|322\|0B \|74t\|7E~\|BF \|C9 \|A0   \|F6 \|5B[\|EE \|4EN\|BB \|CF \|A1    ..2.t~....[.N...
gammu: 10 \|08 \|10 \|26&\|B7 \|D3   \|6En                                       ...&..n
gammu: Leaving GSM_SendSMS
gammu: RECEIVED frame type 0x02/length   0x0A/10
gammu: 01 \|82 \|00 \|22"\|02 \|1D \|01   \|01 \|01 \|00                            ..."......
gammu: Ignoring cell broadcast fail event
gammu: RECEIVED frame type 0x0A/length   0x06/6
gammu: 01 \|81 \|00 \|20 \|00 \|00                                          ...   ..
gammu: None answer
gammu: RECEIVED frame type 0x0A/length   0x06/6
gammu: 01 \|81 \|00 \|20 \|01 \|00                                          ...   ..
gammu: None answer
gammu: RECEIVED frame type 0x02/length   0x0E/14
gammu: 01 \|82 \|00 \|03 \|00 \|01 \|0C \|08 \|01   \|26&\|1D \|00 \|00 \|00            .........&....
gammu: SMS not sent OK, error code   probably 1
SMS sent on device:   "00:1A:DC:43:C1:2E" status=1, reference=29
gammu: RECEIVED frame type 0x02/length   0x0A/10
gammu: 01 \|82 \|00 \|22"\|03 \|1D \|01   \|01 \|01 \|00                            ..."......
gammu: Ignoring cell broadcast fail event
Error getting send status of message:   Unknown error. (UNKNOWN[27])

**Comment by wcypierre** [comment]
> Error getting send status of message: Unknown error. (UNKNOWN[27])

based on this, you can refer to this issue https://github.com/gammu/gammu/issues/416 

You can try to move the file with issue from outbox to error folder and restart gammu smsd again

Common setup for linux would be 
mv /var/spool/gammu/outbox/<filename> /var/spool/gammu/error

**Comment by Sig2018** [comment]
@wcypierre thank you for your replay.
I already saw that post but it doesn't seem like my problem.
I found a very basic mistake. the  "+" before SMS number. I was almost sure I tried before but now it is working. 
Now my problem is with Incoming SMS but I will open a new isue.

**Comment by Roy-Orbison** [comment]
I sometimes get this issue even on well-formed numbers, the network just doesn't like them. I have a script run on a cron job that checks the last line of the **systemd** service:
```sh
journalctl --unit gammu-smsd --quiet --output=cat --reverse --lines=1
```
If that output contains the string `UNKNOWN[27]`, I just move the stuck message to error, as @wcypierre suggested:
```sh
find /var/spool/gammu/outbox/ -mindepth 1 | sort | head -n 1 | xargs -r -d $'\n' mv -t /var/spool/gammu/error/
```
