### ISSUE TITLE
Smsd with mysql does not set delivery report

### ISSUE THREAD

**Issue by m4ucoder** [gammu/gammu#63]
Hello I had a problem with the "delivery report".

In fact I thought it was due to my setup. I configured the "gammu-smsdrc" file to run the "smsc" with mySQL, everything worked except the "delivery report".

Yet when I set it up to make it work with files (service = files), I could see that the "delivery report" worked on seeing the sms spending folder 'sent' folder 'inbox'. So the "delivery report" of SMSC (the supplier) came correctly.

So it was a problem specific to the configuration for mysql.

Looking at the logs, I saw the query:
"SELECT` ID`, status` `,` SendingDateTime`, DeliveryDateTime` `,` SMSCNumber` FROM WHERE `sentitems DeliveryDateTime` IS NULL AND` SenderID` = 'thesenderId' AND `= 190 AND` TPMR` DestinationNumber` = '+ 32485xxxxxx ".

To send the test, I used the following command:
"gammu-smsd-inject TEXT 0485xxxxxx -text" test with delivery report "-report."

It is clear that the two telephone numbers are not the same:
"32485xxxxxx +" and "0485xxxxxx".

By changing the Nos 0485xxxxxx 'by its international version (' + 32485xxxxxx '), the' delivery report 'works!

We must therefore ALWAYS use international numbering.

Sorry for my english

I hope this will help someone ...

**Comment by pavl00** [comment]
It's probably because operator returns in delivery report full international number +32XXXXX and in smsd there is some comparison of the number you sent message and that from delivery report.
For myself I've modified query so that you can send number XXX and delivery report will be checked as XXX or +48XXX
sqlc:
	if (SMSDSQL_option(Config, SQL_QUERY_SAVE_INBOX_SMS_SELECT, "save_inbox_sms_select",
		"SELECT ",
			ESCAPE_FIELD("ID"),
			", ", ESCAPE_FIELD("Status"),
			", ", ESCAPE_FIELD("SendingDateTime"),
			", ", ESCAPE_FIELD("DeliveryDateTime"),
			", ", ESCAPE_FIELD("SMSCNumber"), " "
			"FROM sentitems WHERE ",
			ESCAPE_FIELD("DeliveryDateTime"), " IS NULL AND ",
			ESCAPE_FIELD("SenderID"), " = %P AND ",
			ESCAPE_FIELD("TPMR"), " = %t AND (",
			ESCAPE_FIELD("DestinationNumber"), " = %R OR ",
			ESCAPE_FIELD("DestinationNumber"), " = replace(%R,'+48',''))", NULL) != ERR_NONE) {
		return ERR_UNKNOWN;
	}

**Comment by nijel** [comment]
There is [SkipSMSCNumber](https://wammu.eu/docs/manual/smsd/config.html#option-SkipSMSCNumber) config for this as well..

**Comment by pavl00** [comment]
SkipSMSCNumber works when smsc differs,
 In that problem different is DestinationNumber so that query above returns nothing

**Comment by nijel** [comment]
Ah okay, I didn't get that this is about different number...
