### ISSUE TITLE
Nothing happens when trying to identify SIM900A

### ISSUE THREAD

**Issue by forthrin** [gammu/gammu#748]
Absolutely nothing happens when I try to identify a SIM900A GSM modem connected by a USB to serial adapter on macOS.

I had to make without ODBC support because I got the same build error as #519.

The same thing happens with the Homebrew version.

I can communicate with the device with `screen` or simply `cat` without any problems.

Can anyone help?

```
$ cmake -DWITH_ODBC=OFF 
...
$ cat .gammurc 
[gammu]
device = /dev/cu.usbserial-XXXXXXXX
connection = at

$  time gammu identify
No response in specified timeout. Probably the phone is not connected.
0m30s

$ screen /dev/cu.usbserial-XXXXXXXX
AT+CGMM
SIMCOM_SIM900
```

**Comment by yarmooh** [comment]
Hi,
If you run `gammu -c .gammurc identify` does it produces output?

**Comment by forthrin** [comment]
Suddenly it works with just `gammu identify`, even though I didn't change anything. I have no idea why. Thanks for nudging me to try again. "If at first..." :)
