### ISSUE TITLE
gammu-smsd on el6

### ISSUE THREAD

**Issue by pavkamlc** [gammu/gammu#75]
I found problem after install package into CentOS 6.X server. I used package http://download.opensuse.org/repositories/home:/Nijel/CentOS_CentOS-6/x86_64/gammu-smsd-1.33.0-2.2.x86_64.rpm and after install service cant be configured by service/chkconfig. RH system not support start-stop-daemon and after I tried run witch init script Ive got errors. By commandline works daemon fine.

[root@zenoss ~]# /etc/init.d/gammu-smsd status
/etc/init.d/gammu-smsd: line 144: status_of_proc: command not found
[root@zenoss ~]# /etc/init.d/gammu-smsd start
Starting Gammu SMS Daemon gammu-smsd
/etc/init.d/gammu-smsd: line 85: start-stop-daemon: command not found

**Comment by LordBeaver** [comment]
Similar problem with http://download.opensuse.org/repositories/home:/Nijel/CentOS_7/x86_64/gammu-smsd-1.37.91-1.1.x86_64.rpm

**Comment by nijel** [comment]
Apparently it has been added for some reason again. Patches welcome to make the init script work on CentOS as well.

**Comment by sergiomb2** [comment]
I package gammu on Fedora, we need install libdbi-dbd-sqlite to gammu-smsd pass the test , instead just libdbi-devel, hope this info can help you. 
https://pkgs.fedoraproject.org/cgit/rpms/gammu.git/tree/gammu.spec#n23

**Comment by nijel** [comment]
Indeed sqlite DBI driver is needed (we add it as well https://github.com/gammu/gammu/blob/master/gammu.spec#L50).

The systemd service is installed as well in the RPM package...
