### ISSUE TITLE
SIM card not connecting to network

### ISSUE THREAD

**Issue by mystikxkemix** [gammu/gammu#799]
Hi,

I'm using gammu to get sms from sim cards, and I have an issue when sim cards want to register to the network.
Registration fails when I start using the SIM card with a SIM800C usb stick, but it magically succeed to connect in the night.
From time to time the SIM cards disconnect from the network and take days to reconnect.
Can you help me on this? Here are the logs when I execute the command `gammu monitor 1`

the stdout of the gammu command is this one:

```
Press Ctrl+C to break…
Entering monitor mode…

Enabling info about incoming SMS    : No error.
Enabling info about incoming CB     : No error.
Enabling info about calls           : No error.
Enabling info about USSD            : No error.
SIM phonebook        :   0 used, 250 free
Own numbers          :   1 used,   3 free
Phone phonebook      :   0 used, 100 free
Battery level        : 99 percent
Charge state         : powered from battery
Signal strength      : -61 dBm
Network level        : 78 percent
Bit error rate       : 0 percent
SIM SMS status       : 0 used, 0 unread, 50 locations
Phone SMS status     : 0 used, 0 unread, 50 locations
Network state        : not logged into network
Packet network state : not logged into network
GPRS                 : detached
```

And you can find the debug logs here: [ttyUsb3.log](https://github.com/gammu/gammu/files/11679995/ttyUsb3.log)
Here is the config file used:

```
[gammu]
port = /dev/ttyUSB3
connection = at
logformat = textalldate
logfile = /tmp/log/ttyUSB3.log

[smsd]
Service = null
RunOnReceive = /tmp/on_receive_sms.sh
PhoneID = ttyUSB3
PIN = 1234
```

**Comment by pjarmuzek** [comment]
Hello,

Since your SIMcard is not registering in the network, that's not a gammu-related issue.
