### ISSUE TITLE
unfinite error loop on inserting non-UTF8 character string to DB

### ISSUE THREAD

**Issue by melones** [gammu/gammu#8]
Module: gammu-smsd
Backend: PostgreSQL

Gammu-smsd goes into infinite database insert loop when receiving a sms message with non-UTF8 characters. PostgresSQL database rejects insert of non UTF-8 character into database, and gammu-smsd tries to insert it again in a loop.

Example sms message:  0xD83DDC4D  (which is a "thumb up" sign sent from smartphone)

smsd.log content:

Fri 2013/06/28 10:59:15 gammu-smsd[1870]: Execute SQL: INSERT INTO inbox ("ReceivingDateTime", "Text", "SenderNumber", "Coding", "SMSCNumber", "UDH", "Class", "TextDecoded", "RecipientID") VALUES ('2013-06-19 22:02:30 GMT', 'D83DDC4D', '+32471772353', 'Unicode_No_Compression', '+32475161616', '', -1, '<this was removed because Github also complains about this content>', '')
Fri 2013/06/28 10:59:15 gammu-smsd[1870]: Error: ERROR:  invalid byte sequence for encoding "UTF8": 0xeda0bd
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".

Fri 2013/06/28 10:59:16 gammu-smsd[1870]: SQL failure: 2
Fri 2013/06/28 10:59:16 gammu-smsd[1870]: Error writing to database (SMSDSQL_SaveInboxSMS)
Fri 2013/06/28 10:59:16 gammu-smsd[1870]: Error processing SMS: Unknown error. (UNKNOWN[27])

**Comment by melones** [comment]
Hello nijel,

it seems that the bug wasn't completely fixed. I have setup test environment, compiled the latest gammu-smsd 1.34.0 and tested it again. 

After sending "thumb up" icon (the same as in first report in this bug) from smarthpone to gammu-smsd I get the following error:

Thu 2015/01/29 09:42:51 gammu-smsd[3934]: Received message from: +481234567
Thu 2015/01/29 09:42:51 gammu-smsd[3934]: Read 1 messages
Thu 2015/01/29 09:51:59 gammu-smsd[4424]: Execute SQL: INSERT INTO inbox ("ReceivingDateTime", "Text
", "SenderNumber", "Coding", "SMSCNumber", "UDH", "Class", "TextDecoded", "RecipientID") VALUES ('20
15-01-29 08:41:54 GMT', 'E00E', '+481234567', 'Unicode_No_Compression', '+48790998250', '', -1, '
Ç ', 'smseagle1')
Thu 2015/01/29 09:42:51 gammu-smsd[3934]: Error: ERROR:  invalid byte sequence for encoding "UTF8": 0xf08e808e
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".
Thu 2015/01/29 09:42:51 gammu-smsd[3934]: SQL failure: 2
Thu 2015/01/29 09:42:51 gammu-smsd[3934]: Error writing to database (SMSDSQL_SaveInboxSMS)
Thu 2015/01/29 09:42:51 gammu-smsd[3934]: Error processing SMS: Unknown error (UNKNOWN[27])

And gammu-smsd goes into infinite loop trying to save the sms message to database but without result (the same error is continuosly written into log).

**Comment by nijel** [comment]
Well with MySQL it's different issue, it's utf8 type can not handle all utf8 chars. They have introduced utf8mb4 type to "fix" this see https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

Gammu should probably default to this type...

**Comment by melones** [comment]
Hi nijel,
that's right. But that's a solution limited to MySQL databases. All other (especially Postgres) will still suffer from infinite-loop problem. Maybe this could be fixed easier with replacement char '?' for all non-utf8 chars? 

Something like this (pseudocode): 
if (!IsUTF8(character)) then character = '?'

What do you think?

**Comment by nijel** [comment]
Postgres will not get this error at all...

This problem is MySQL only - the char is valid UTF-8, but MySQL supports only subset of UTF-8 by default...

**Comment by melones** [comment]
Nijel. I experience this error on Postgres database. Both error logs attached above (from gammu 1.33 and gammu 1.34) come from gammu-smsd and Postgres-db - not MySQL.

**Comment by nijel** [comment]
Hmm, actually there is bug in the code, working on that...

**Comment by melones** [comment]
Hi nijel, 

I cloned the master branch from git repo, compiled and tested the fix. Still there is a problem with infinite-loop in gammu-smsd. 

I test this issue with 2 different smarphones: I send a thumb-up emoji to gammu-smsd powered device from both smartphones. With earlier (release 1.34.0 version) with both smartphones gammu-smsd went into infinite-loop after receiving emoji. With fixed version 1.34.90 (including latest commit) now message from first smartphone is received successfully, but message from second smartphone causes again infinite-loop in gammu-smsd. So we have progress, but bug is not eliminated completely :)

Here's the details:
Gammu-smsd version 1.34.90
Built 09:32:57 on Feb 13 2015 using GCC 4.1

_Gammu-Log from first smartphone (when message is received correcly):_
Fri 2015/02/13 09:43:15 gammu-smsd[15693]: Read 1 messages
Fri 2015/02/13 09:43:15 gammu-smsd[15693]: Execute SQL: INSERT INTO inbox ("ReceivingDateTime", "Text", "SenderNumber", "Coding", "SMSCNumber", "UDH", "Class", "TextDecoded", "RecipientID") VALUES ('2015-02-13 08:43:10 GMT', 'E00E', '+482234567', 'Unicode_No_Compression', '+482234567', '', -1, '', 'phone1')
Fri 2015/02/13 09:43:15 gammu-smsd[15693]: Execute SQL: UPDATE phones SET "Received" = "Received" + 1 WHERE "IMEI" = '012142342342342'
Fri 2015/02/13 09:43:15 gammu-smsd[15730]: Starting run on receive: /mnt/ramdisk/htdocs/scripts/daemon.sh 39
Fri 2015/02/13 09:43:22 gammu-smsd[15693]: Process finished successfully

_Gammu-Log from second smartphone (when gammu-smsd is going crazy):_
Fri 2015/02/13 09:44:24 gammu-smsd[15693]: Read 1 messages
Fri 2015/02/13 09:44:24 gammu-smsd[15693]: Execute SQL: INSERT INTO inbox ("ReceivingDateTime", "Text", "SenderNumber", "Coding", "SMSCNumber", "UDH", "Class", "TextDecoded", "RecipientID") VALUES ('2015-02-13 08:44:13 GMT', 'D83DDC4D', '+481234567', 'Unicode_No_Compression', '+481234567', '', -1, '👍���', 'phone1')
Fri 2015/02/13 09:44:24 gammu-smsd[15693]: Error: ERROR:  invalid byte sequence for encoding "UTF8": 0xedb18d
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".
Fri 2015/02/13 09:44:24 gammu-smsd[15693]: SQL failure: 2
Fri 2015/02/13 09:44:24 gammu-smsd[15693]: Error writing to database (SMSDSQL_SaveInboxSMS)
Fri 2015/02/13 09:44:24 gammu-smsd[15693]: Error processing SMS: Unknown error. (UNKNOWN[27])

**Comment by nijel** [comment]
Have you also changed the MySQL table to be utf8mb4? I believe this will be the problem here now as the character is valid utf-8, but can not fit into stadard MySQL's utf8 data type...

**Comment by melones** [comment]
No, I'm using PosgtreSQL database.

**Comment by nijel** [comment]
Ah, I've found another bug in the code, fixed it and added testcase for that...

**Comment by melones** [comment]
I compiled tested the package in several scenarios and now all my integration tests pass. You can close the issue. Thanks a lot!

**Comment by nijel** [comment]
Thanks for verifying that!

**Comment by browndav** [comment]
Hi @nijel,

Preface: This is more of a request for comments than anything else, but you're welcome to do whatever you want with this patch. Saw the mention of UTF-16 and figured I should post.

A while back, I noticed that the multipart splitting code (in the outgoing Unicode-required case) wasn't UTF-16 aware – specifically, it would happily split a UTF-16 surrogate pair in the middle, which meant that the character is visually destroyed if the recipient is unable to reassemble the message (say, if the UDH was stripped by a telco – I've seen this happen in the wild between the US carriers AT&T and T-Mobile).

There was also a similar set of issues with a subset joined characters, specifically where the non-joined components don't make much sense in isolation: for instance, the "regional indicator symbol" flags, or the "combining diacritical marks"; all cases where multiple characters really only make sense when viewed as a single glyph.

This is admittedly a bit of an edge case, but we've been using `libgammu` in developing-country situations where telco behavior/filtering is highly unpredictable, so it made sense at the time for us to patch it. What we've done is decrease the segment size for a single message segment iff splitting it at exactly 70 bytes would cut a (UTF-16) character in half. It seems to be working well for us so far.

Here's a raw diff against an old version, just so you can see what we're doing:
  https://raw.githubusercontent.com/browndav/medic-os/master/platform/source/medic-core-1.6.0/patches/gammu-utf16-sms-multipart.diff

I need to port this forward to the latest version for our internal use regardless; if you're at all interested, I'd be happy to send a PR and/or fix it up in whatever way's needed to merge.

Thanks!

**Comment by nijel** [comment]
Let's discuss this separately: https://github.com/gammu/gammu/issues/95

**Comment by melones** [comment]
Problem came back for multipart messages. More info here: #95

**Comment by nijel** [comment]
See #281 for that. There is no reason to comment that on more issues...

**Comment by handiwijoyo** [comment]
I got this error when using `Mysql ODBC Unicode Driver` on windows machine. Solved by changed it to  `ANSI Driver`

![image](https://user-images.githubusercontent.com/4060094/42261838-a7e5f322-7f93-11e8-8d93-1654e1e15ca5.png)
