### ISSUE TITLE
Running RunOnReceive command many times after long SMS, merging long SMS in one message

### ISSUE THREAD

**Issue by interduo** [gammu/gammu#804]
Gammu run **RunOnReceive** command multipletimes when long SMS received. Its repeatable every time. Is this a bug?
If not - merging SMS is very expected. It should run only once per whole message. 
Could it be implemented?

**Comment by pjarmuzek** [comment]
Can you share the logs?

**Comment by interduo** [comment]
All is OK.  

The mess was done by badly written wrapper script at `runonreceive = script.sh`.
