### ISSUE TITLE
Newest 1.34.0 source build issues

### ISSUE THREAD

**Issue by Paku-** [gammu/gammu#84]
First of all I build using checkinstall utility so I am not sure if it could be a problem but:
1. Starting script calls gammu-smsd from user/bin while after build it's in usr/local/bin
2. libs are located in usr/local/lib and the same - old used to be in /usr/lib.

Know I can change paths but just simple

    $ ./configure
    $ make
    $ make install

 just does not work.

 3. I decided to go for 1.34 as my logs were flooded with "Read 0 msgs" lines. Bad it's still here :( (#79)

    Fri 2015/01/09 15:15:05 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:07 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:08 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:09 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:11 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:12 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:14 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:15 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:16 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:18 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:19 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:20 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:22 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:23 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:25 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:26 gammu-smsd[3538]: Read 0 messages
    Fri 2015/01/09 15:15:27 gammu-smsd[3538]: Read 0 messages

**Comment by nijel** [comment]
The default prefix has always been ``/usr/local/``, you can specify it on command line.

Maybe the problem is that you're still using older libraries with new frontend?

**Comment by Paku-** [comment]
will check this out but what about the "Read 0 messages" flood ??

**Comment by nijel** [comment]
It's probably still same as in #79, that bug has not been fixed...

**Comment by Paku-** [comment]
it's something around but in my case the log is filled even if there is no new SMSs sent or received.
Just every second or two new log entry, all the time.

**Comment by Paku-** [comment]
I rebuild (core.c) adding simple if here:

    /* Log how many messages were read */
    if (GetSMSNumber > 0)
    SMSD_Log(DEBUG_INFO, Config, "Read %d messages", GetSMSNumber);

seems to work.
