### ISSUE TITLE
Published Gammu client for Node.JS

### ISSUE THREAD

**Issue by fulup-bzh** [gammu/gammu#92]
Not a bug but might still interest some Gammu users.

I published a node.js client to Gammu that leverages MySql backend. This client supports both individual and chain of commands in batch mode. It was developed to configure M2M devices.

Package available on both NPM and https://github.com/fulup-bzh/GeoGate/tree/master/smsc

**Comment by nijel** [comment]
Added it to our website, thanks for noticing.
