### ISSUE TITLE
Using Huawei E169 compatible modem with gammu (1.31.90-1+b1)

### ISSUE THREAD

**Issue by dbonengel** [gammu/gammu#94]
Hi there,

I try to configure a Huwaei modem to send SMS using gammu, cannot make out why it doesn't work...
Environment: Debian 'stable' with gammu (1.31.90-1+b1) installed.
lsusb gives me:
> Bus 001 Device 002: ID 12d1:1001 Huawei Technologies Co., Ltd. E169/E620/E800 HSDPA Modem

(The Huwaei E169 is on the HCL and should therefore work)

However, gammu identify gives me the following:

> GerÃ¤t               : /dev/mobile
> Hersteller           : Huawei
> Modell               : E1750 (E1750)
> Firmware             : 11.126.03.01.55
> IMEI                 : 351910048718865
> SIM IMSI             : 262016747062058

My /etc/gammurc:

> [gammu]
> port = /dev/mobile
> model = E169
> connection = at115200
> synchronizetime = yes
> logfile =
> logformat = textalldate
> use_locking = yes
> gammuloc =

Trying to send a SMS gives me the following (and, of course, does not work)
> echo "TEST" | gammu sendsms TEXT +49<mymobilenumber>
> DrÃ¼cken Sie Strg-C, wenn Sie unterbrechen mÃ¶chten...
> Sende SMS 1/1....warte auf Netz-BestÃ¤tiung..Fehler 500, Nachricht-Referenz=-1
> Unbekannter Fehler.

Wether I set 'E169', 'E1750' or simply 'at' as model makes no difference. at19200 as connection makes no difference either

**Comment by dbonengel** [comment]
`
Sun 2015/03/01 09:53:41: [Gammu            - 1.31.90 built 16:37:44 Jun  9 2012 using GCC 4.7]
Sun 2015/03/01 09:53:41: [Connection       - "at19200"]
Sun 2015/03/01 09:53:41: [Connection index - 0]
Sun 2015/03/01 09:53:41: [Model type       - "at"]
Sun 2015/03/01 09:53:41: [Device           - "/dev/mobile"]
Sun 2015/03/01 09:53:41: [Running on       - Linux, kernel 3.2.0-4-686-pae (#1 SMP Debian 3.2.65-1+deb7u2)]
Sun 2015/03/01 09:53:41: [Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|711
Sun 2015/03/01 09:53:41: Locking device
Sun 2015/03/01 09:53:41: Serial device: DTR is up, RTS is up, CAR is up, CTS is up
Sun 2015/03/01 09:53:41: Setting speed to 19200
Sun 2015/03/01 09:53:41: Escaping SMS mode
Sun 2015/03/01 09:53:41: SENDING frametype 0x00/length 0x02/2
Sun 2015/03/01 09:53:41: 1B |0D                                                          ..
Sun 2015/03/01 09:53:42: Sending simple AT command to wake up some devices
Sun 2015/03/01 09:53:42: SENDING frametype 0x00/length 0x03/3
Sun 2015/03/01 09:53:42: 41A|54T|0D                                                      AT.
Sun 2015/03/01 09:53:42: 1 "AT"
Sun 2015/03/01 09:53:42: 2 "OK"
Sun 2015/03/01 09:53:42: Checking line: OK
Sun 2015/03/01 09:53:42: AT reply state: 1
Sun 2015/03/01 09:53:42: RECEIVED frametype 0x00/length 0x09/9
Sun 2015/03/01 09:53:42: 41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..
Sun 2015/03/01 09:53:43: Enabling echo
Sun 2015/03/01 09:53:43: SENDING frametype 0x00/length 0x05/5
Sun 2015/03/01 09:53:43: 41A|54T|45E|311|0D                                              ATE1.
Sun 2015/03/01 09:53:43: 1 "ATE1"
Sun 2015/03/01 09:53:43: 2 "OK"
Sun 2015/03/01 09:53:43: Checking line: OK
Sun 2015/03/01 09:53:43: AT reply state: 1
Sun 2015/03/01 09:53:43: RECEIVED frametype 0x00/length 0x0B/11
Sun 2015/03/01 09:53:43: 41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..
Sun 2015/03/01 09:53:43: Trying Motorola mode switch
Sun 2015/03/01 09:53:43: SENDING frametype 0x00/length 0x0A/10
Sun 2015/03/01 09:53:43: 41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.
Sun 2015/03/01 09:53:43: 1 "AT+MODE=2"
Sun 2015/03/01 09:53:43: 2 "COMMAND NOT SUPPORT"
Sun 2015/03/01 09:53:43: Checking line: COMMAND NOT SUPPORT
Sun 2015/03/01 09:53:43: AT reply state: 3
Sun 2015/03/01 09:53:43: RECEIVED frametype 0x00/length 0x21/33
Sun 2015/03/01 09:53:43: 41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |43C|4FO|4DM|4DM AT+MODE=2...COMM
Sun 2015/03/01 09:53:43: 41A|4EN|44D|20 |4EN|4FO|54T|20 |53S|55U|50P|50P|4FO|52R|54T|0D  AND NOT SUPPORT.
Sun 2015/03/01 09:53:43: 0A                                                              .
Sun 2015/03/01 09:53:43: Seems not to be supported
Sun 2015/03/01 09:53:43: Enabling CME errors
Sun 2015/03/01 09:53:43: SENDING frametype 0x00/length 0x0A/10
Sun 2015/03/01 09:53:43: 41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.
Sun 2015/03/01 09:53:44: 1 "AT+CMEE=1"
Sun 2015/03/01 09:53:44: 2 "OK"
Sun 2015/03/01 09:53:44: Checking line: OK
Sun 2015/03/01 09:53:44: AT reply state: 1
Sun 2015/03/01 09:53:44: RECEIVED frametype 0x00/length 0x10/16
Sun 2015/03/01 09:53:44: 41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
Sun 2015/03/01 09:53:44: SENDING frametype 0x00/length 0x09/9
Sun 2015/03/01 09:53:44: 41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.
Sun 2015/03/01 09:53:44: 1 "AT+CSCS?"
Sun 2015/03/01 09:53:44: 2 "+CSCS: "GSM""
Sun 2015/03/01 09:53:44: 3 "OK"
Sun 2015/03/01 09:53:44: Checking line: OK
Sun 2015/03/01 09:53:44: AT reply state: 1
Sun 2015/03/01 09:53:44: RECEIVED frametype 0x00/length 0x1F/31
Sun 2015/03/01 09:53:44: 41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
Sun 2015/03/01 09:53:44: 3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK..
Sun 2015/03/01 09:53:44: SENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:44: 41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.
Sun 2015/03/01 09:53:45: 1 "AT+CGMI"
Sun 2015/03/01 09:53:45: 2 "huawei"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x18/24
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
Sun 2015/03/01 09:53:45: 0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..
Sun 2015/03/01 09:53:45: Manufacturer info received
Sun 2015/03/01 09:53:45: [Manufacturer: Huawei]
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x0A/10
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.
Sun 2015/03/01 09:53:45: 1 "AT+CSCS=?"
Sun 2015/03/01 09:53:45: 2 "+CSCS: ("IRA","GSM","UCS2")"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x2F/47
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
Sun 2015/03/01 09:53:45: 53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
Sun 2015/03/01 09:53:45: 22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK..
Sun 2015/03/01 09:53:45: Chosen GSM as normal charset
Sun 2015/03/01 09:53:45: Chosen UCS2 as unicode charset
Sun 2015/03/01 09:53:45: Getting model
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.
Sun 2015/03/01 09:53:45: 1 "AT+CGMM"
Sun 2015/03/01 09:53:45: 2 "E1750"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x17/23
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |45E|311|377|355|300|0D  AT+CGMM...E1750.
Sun 2015/03/01 09:53:45: 0A |0D |0A |4FO|4BK|0D |0A                                      ...OK..
Sun 2015/03/01 09:53:45: [Model name: `E1750']
Sun 2015/03/01 09:53:45: [Model data: `E1750']
Sun 2015/03/01 09:53:45: [Model data: `E1750']
Sun 2015/03/01 09:53:45: [Connected model  - "E1750"]
Sun 2015/03/01 09:53:45: Checking for OBEX support
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x0B/11
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.
Sun 2015/03/01 09:53:45: 1 "AT+CPROT=?"
Sun 2015/03/01 09:53:45: 2 "COMMAND NOT SUPPORT"
Sun 2015/03/01 09:53:45: Checking line: COMMAND NOT SUPPORT
Sun 2015/03/01 09:53:45: AT reply state: 3
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x22/34
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |43C|4FO|4DM AT+CPROT=?...COM
Sun 2015/03/01 09:53:45: 4DM|41A|4EN|44D|20 |4EN|4FO|54T|20 |53S|55U|50P|50P|4FO|52R|54T MAND NOT SUPPORT
Sun 2015/03/01 09:53:45: 0D |0A                                                          ..
Sun 2015/03/01 09:53:45: Checking for SYNCML/OBEX support
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x0C/12
Sun 2015/03/01 09:53:45: 41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.
Sun 2015/03/01 09:53:45: 1 "AT+SYNCML=?"
Sun 2015/03/01 09:53:45: 2 "COMMAND NOT SUPPORT"
Sun 2015/03/01 09:53:45: Checking line: COMMAND NOT SUPPORT
Sun 2015/03/01 09:53:45: AT reply state: 3
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x23/35
Sun 2015/03/01 09:53:45: 41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |43C|4FO AT+SYNCML=?...CO
Sun 2015/03/01 09:53:45: 4DM|4DM|41A|4EN|44D|20 |4EN|4FO|54T|20 |53S|55U|50P|50P|4FO|52R MMAND NOT SUPPOR
Sun 2015/03/01 09:53:45: 54T|0D |0A                                                      T..
Sun 2015/03/01 09:53:45: Checking for SYNCML/OBEX support
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x0D/13
Sun 2015/03/01 09:53:45: 41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.
Sun 2015/03/01 09:53:45: 1 "AT$TSSPCSW=?"
Sun 2015/03/01 09:53:45: 2 "COMMAND NOT SUPPORT"
Sun 2015/03/01 09:53:45: Checking line: COMMAND NOT SUPPORT
Sun 2015/03/01 09:53:45: AT reply state: 3
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x24/36
Sun 2015/03/01 09:53:45: 41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |43C AT$TSSPCSW=?...C
Sun 2015/03/01 09:53:45: 4FO|4DM|4DM|41A|4EN|44D|20 |4EN|4FO|54T|20 |53S|55U|50P|50P|4FO OMMAND NOT SUPPO
Sun 2015/03/01 09:53:45: 52R|54T|0D |0A                                                  RT..
Sun 2015/03/01 09:53:45: Setting date & time
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x21/33
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|300|333 AT+CCLK="2015/03
Sun 2015/03/01 09:53:45: 2F/|300|311|2C,|300|399|3A:|355|333|3A:|344|355|2B+|300|300|22" /01,09:53:45+00"
Sun 2015/03/01 09:53:45: 0D                                                              .
Sun 2015/03/01 09:53:45: 1 "AT+CCLK="2015/03/01,09:53:45+00""
Sun 2015/03/01 09:53:45: 2 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x27/39
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|43C|4CL|4BK|3D=|22"|322|300|311|355|2F/|300|333 AT+CCLK="2015/03
Sun 2015/03/01 09:53:45: 2F/|300|311|2C,|300|399|3A:|355|333|3A:|344|355|2B+|300|300|22" /01,09:53:45+00"
Sun 2015/03/01 09:53:45: 0D |0D |0A |4FO|4BK|0D |0A                                      ...OK..
Sun 2015/03/01 09:53:45: Getting firmware versions
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.
Sun 2015/03/01 09:53:45: 1 "AT+CGMR"
Sun 2015/03/01 09:53:45: 2 "11.126.03.01.55"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x21/33
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|311|322|366 AT+CGMR...11.126
Sun 2015/03/01 09:53:45: 2E.|300|333|2E.|300|311|2E.|355|355|0D |0A |0D |0A |4FO|4BK|0D  .03.01.55....OK.
Sun 2015/03/01 09:53:45: 0A                                                              .
Sun 2015/03/01 09:53:45: Received firmware version: "11.126.03.01.55"
Sun 2015/03/01 09:53:45: Number version is "11,126030"
Sun 2015/03/01 09:53:45: [Firmware version - "11.126.03.01.55"]
Sun 2015/03/01 09:53:45: [Connected]
Sun 2015/03/01 09:53:45: Entering GSM_GetManufacturer
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.
Sun 2015/03/01 09:53:45: 1 "AT+CGMI"
Sun 2015/03/01 09:53:45: 2 "huawei"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x18/24
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
Sun 2015/03/01 09:53:45: 0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..
Sun 2015/03/01 09:53:45: Manufacturer info received
Sun 2015/03/01 09:53:45: [Manufacturer: Huawei]
Sun 2015/03/01 09:53:45: Leaving GSM_GetManufacturer
Sun 2015/03/01 09:53:45: Entering GSM_GetModel
Sun 2015/03/01 09:53:45: Getting model
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.
Sun 2015/03/01 09:53:45: 1 "AT+CGMM"
Sun 2015/03/01 09:53:45: 2 "E1750"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x17/23
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |45E|311|377|355|300|0D  AT+CGMM...E1750.
Sun 2015/03/01 09:53:45: 0A |0D |0A |4FO|4BK|0D |0A                                      ...OK..
Sun 2015/03/01 09:53:45: [Model name: `E1750']
Sun 2015/03/01 09:53:45: [Model data: `E1750']
Sun 2015/03/01 09:53:45: [Model data: `E1750']
Sun 2015/03/01 09:53:45: Leaving GSM_GetModel
Sun 2015/03/01 09:53:45: Entering GSM_GetFirmware
Sun 2015/03/01 09:53:45: Getting firmware versions
Sun 2015/03/01 09:53:45: SENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.
Sun 2015/03/01 09:53:45: 1 "AT+CGMR"
Sun 2015/03/01 09:53:45: 2 "11.126.03.01.55"
Sun 2015/03/01 09:53:45: 3 "OK"
Sun 2015/03/01 09:53:45: Checking line: OK
Sun 2015/03/01 09:53:45: AT reply state: 1
Sun 2015/03/01 09:53:45: RECEIVED frametype 0x00/length 0x21/33
Sun 2015/03/01 09:53:45: 41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|311|322|366 AT+CGMR...11.126
Sun 2015/03/01 09:53:45: 2E.|300|333|2E.|300|311|2E.|355|355|0D |0A |0D |0A |4FO|4BK|0D  .03.01.55....OK.
Sun 2015/03/01 09:53:45: 0A                                                              .
Sun 2015/03/01 09:53:45: Received firmware version: "11.126.03.01.55"
Sun 2015/03/01 09:53:45: Number version is "11,126030"
Sun 2015/03/01 09:53:45: [Firmware version - "11.126.03.01.55"]
Sun 2015/03/01 09:53:45: Leaving GSM_GetFirmware
Sun 2015/03/01 09:53:45: Entering GSM_GetPPM
Sun 2015/03/01 09:53:45: GSM_GetPPM failed with error NOTSUPPORTED[21]: Funktion wird nicht vom Telefon unterstÃ¼tzt.
Sun 2015/03/01 09:53:45: GLeaving GSM_GetPPM
Sun 2015/03/01 09:53:45: GEntering GSM_GetHardware
Sun 2015/03/01 09:53:45: GGSM_GetHardware failed with error NOTSUPPORTED[21]: Funktion wird nicht vom Telefon unterstÃ¼tzt.
Sun 2015/03/01 09:53:45: GGLeaving GSM_GetHardware
Sun 2015/03/01 09:53:45: GGEntering GSM_GetIMEI
Sun 2015/03/01 09:53:45: GGGetting IMEI
Sun 2015/03/01 09:53:45: GGSENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: GG41A|54T|2B+|43C|47G|53S|4EN|0D                                  AT+CGSN.
Sun 2015/03/01 09:53:45: GG1 "AT+CGSN"
Sun 2015/03/01 09:53:45: GG2 "351910048718865"
Sun 2015/03/01 09:53:45: GG3 "OK"
Sun 2015/03/01 09:53:45: GGChecking line: OK
Sun 2015/03/01 09:53:45: GGAT reply state: 1
Sun 2015/03/01 09:53:45: GGRECEIVED frametype 0x00/length 0x21/33
Sun 2015/03/01 09:53:45: GG41A|54T|2B+|43C|47G|53S|4EN|0D |0D |0A |333|355|311|399|311|300 AT+CGSN...351910
Sun 2015/03/01 09:53:45: GG300|344|388|377|311|388|388|366|355|0D |0A |0D |0A |4FO|4BK|0D  048718865....OK.
Sun 2015/03/01 09:53:45: GG0A                                                              .
Sun 2015/03/01 09:53:45: GGReceived IMEI 351910048718865
Sun 2015/03/01 09:53:45: GGLeaving GSM_GetIMEI
Sun 2015/03/01 09:53:45: GGEntering GSM_GetOriginalIMEI
Sun 2015/03/01 09:53:45: GGGSM_GetOriginalIMEI failed with error NOTSUPPORTED[21]: Funktion wird nicht vom Telefon unterstÃ¼tzt.
Sun 2015/03/01 09:53:45: GGGLeaving GSM_GetOriginalIMEI
Sun 2015/03/01 09:53:45: GGGEntering GSM_GetManufactureMonth
Sun 2015/03/01 09:53:45: GGGGSM_GetManufactureMonth failed with error NOTSUPPORTED[21]: Funktion wird nicht vom Telefon unterstÃ¼tzt.
Sun 2015/03/01 09:53:45: GGGGLeaving GSM_GetManufactureMonth
Sun 2015/03/01 09:53:45: GGGGEntering GSM_GetProductCode
Sun 2015/03/01 09:53:45: GGGGGSM_GetProductCode failed with error NOTSUPPORTED[21]: Funktion wird nicht vom Telefon unterstÃ¼tzt.
Sun 2015/03/01 09:53:45: GGGGGLeaving GSM_GetProductCode
Sun 2015/03/01 09:53:45: GGGGGEntering GSM_GetSIMIMSI
Sun 2015/03/01 09:53:45: GGGGGGetting SIM IMSI
Sun 2015/03/01 09:53:45: GGGGGSENDING frametype 0x00/length 0x08/8
Sun 2015/03/01 09:53:45: GGGGG41A|54T|2B+|43C|49I|4DM|49I|0D                                  AT+CIMI.
Sun 2015/03/01 09:53:45: GGGGG1 "AT+CIMI"
Sun 2015/03/01 09:53:45: GGGGG2 "262016747062058"
Sun 2015/03/01 09:53:45: GGGGG3 "OK"
Sun 2015/03/01 09:53:45: GGGGGChecking line: OK
Sun 2015/03/01 09:53:45: GGGGGAT reply state: 1
Sun 2015/03/01 09:53:45: GGGGGRECEIVED frametype 0x00/length 0x21/33
Sun 2015/03/01 09:53:45: GGGGG41A|54T|2B+|43C|49I|4DM|49I|0D |0D |0A |322|366|322|300|311|366 AT+CIMI...262016
Sun 2015/03/01 09:53:45: GGGGG377|344|377|300|366|322|300|355|388|0D |0A |0D |0A |4FO|4BK|0D  747062058....OK.
Sun 2015/03/01 09:53:45: GGGGG0A                                                              .
Sun 2015/03/01 09:53:45: GGGGGReceived IMSI 262016747062058
Sun 2015/03/01 09:53:45: GGGGGLeaving GSM_GetSIMIMSI
Sun 2015/03/01 09:53:45: GGGGG[Terminating]
Sun 2015/03/01 09:53:45: GGGGG[Closing]


`

**Comment by nijel** [comment]
Have you tried using latest versoin? There has been many bug fixes meanwhile...

**Comment by dbonengel** [comment]
Hi, Michal, no I didn't, but this problem can be closed nevertheless.
Both Linux box and the GSM modem are being provided by and located at a Customer of mine, and he discovered this to be a problem with the SIM of the modem. Looks like the correspondending contract does not allow sending SMS (not sure exactly)
If he puts in his own, private SIM the modem works as expected!
Ball on his side!

Thanks in any case for the excellent work!

Dirk
