### ISSUE TITLE
wammu new bug

### ISSUE THREAD

**Issue by pop1** [gammu/gammu#96]
![screenshot from 2015-03-05 11 54 10](https://cloud.githubusercontent.com/assets/11329917/6502916/8bb21ba4-c330-11e4-893a-1a58d60d64ff.png)

**Comment by nijel** [comment]
Already fixed in https://github.com/gammu/wammu/commit/db23e424d2bd97283b0a7c7bbc4a95a584ec6f1e, please upgrade.
