### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by kleinsasserm** [gammu/gammu#98]
First of all, this is a great piece of software! A collegue of mine an I are currently programming a SMS gateway including a cherrypy web-frontend and services. Therefore we are using Python 3. As I can see, the current release is not Python 3 compatible - are you having plans to support Python 3 in the near future?

**Comment by nijel** [comment]
Currently nobody is working on this, but patches are always welcome :-).

**Comment by kleinsasserm** [comment]
:+1: Maybe  we will have a look at it :)

**Comment by nijel** [comment]
The basic infrastructure is done at https://github.com/nijel/python-gammu, but more work is needed, especiall in string handling...

**Comment by kleinsasserm** [comment]
Forked it. Looks good! I will try to find a way to wok through the Python C-API stuff...

**Comment by nijel** [comment]
And there is now first version which builds and passes testsuite for both Python 2 and 3: https://travis-ci.org/nijel/python-gammu/builds/56087763

But it needs more testing and I'm affraid there is still some problem as the module occasionally segfaults on the CI server (I failed to produce this locally and also valgrind is not much helpful).

**Comment by nijel** [comment]
The code is now https://github.com/gammu/python-gammu, but needs deeper testing.

**Comment by kleinsasserm** [comment]
:+1:  I received your blog news (from your private site) through Debian Planet also. Glad and proud that I helped a very tiny little bit :). I will try to test it further!

**Comment by nijel** [comment]
Released today. Should there be any bugs, please report to it's issue tracker: https://github.com/gammu/python-gammu/issues

**Comment by kleinsasserm** [comment]
Wow thanks! I'am currently very busy, but we will test it in the near future!
