### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by RajivTyagi** [gammu/gammu#99]
I am using a Simcom SIM900A GSM/GPRS module connected to Wammu via /dev/ttyS0. Everything works seamlessly, except the following:

1. Send SMS to multiple recipients:
I did CTRL-M - Edit and selected multiple recipients. The recipients I selected were visible in the "Recipient's numbers" dialogue, each separated by a space from the following number. Then typed the number and sent the message. Gammu fails to send any message and marks the message Unsent for all recipients. However, sending messages one by one succeeds.

**Comment by nijel** [comment]
Moved to correct issue tracker: https://github.com/gammu/wammu/issues/9
